// Code generated by Kitex v0.16.2. DO NOT EDIT.

package businessfoundationservicev1

import (
	"context"
	foundationv1 "github.com/FigoGoo/Dora-Agent/agent/kitex_gen/foundationv1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Probe(ctx context.Context, request *foundationv1.FoundationProbeRequestV1, callOptions ...callopt.Option) (r *foundationv1.FoundationProbeResponseV1, err error)
	GetCreationSpecContextPreviewV1(ctx context.Context, request *foundationv1.GetCreationSpecContextPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.GetCreationSpecContextPreviewResponseV1, err error)
	SaveCreationSpecDraftPreviewV1(ctx context.Context, request *foundationv1.SaveCreationSpecDraftPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.SaveCreationSpecDraftPreviewResponseV1, err error)
	QueryCreationSpecDraftCommandPreviewV1(ctx context.Context, request *foundationv1.QueryCreationSpecDraftCommandPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.QueryCreationSpecDraftCommandPreviewResponseV1, err error)
	BatchGetAssetAnalysisInputsPreviewV1(ctx context.Context, request *foundationv1.BatchGetAssetAnalysisInputsPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.BatchGetAssetAnalysisInputsPreviewResponseV1, err error)
	GetStoryboardPlanningContextPreviewV1(ctx context.Context, request *foundationv1.GetStoryboardPlanningContextPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.GetStoryboardPlanningContextPreviewResponseV1, err error)
	SaveStoryboardDraftPreviewV1(ctx context.Context, request *foundationv1.SaveStoryboardDraftPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.SaveStoryboardDraftPreviewResponseV1, err error)
	QueryStoryboardDraftCommandPreviewV1(ctx context.Context, request *foundationv1.QueryStoryboardDraftCommandPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.QueryStoryboardDraftCommandPreviewResponseV1, err error)
	GetPromptGenerationContextPreviewV1(ctx context.Context, request *foundationv1.GetPromptGenerationContextPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.GetPromptGenerationContextPreviewResponseV1, err error)
	SavePromptDraftPreviewV1(ctx context.Context, request *foundationv1.SavePromptDraftPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.SavePromptDraftPreviewResponseV1, err error)
	QueryPromptDraftCommandPreviewV1(ctx context.Context, request *foundationv1.QueryPromptDraftCommandPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.QueryPromptDraftCommandPreviewResponseV1, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kBusinessFoundationServiceV1Client{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kBusinessFoundationServiceV1Client struct {
	*kClient
}

func (p *kBusinessFoundationServiceV1Client) Probe(ctx context.Context, request *foundationv1.FoundationProbeRequestV1, callOptions ...callopt.Option) (r *foundationv1.FoundationProbeResponseV1, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Probe(ctx, request)
}

func (p *kBusinessFoundationServiceV1Client) GetCreationSpecContextPreviewV1(ctx context.Context, request *foundationv1.GetCreationSpecContextPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.GetCreationSpecContextPreviewResponseV1, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCreationSpecContextPreviewV1(ctx, request)
}

func (p *kBusinessFoundationServiceV1Client) SaveCreationSpecDraftPreviewV1(ctx context.Context, request *foundationv1.SaveCreationSpecDraftPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.SaveCreationSpecDraftPreviewResponseV1, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SaveCreationSpecDraftPreviewV1(ctx, request)
}

func (p *kBusinessFoundationServiceV1Client) QueryCreationSpecDraftCommandPreviewV1(ctx context.Context, request *foundationv1.QueryCreationSpecDraftCommandPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.QueryCreationSpecDraftCommandPreviewResponseV1, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryCreationSpecDraftCommandPreviewV1(ctx, request)
}

func (p *kBusinessFoundationServiceV1Client) BatchGetAssetAnalysisInputsPreviewV1(ctx context.Context, request *foundationv1.BatchGetAssetAnalysisInputsPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.BatchGetAssetAnalysisInputsPreviewResponseV1, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchGetAssetAnalysisInputsPreviewV1(ctx, request)
}

func (p *kBusinessFoundationServiceV1Client) GetStoryboardPlanningContextPreviewV1(ctx context.Context, request *foundationv1.GetStoryboardPlanningContextPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.GetStoryboardPlanningContextPreviewResponseV1, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetStoryboardPlanningContextPreviewV1(ctx, request)
}

func (p *kBusinessFoundationServiceV1Client) SaveStoryboardDraftPreviewV1(ctx context.Context, request *foundationv1.SaveStoryboardDraftPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.SaveStoryboardDraftPreviewResponseV1, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SaveStoryboardDraftPreviewV1(ctx, request)
}

func (p *kBusinessFoundationServiceV1Client) QueryStoryboardDraftCommandPreviewV1(ctx context.Context, request *foundationv1.QueryStoryboardDraftCommandPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.QueryStoryboardDraftCommandPreviewResponseV1, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryStoryboardDraftCommandPreviewV1(ctx, request)
}

func (p *kBusinessFoundationServiceV1Client) GetPromptGenerationContextPreviewV1(ctx context.Context, request *foundationv1.GetPromptGenerationContextPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.GetPromptGenerationContextPreviewResponseV1, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPromptGenerationContextPreviewV1(ctx, request)
}

func (p *kBusinessFoundationServiceV1Client) SavePromptDraftPreviewV1(ctx context.Context, request *foundationv1.SavePromptDraftPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.SavePromptDraftPreviewResponseV1, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SavePromptDraftPreviewV1(ctx, request)
}

func (p *kBusinessFoundationServiceV1Client) QueryPromptDraftCommandPreviewV1(ctx context.Context, request *foundationv1.QueryPromptDraftCommandPreviewRequestV1, callOptions ...callopt.Option) (r *foundationv1.QueryPromptDraftCommandPreviewResponseV1, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryPromptDraftCommandPreviewV1(ctx, request)
}
