// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package businessskillmarketplace

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
)

type SkillVersionStatus int64

const (
	SkillVersionStatus_DRAFT      SkillVersionStatus = 1
	SkillVersionStatus_SUBMITTED  SkillVersionStatus = 2
	SkillVersionStatus_REVIEWING  SkillVersionStatus = 3
	SkillVersionStatus_REJECTED   SkillVersionStatus = 4
	SkillVersionStatus_PUBLISHED  SkillVersionStatus = 5
	SkillVersionStatus_DEPRECATED SkillVersionStatus = 6
	SkillVersionStatus_REMOVED    SkillVersionStatus = 7
)

func (p SkillVersionStatus) String() string {
	switch p {
	case SkillVersionStatus_DRAFT:
		return "DRAFT"
	case SkillVersionStatus_SUBMITTED:
		return "SUBMITTED"
	case SkillVersionStatus_REVIEWING:
		return "REVIEWING"
	case SkillVersionStatus_REJECTED:
		return "REJECTED"
	case SkillVersionStatus_PUBLISHED:
		return "PUBLISHED"
	case SkillVersionStatus_DEPRECATED:
		return "DEPRECATED"
	case SkillVersionStatus_REMOVED:
		return "REMOVED"
	}
	return "<UNSET>"
}

func SkillVersionStatusFromString(s string) (SkillVersionStatus, error) {
	switch s {
	case "DRAFT":
		return SkillVersionStatus_DRAFT, nil
	case "SUBMITTED":
		return SkillVersionStatus_SUBMITTED, nil
	case "REVIEWING":
		return SkillVersionStatus_REVIEWING, nil
	case "REJECTED":
		return SkillVersionStatus_REJECTED, nil
	case "PUBLISHED":
		return SkillVersionStatus_PUBLISHED, nil
	case "DEPRECATED":
		return SkillVersionStatus_DEPRECATED, nil
	case "REMOVED":
		return SkillVersionStatus_REMOVED, nil
	}
	return SkillVersionStatus(0), fmt.Errorf("not a valid SkillVersionStatus string")
}

func SkillVersionStatusPtr(v SkillVersionStatus) *SkillVersionStatus { return &v }
func (p *SkillVersionStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = SkillVersionStatus(result.Int64)
	return
}

func (p *SkillVersionStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type MarketplaceListingStatus int64

const (
	MarketplaceListingStatus_DRAFT                  MarketplaceListingStatus = 1
	MarketplaceListingStatus_PENDING_LISTING_REVIEW MarketplaceListingStatus = 2
	MarketplaceListingStatus_LISTED                 MarketplaceListingStatus = 3
	MarketplaceListingStatus_UNLISTED               MarketplaceListingStatus = 4
	MarketplaceListingStatus_SUSPENDED              MarketplaceListingStatus = 5
	MarketplaceListingStatus_REMOVED                MarketplaceListingStatus = 6
)

func (p MarketplaceListingStatus) String() string {
	switch p {
	case MarketplaceListingStatus_DRAFT:
		return "DRAFT"
	case MarketplaceListingStatus_PENDING_LISTING_REVIEW:
		return "PENDING_LISTING_REVIEW"
	case MarketplaceListingStatus_LISTED:
		return "LISTED"
	case MarketplaceListingStatus_UNLISTED:
		return "UNLISTED"
	case MarketplaceListingStatus_SUSPENDED:
		return "SUSPENDED"
	case MarketplaceListingStatus_REMOVED:
		return "REMOVED"
	}
	return "<UNSET>"
}

func MarketplaceListingStatusFromString(s string) (MarketplaceListingStatus, error) {
	switch s {
	case "DRAFT":
		return MarketplaceListingStatus_DRAFT, nil
	case "PENDING_LISTING_REVIEW":
		return MarketplaceListingStatus_PENDING_LISTING_REVIEW, nil
	case "LISTED":
		return MarketplaceListingStatus_LISTED, nil
	case "UNLISTED":
		return MarketplaceListingStatus_UNLISTED, nil
	case "SUSPENDED":
		return MarketplaceListingStatus_SUSPENDED, nil
	case "REMOVED":
		return MarketplaceListingStatus_REMOVED, nil
	}
	return MarketplaceListingStatus(0), fmt.Errorf("not a valid MarketplaceListingStatus string")
}

func MarketplaceListingStatusPtr(v MarketplaceListingStatus) *MarketplaceListingStatus { return &v }
func (p *MarketplaceListingStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = MarketplaceListingStatus(result.Int64)
	return
}

func (p *MarketplaceListingStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type InstallationScope int64

const (
	InstallationScope_PERSONAL   InstallationScope = 1
	InstallationScope_ENTERPRISE InstallationScope = 2
)

func (p InstallationScope) String() string {
	switch p {
	case InstallationScope_PERSONAL:
		return "PERSONAL"
	case InstallationScope_ENTERPRISE:
		return "ENTERPRISE"
	}
	return "<UNSET>"
}

func InstallationScopeFromString(s string) (InstallationScope, error) {
	switch s {
	case "PERSONAL":
		return InstallationScope_PERSONAL, nil
	case "ENTERPRISE":
		return InstallationScope_ENTERPRISE, nil
	}
	return InstallationScope(0), fmt.Errorf("not a valid InstallationScope string")
}

func InstallationScopePtr(v InstallationScope) *InstallationScope { return &v }
func (p *InstallationScope) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = InstallationScope(result.Int64)
	return
}

func (p *InstallationScope) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type MarketplaceListingDTO struct {
	ListingId           string                   `thrift:"listing_id,1,required" frugal:"1,required,string" json:"listing_id"`
	SkillId             string                   `thrift:"skill_id,2,required" frugal:"2,required,string" json:"skill_id"`
	SkillVersionId      string                   `thrift:"skill_version_id,3,required" frugal:"3,required,string" json:"skill_version_id"`
	Status              MarketplaceListingStatus `thrift:"status,4,required" frugal:"4,required,MarketplaceListingStatus" json:"status"`
	PricingPolicyDigest string                   `thrift:"pricing_policy_digest,5,required" frugal:"5,required,string" json:"pricing_policy_digest"`
	CreatedAt           string                   `thrift:"created_at,6,required" frugal:"6,required,string" json:"created_at"`
	UpdatedAt           string                   `thrift:"updated_at,7,required" frugal:"7,required,string" json:"updated_at"`
}

func NewMarketplaceListingDTO() *MarketplaceListingDTO {
	return &MarketplaceListingDTO{}
}

func (p *MarketplaceListingDTO) InitDefault() {
}

func (p *MarketplaceListingDTO) GetListingId() (v string) {
	return p.ListingId
}

func (p *MarketplaceListingDTO) GetSkillId() (v string) {
	return p.SkillId
}

func (p *MarketplaceListingDTO) GetSkillVersionId() (v string) {
	return p.SkillVersionId
}

func (p *MarketplaceListingDTO) GetStatus() (v MarketplaceListingStatus) {
	return p.Status
}

func (p *MarketplaceListingDTO) GetPricingPolicyDigest() (v string) {
	return p.PricingPolicyDigest
}

func (p *MarketplaceListingDTO) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *MarketplaceListingDTO) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}
func (p *MarketplaceListingDTO) SetListingId(val string) {
	p.ListingId = val
}
func (p *MarketplaceListingDTO) SetSkillId(val string) {
	p.SkillId = val
}
func (p *MarketplaceListingDTO) SetSkillVersionId(val string) {
	p.SkillVersionId = val
}
func (p *MarketplaceListingDTO) SetStatus(val MarketplaceListingStatus) {
	p.Status = val
}
func (p *MarketplaceListingDTO) SetPricingPolicyDigest(val string) {
	p.PricingPolicyDigest = val
}
func (p *MarketplaceListingDTO) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *MarketplaceListingDTO) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}

func (p *MarketplaceListingDTO) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MarketplaceListingDTO(%+v)", *p)
}

var fieldIDToName_MarketplaceListingDTO = map[int16]string{
	1: "listing_id",
	2: "skill_id",
	3: "skill_version_id",
	4: "status",
	5: "pricing_policy_digest",
	6: "created_at",
	7: "updated_at",
}

type SkillInstallationDTO struct {
	InstallationId   string            `thrift:"installation_id,1,required" frugal:"1,required,string" json:"installation_id"`
	AccountId        string            `thrift:"account_id,2,required" frugal:"2,required,string" json:"account_id"`
	AccountScope     InstallationScope `thrift:"account_scope,3,required" frugal:"3,required,InstallationScope" json:"account_scope"`
	ListingId        string            `thrift:"listing_id,4,required" frugal:"4,required,string" json:"listing_id"`
	SkillId          string            `thrift:"skill_id,5,required" frugal:"5,required,string" json:"skill_id"`
	InstalledVersion string            `thrift:"installed_version,6,required" frugal:"6,required,string" json:"installed_version"`
	VersionStrategy  string            `thrift:"version_strategy,7,required" frugal:"7,required,string" json:"version_strategy"`
	Status           string            `thrift:"status,8,required" frugal:"8,required,string" json:"status"`
	UpgradeStatus    string            `thrift:"upgrade_status,9,required" frugal:"9,required,string" json:"upgrade_status"`
	CreatedAt        string            `thrift:"created_at,10,required" frugal:"10,required,string" json:"created_at"`
	UpdatedAt        string            `thrift:"updated_at,11,required" frugal:"11,required,string" json:"updated_at"`
}

func NewSkillInstallationDTO() *SkillInstallationDTO {
	return &SkillInstallationDTO{}
}

func (p *SkillInstallationDTO) InitDefault() {
}

func (p *SkillInstallationDTO) GetInstallationId() (v string) {
	return p.InstallationId
}

func (p *SkillInstallationDTO) GetAccountId() (v string) {
	return p.AccountId
}

func (p *SkillInstallationDTO) GetAccountScope() (v InstallationScope) {
	return p.AccountScope
}

func (p *SkillInstallationDTO) GetListingId() (v string) {
	return p.ListingId
}

func (p *SkillInstallationDTO) GetSkillId() (v string) {
	return p.SkillId
}

func (p *SkillInstallationDTO) GetInstalledVersion() (v string) {
	return p.InstalledVersion
}

func (p *SkillInstallationDTO) GetVersionStrategy() (v string) {
	return p.VersionStrategy
}

func (p *SkillInstallationDTO) GetStatus() (v string) {
	return p.Status
}

func (p *SkillInstallationDTO) GetUpgradeStatus() (v string) {
	return p.UpgradeStatus
}

func (p *SkillInstallationDTO) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *SkillInstallationDTO) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}
func (p *SkillInstallationDTO) SetInstallationId(val string) {
	p.InstallationId = val
}
func (p *SkillInstallationDTO) SetAccountId(val string) {
	p.AccountId = val
}
func (p *SkillInstallationDTO) SetAccountScope(val InstallationScope) {
	p.AccountScope = val
}
func (p *SkillInstallationDTO) SetListingId(val string) {
	p.ListingId = val
}
func (p *SkillInstallationDTO) SetSkillId(val string) {
	p.SkillId = val
}
func (p *SkillInstallationDTO) SetInstalledVersion(val string) {
	p.InstalledVersion = val
}
func (p *SkillInstallationDTO) SetVersionStrategy(val string) {
	p.VersionStrategy = val
}
func (p *SkillInstallationDTO) SetStatus(val string) {
	p.Status = val
}
func (p *SkillInstallationDTO) SetUpgradeStatus(val string) {
	p.UpgradeStatus = val
}
func (p *SkillInstallationDTO) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *SkillInstallationDTO) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}

func (p *SkillInstallationDTO) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SkillInstallationDTO(%+v)", *p)
}

var fieldIDToName_SkillInstallationDTO = map[int16]string{
	1:  "installation_id",
	2:  "account_id",
	3:  "account_scope",
	4:  "listing_id",
	5:  "skill_id",
	6:  "installed_version",
	7:  "version_strategy",
	8:  "status",
	9:  "upgrade_status",
	10: "created_at",
	11: "updated_at",
}

type SkillUsageRecordDTO struct {
	UsageId             string  `thrift:"usage_id,1,required" frugal:"1,required,string" json:"usage_id"`
	RunId               string  `thrift:"run_id,2,required" frugal:"2,required,string" json:"run_id"`
	ListingId           string  `thrift:"listing_id,3,required" frugal:"3,required,string" json:"listing_id"`
	SkillId             string  `thrift:"skill_id,4,required" frugal:"4,required,string" json:"skill_id"`
	SkillVersion        string  `thrift:"skill_version,5,required" frugal:"5,required,string" json:"skill_version"`
	PricingPolicyDigest string  `thrift:"pricing_policy_digest,6,required" frugal:"6,required,string" json:"pricing_policy_digest"`
	SkillUsageDigest    string  `thrift:"skill_usage_digest,7,required" frugal:"7,required,string" json:"skill_usage_digest"`
	UsageStatus         string  `thrift:"usage_status,8,required" frugal:"8,required,string" json:"usage_status"`
	ChargeStatus        string  `thrift:"charge_status,9,required" frugal:"9,required,string" json:"charge_status"`
	RefundStatus        string  `thrift:"refund_status,10,required" frugal:"10,required,string" json:"refund_status"`
	SettlementStatus    string  `thrift:"settlement_status,11,required" frugal:"11,required,string" json:"settlement_status"`
	EstimatedCredits    int64   `thrift:"estimated_credits,12,required" frugal:"12,required,i64" json:"estimated_credits"`
	CreditHoldId        *string `thrift:"credit_hold_id,13,optional" frugal:"13,optional,string" json:"credit_hold_id,omitempty"`
}

func NewSkillUsageRecordDTO() *SkillUsageRecordDTO {
	return &SkillUsageRecordDTO{}
}

func (p *SkillUsageRecordDTO) InitDefault() {
}

func (p *SkillUsageRecordDTO) GetUsageId() (v string) {
	return p.UsageId
}

func (p *SkillUsageRecordDTO) GetRunId() (v string) {
	return p.RunId
}

func (p *SkillUsageRecordDTO) GetListingId() (v string) {
	return p.ListingId
}

func (p *SkillUsageRecordDTO) GetSkillId() (v string) {
	return p.SkillId
}

func (p *SkillUsageRecordDTO) GetSkillVersion() (v string) {
	return p.SkillVersion
}

func (p *SkillUsageRecordDTO) GetPricingPolicyDigest() (v string) {
	return p.PricingPolicyDigest
}

func (p *SkillUsageRecordDTO) GetSkillUsageDigest() (v string) {
	return p.SkillUsageDigest
}

func (p *SkillUsageRecordDTO) GetUsageStatus() (v string) {
	return p.UsageStatus
}

func (p *SkillUsageRecordDTO) GetChargeStatus() (v string) {
	return p.ChargeStatus
}

func (p *SkillUsageRecordDTO) GetRefundStatus() (v string) {
	return p.RefundStatus
}

func (p *SkillUsageRecordDTO) GetSettlementStatus() (v string) {
	return p.SettlementStatus
}

func (p *SkillUsageRecordDTO) GetEstimatedCredits() (v int64) {
	return p.EstimatedCredits
}

var SkillUsageRecordDTO_CreditHoldId_DEFAULT string

func (p *SkillUsageRecordDTO) GetCreditHoldId() (v string) {
	if !p.IsSetCreditHoldId() {
		return SkillUsageRecordDTO_CreditHoldId_DEFAULT
	}
	return *p.CreditHoldId
}
func (p *SkillUsageRecordDTO) SetUsageId(val string) {
	p.UsageId = val
}
func (p *SkillUsageRecordDTO) SetRunId(val string) {
	p.RunId = val
}
func (p *SkillUsageRecordDTO) SetListingId(val string) {
	p.ListingId = val
}
func (p *SkillUsageRecordDTO) SetSkillId(val string) {
	p.SkillId = val
}
func (p *SkillUsageRecordDTO) SetSkillVersion(val string) {
	p.SkillVersion = val
}
func (p *SkillUsageRecordDTO) SetPricingPolicyDigest(val string) {
	p.PricingPolicyDigest = val
}
func (p *SkillUsageRecordDTO) SetSkillUsageDigest(val string) {
	p.SkillUsageDigest = val
}
func (p *SkillUsageRecordDTO) SetUsageStatus(val string) {
	p.UsageStatus = val
}
func (p *SkillUsageRecordDTO) SetChargeStatus(val string) {
	p.ChargeStatus = val
}
func (p *SkillUsageRecordDTO) SetRefundStatus(val string) {
	p.RefundStatus = val
}
func (p *SkillUsageRecordDTO) SetSettlementStatus(val string) {
	p.SettlementStatus = val
}
func (p *SkillUsageRecordDTO) SetEstimatedCredits(val int64) {
	p.EstimatedCredits = val
}
func (p *SkillUsageRecordDTO) SetCreditHoldId(val *string) {
	p.CreditHoldId = val
}

func (p *SkillUsageRecordDTO) IsSetCreditHoldId() bool {
	return p.CreditHoldId != nil
}

func (p *SkillUsageRecordDTO) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SkillUsageRecordDTO(%+v)", *p)
}

var fieldIDToName_SkillUsageRecordDTO = map[int16]string{
	1:  "usage_id",
	2:  "run_id",
	3:  "listing_id",
	4:  "skill_id",
	5:  "skill_version",
	6:  "pricing_policy_digest",
	7:  "skill_usage_digest",
	8:  "usage_status",
	9:  "charge_status",
	10: "refund_status",
	11: "settlement_status",
	12: "estimated_credits",
	13: "credit_hold_id",
}

type ListMarketplaceSkillsRequest struct {
	AuthContext *businessagent.AuthContext `thrift:"auth_context,1,required" frugal:"1,required,businessagent.AuthContext" json:"auth_context"`
	RequestMeta *businessagent.RequestMeta `thrift:"request_meta,2,required" frugal:"2,required,businessagent.RequestMeta" json:"request_meta"`
	Query       *string                    `thrift:"query,3,optional" frugal:"3,optional,string" json:"query,omitempty"`
	PageSize    *int32                     `thrift:"page_size,4,optional" frugal:"4,optional,i32" json:"page_size,omitempty"`
	Cursor      *string                    `thrift:"cursor,5,optional" frugal:"5,optional,string" json:"cursor,omitempty"`
}

func NewListMarketplaceSkillsRequest() *ListMarketplaceSkillsRequest {
	return &ListMarketplaceSkillsRequest{}
}

func (p *ListMarketplaceSkillsRequest) InitDefault() {
}

var ListMarketplaceSkillsRequest_AuthContext_DEFAULT *businessagent.AuthContext

func (p *ListMarketplaceSkillsRequest) GetAuthContext() (v *businessagent.AuthContext) {
	if !p.IsSetAuthContext() {
		return ListMarketplaceSkillsRequest_AuthContext_DEFAULT
	}
	return p.AuthContext
}

var ListMarketplaceSkillsRequest_RequestMeta_DEFAULT *businessagent.RequestMeta

func (p *ListMarketplaceSkillsRequest) GetRequestMeta() (v *businessagent.RequestMeta) {
	if !p.IsSetRequestMeta() {
		return ListMarketplaceSkillsRequest_RequestMeta_DEFAULT
	}
	return p.RequestMeta
}

var ListMarketplaceSkillsRequest_Query_DEFAULT string

func (p *ListMarketplaceSkillsRequest) GetQuery() (v string) {
	if !p.IsSetQuery() {
		return ListMarketplaceSkillsRequest_Query_DEFAULT
	}
	return *p.Query
}

var ListMarketplaceSkillsRequest_PageSize_DEFAULT int32

func (p *ListMarketplaceSkillsRequest) GetPageSize() (v int32) {
	if !p.IsSetPageSize() {
		return ListMarketplaceSkillsRequest_PageSize_DEFAULT
	}
	return *p.PageSize
}

var ListMarketplaceSkillsRequest_Cursor_DEFAULT string

func (p *ListMarketplaceSkillsRequest) GetCursor() (v string) {
	if !p.IsSetCursor() {
		return ListMarketplaceSkillsRequest_Cursor_DEFAULT
	}
	return *p.Cursor
}
func (p *ListMarketplaceSkillsRequest) SetAuthContext(val *businessagent.AuthContext) {
	p.AuthContext = val
}
func (p *ListMarketplaceSkillsRequest) SetRequestMeta(val *businessagent.RequestMeta) {
	p.RequestMeta = val
}
func (p *ListMarketplaceSkillsRequest) SetQuery(val *string) {
	p.Query = val
}
func (p *ListMarketplaceSkillsRequest) SetPageSize(val *int32) {
	p.PageSize = val
}
func (p *ListMarketplaceSkillsRequest) SetCursor(val *string) {
	p.Cursor = val
}

func (p *ListMarketplaceSkillsRequest) IsSetAuthContext() bool {
	return p.AuthContext != nil
}

func (p *ListMarketplaceSkillsRequest) IsSetRequestMeta() bool {
	return p.RequestMeta != nil
}

func (p *ListMarketplaceSkillsRequest) IsSetQuery() bool {
	return p.Query != nil
}

func (p *ListMarketplaceSkillsRequest) IsSetPageSize() bool {
	return p.PageSize != nil
}

func (p *ListMarketplaceSkillsRequest) IsSetCursor() bool {
	return p.Cursor != nil
}

func (p *ListMarketplaceSkillsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListMarketplaceSkillsRequest(%+v)", *p)
}

var fieldIDToName_ListMarketplaceSkillsRequest = map[int16]string{
	1: "auth_context",
	2: "request_meta",
	3: "query",
	4: "page_size",
	5: "cursor",
}

type ListMarketplaceSkillsResponse struct {
	Listings   []*MarketplaceListingDTO `thrift:"listings,1,required" frugal:"1,required,list<MarketplaceListingDTO>" json:"listings"`
	NextCursor *string                  `thrift:"next_cursor,2,optional" frugal:"2,optional,string" json:"next_cursor,omitempty"`
}

func NewListMarketplaceSkillsResponse() *ListMarketplaceSkillsResponse {
	return &ListMarketplaceSkillsResponse{}
}

func (p *ListMarketplaceSkillsResponse) InitDefault() {
}

func (p *ListMarketplaceSkillsResponse) GetListings() (v []*MarketplaceListingDTO) {
	return p.Listings
}

var ListMarketplaceSkillsResponse_NextCursor_DEFAULT string

func (p *ListMarketplaceSkillsResponse) GetNextCursor() (v string) {
	if !p.IsSetNextCursor() {
		return ListMarketplaceSkillsResponse_NextCursor_DEFAULT
	}
	return *p.NextCursor
}
func (p *ListMarketplaceSkillsResponse) SetListings(val []*MarketplaceListingDTO) {
	p.Listings = val
}
func (p *ListMarketplaceSkillsResponse) SetNextCursor(val *string) {
	p.NextCursor = val
}

func (p *ListMarketplaceSkillsResponse) IsSetNextCursor() bool {
	return p.NextCursor != nil
}

func (p *ListMarketplaceSkillsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListMarketplaceSkillsResponse(%+v)", *p)
}

var fieldIDToName_ListMarketplaceSkillsResponse = map[int16]string{
	1: "listings",
	2: "next_cursor",
}

type GetMarketplaceSkillRequest struct {
	AuthContext *businessagent.AuthContext `thrift:"auth_context,1,required" frugal:"1,required,businessagent.AuthContext" json:"auth_context"`
	RequestMeta *businessagent.RequestMeta `thrift:"request_meta,2,required" frugal:"2,required,businessagent.RequestMeta" json:"request_meta"`
	ListingId   string                     `thrift:"listing_id,3,required" frugal:"3,required,string" json:"listing_id"`
}

func NewGetMarketplaceSkillRequest() *GetMarketplaceSkillRequest {
	return &GetMarketplaceSkillRequest{}
}

func (p *GetMarketplaceSkillRequest) InitDefault() {
}

var GetMarketplaceSkillRequest_AuthContext_DEFAULT *businessagent.AuthContext

func (p *GetMarketplaceSkillRequest) GetAuthContext() (v *businessagent.AuthContext) {
	if !p.IsSetAuthContext() {
		return GetMarketplaceSkillRequest_AuthContext_DEFAULT
	}
	return p.AuthContext
}

var GetMarketplaceSkillRequest_RequestMeta_DEFAULT *businessagent.RequestMeta

func (p *GetMarketplaceSkillRequest) GetRequestMeta() (v *businessagent.RequestMeta) {
	if !p.IsSetRequestMeta() {
		return GetMarketplaceSkillRequest_RequestMeta_DEFAULT
	}
	return p.RequestMeta
}

func (p *GetMarketplaceSkillRequest) GetListingId() (v string) {
	return p.ListingId
}
func (p *GetMarketplaceSkillRequest) SetAuthContext(val *businessagent.AuthContext) {
	p.AuthContext = val
}
func (p *GetMarketplaceSkillRequest) SetRequestMeta(val *businessagent.RequestMeta) {
	p.RequestMeta = val
}
func (p *GetMarketplaceSkillRequest) SetListingId(val string) {
	p.ListingId = val
}

func (p *GetMarketplaceSkillRequest) IsSetAuthContext() bool {
	return p.AuthContext != nil
}

func (p *GetMarketplaceSkillRequest) IsSetRequestMeta() bool {
	return p.RequestMeta != nil
}

func (p *GetMarketplaceSkillRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMarketplaceSkillRequest(%+v)", *p)
}

var fieldIDToName_GetMarketplaceSkillRequest = map[int16]string{
	1: "auth_context",
	2: "request_meta",
	3: "listing_id",
}

type GetMarketplaceSkillResponse struct {
	Listing *MarketplaceListingDTO `thrift:"listing,1,required" frugal:"1,required,MarketplaceListingDTO" json:"listing"`
}

func NewGetMarketplaceSkillResponse() *GetMarketplaceSkillResponse {
	return &GetMarketplaceSkillResponse{}
}

func (p *GetMarketplaceSkillResponse) InitDefault() {
}

var GetMarketplaceSkillResponse_Listing_DEFAULT *MarketplaceListingDTO

func (p *GetMarketplaceSkillResponse) GetListing() (v *MarketplaceListingDTO) {
	if !p.IsSetListing() {
		return GetMarketplaceSkillResponse_Listing_DEFAULT
	}
	return p.Listing
}
func (p *GetMarketplaceSkillResponse) SetListing(val *MarketplaceListingDTO) {
	p.Listing = val
}

func (p *GetMarketplaceSkillResponse) IsSetListing() bool {
	return p.Listing != nil
}

func (p *GetMarketplaceSkillResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMarketplaceSkillResponse(%+v)", *p)
}

var fieldIDToName_GetMarketplaceSkillResponse = map[int16]string{
	1: "listing",
}

type InstallSkillRequest struct {
	AuthContext  *businessagent.AuthContext `thrift:"auth_context,1,required" frugal:"1,required,businessagent.AuthContext" json:"auth_context"`
	RequestMeta  *businessagent.RequestMeta `thrift:"request_meta,2,required" frugal:"2,required,businessagent.RequestMeta" json:"request_meta"`
	ListingId    string                     `thrift:"listing_id,3,required" frugal:"3,required,string" json:"listing_id"`
	TargetScope  InstallationScope          `thrift:"target_scope,4,required" frugal:"4,required,InstallationScope" json:"target_scope"`
	EnterpriseId *string                    `thrift:"enterprise_id,5,optional" frugal:"5,optional,string" json:"enterprise_id,omitempty"`
}

func NewInstallSkillRequest() *InstallSkillRequest {
	return &InstallSkillRequest{}
}

func (p *InstallSkillRequest) InitDefault() {
}

var InstallSkillRequest_AuthContext_DEFAULT *businessagent.AuthContext

func (p *InstallSkillRequest) GetAuthContext() (v *businessagent.AuthContext) {
	if !p.IsSetAuthContext() {
		return InstallSkillRequest_AuthContext_DEFAULT
	}
	return p.AuthContext
}

var InstallSkillRequest_RequestMeta_DEFAULT *businessagent.RequestMeta

func (p *InstallSkillRequest) GetRequestMeta() (v *businessagent.RequestMeta) {
	if !p.IsSetRequestMeta() {
		return InstallSkillRequest_RequestMeta_DEFAULT
	}
	return p.RequestMeta
}

func (p *InstallSkillRequest) GetListingId() (v string) {
	return p.ListingId
}

func (p *InstallSkillRequest) GetTargetScope() (v InstallationScope) {
	return p.TargetScope
}

var InstallSkillRequest_EnterpriseId_DEFAULT string

func (p *InstallSkillRequest) GetEnterpriseId() (v string) {
	if !p.IsSetEnterpriseId() {
		return InstallSkillRequest_EnterpriseId_DEFAULT
	}
	return *p.EnterpriseId
}
func (p *InstallSkillRequest) SetAuthContext(val *businessagent.AuthContext) {
	p.AuthContext = val
}
func (p *InstallSkillRequest) SetRequestMeta(val *businessagent.RequestMeta) {
	p.RequestMeta = val
}
func (p *InstallSkillRequest) SetListingId(val string) {
	p.ListingId = val
}
func (p *InstallSkillRequest) SetTargetScope(val InstallationScope) {
	p.TargetScope = val
}
func (p *InstallSkillRequest) SetEnterpriseId(val *string) {
	p.EnterpriseId = val
}

func (p *InstallSkillRequest) IsSetAuthContext() bool {
	return p.AuthContext != nil
}

func (p *InstallSkillRequest) IsSetRequestMeta() bool {
	return p.RequestMeta != nil
}

func (p *InstallSkillRequest) IsSetEnterpriseId() bool {
	return p.EnterpriseId != nil
}

func (p *InstallSkillRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InstallSkillRequest(%+v)", *p)
}

var fieldIDToName_InstallSkillRequest = map[int16]string{
	1: "auth_context",
	2: "request_meta",
	3: "listing_id",
	4: "target_scope",
	5: "enterprise_id",
}

type InstallSkillResponse struct {
	Installation     *SkillInstallationDTO `thrift:"installation,1,required" frugal:"1,required,SkillInstallationDTO" json:"installation"`
	IdempotentReplay bool                  `thrift:"idempotent_replay,2,required" frugal:"2,required,bool" json:"idempotent_replay"`
}

func NewInstallSkillResponse() *InstallSkillResponse {
	return &InstallSkillResponse{}
}

func (p *InstallSkillResponse) InitDefault() {
}

var InstallSkillResponse_Installation_DEFAULT *SkillInstallationDTO

func (p *InstallSkillResponse) GetInstallation() (v *SkillInstallationDTO) {
	if !p.IsSetInstallation() {
		return InstallSkillResponse_Installation_DEFAULT
	}
	return p.Installation
}

func (p *InstallSkillResponse) GetIdempotentReplay() (v bool) {
	return p.IdempotentReplay
}
func (p *InstallSkillResponse) SetInstallation(val *SkillInstallationDTO) {
	p.Installation = val
}
func (p *InstallSkillResponse) SetIdempotentReplay(val bool) {
	p.IdempotentReplay = val
}

func (p *InstallSkillResponse) IsSetInstallation() bool {
	return p.Installation != nil
}

func (p *InstallSkillResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InstallSkillResponse(%+v)", *p)
}

var fieldIDToName_InstallSkillResponse = map[int16]string{
	1: "installation",
	2: "idempotent_replay",
}

type UpgradeSkillInstallationRequest struct {
	AuthContext    *businessagent.AuthContext `thrift:"auth_context,1,required" frugal:"1,required,businessagent.AuthContext" json:"auth_context"`
	RequestMeta    *businessagent.RequestMeta `thrift:"request_meta,2,required" frugal:"2,required,businessagent.RequestMeta" json:"request_meta"`
	InstallationId string                     `thrift:"installation_id,3,required" frugal:"3,required,string" json:"installation_id"`
	TargetVersion  string                     `thrift:"target_version,4,required" frugal:"4,required,string" json:"target_version"`
	Confirmed      bool                       `thrift:"confirmed,5,required" frugal:"5,required,bool" json:"confirmed"`
}

func NewUpgradeSkillInstallationRequest() *UpgradeSkillInstallationRequest {
	return &UpgradeSkillInstallationRequest{}
}

func (p *UpgradeSkillInstallationRequest) InitDefault() {
}

var UpgradeSkillInstallationRequest_AuthContext_DEFAULT *businessagent.AuthContext

func (p *UpgradeSkillInstallationRequest) GetAuthContext() (v *businessagent.AuthContext) {
	if !p.IsSetAuthContext() {
		return UpgradeSkillInstallationRequest_AuthContext_DEFAULT
	}
	return p.AuthContext
}

var UpgradeSkillInstallationRequest_RequestMeta_DEFAULT *businessagent.RequestMeta

func (p *UpgradeSkillInstallationRequest) GetRequestMeta() (v *businessagent.RequestMeta) {
	if !p.IsSetRequestMeta() {
		return UpgradeSkillInstallationRequest_RequestMeta_DEFAULT
	}
	return p.RequestMeta
}

func (p *UpgradeSkillInstallationRequest) GetInstallationId() (v string) {
	return p.InstallationId
}

func (p *UpgradeSkillInstallationRequest) GetTargetVersion() (v string) {
	return p.TargetVersion
}

func (p *UpgradeSkillInstallationRequest) GetConfirmed() (v bool) {
	return p.Confirmed
}
func (p *UpgradeSkillInstallationRequest) SetAuthContext(val *businessagent.AuthContext) {
	p.AuthContext = val
}
func (p *UpgradeSkillInstallationRequest) SetRequestMeta(val *businessagent.RequestMeta) {
	p.RequestMeta = val
}
func (p *UpgradeSkillInstallationRequest) SetInstallationId(val string) {
	p.InstallationId = val
}
func (p *UpgradeSkillInstallationRequest) SetTargetVersion(val string) {
	p.TargetVersion = val
}
func (p *UpgradeSkillInstallationRequest) SetConfirmed(val bool) {
	p.Confirmed = val
}

func (p *UpgradeSkillInstallationRequest) IsSetAuthContext() bool {
	return p.AuthContext != nil
}

func (p *UpgradeSkillInstallationRequest) IsSetRequestMeta() bool {
	return p.RequestMeta != nil
}

func (p *UpgradeSkillInstallationRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpgradeSkillInstallationRequest(%+v)", *p)
}

var fieldIDToName_UpgradeSkillInstallationRequest = map[int16]string{
	1: "auth_context",
	2: "request_meta",
	3: "installation_id",
	4: "target_version",
	5: "confirmed",
}

type UpgradeSkillInstallationResponse struct {
	Installation *SkillInstallationDTO `thrift:"installation,1,required" frugal:"1,required,SkillInstallationDTO" json:"installation"`
}

func NewUpgradeSkillInstallationResponse() *UpgradeSkillInstallationResponse {
	return &UpgradeSkillInstallationResponse{}
}

func (p *UpgradeSkillInstallationResponse) InitDefault() {
}

var UpgradeSkillInstallationResponse_Installation_DEFAULT *SkillInstallationDTO

func (p *UpgradeSkillInstallationResponse) GetInstallation() (v *SkillInstallationDTO) {
	if !p.IsSetInstallation() {
		return UpgradeSkillInstallationResponse_Installation_DEFAULT
	}
	return p.Installation
}
func (p *UpgradeSkillInstallationResponse) SetInstallation(val *SkillInstallationDTO) {
	p.Installation = val
}

func (p *UpgradeSkillInstallationResponse) IsSetInstallation() bool {
	return p.Installation != nil
}

func (p *UpgradeSkillInstallationResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpgradeSkillInstallationResponse(%+v)", *p)
}

var fieldIDToName_UpgradeSkillInstallationResponse = map[int16]string{
	1: "installation",
}

type EstimateSkillUsageCreditsRequest struct {
	AuthContext         *businessagent.AuthContext `thrift:"auth_context,1,required" frugal:"1,required,businessagent.AuthContext" json:"auth_context"`
	RequestMeta         *businessagent.RequestMeta `thrift:"request_meta,2,required" frugal:"2,required,businessagent.RequestMeta" json:"request_meta"`
	RunId               string                     `thrift:"run_id,3,required" frugal:"3,required,string" json:"run_id"`
	ListingId           string                     `thrift:"listing_id,4,required" frugal:"4,required,string" json:"listing_id"`
	PricingPolicyDigest string                     `thrift:"pricing_policy_digest,5,required" frugal:"5,required,string" json:"pricing_policy_digest"`
}

func NewEstimateSkillUsageCreditsRequest() *EstimateSkillUsageCreditsRequest {
	return &EstimateSkillUsageCreditsRequest{}
}

func (p *EstimateSkillUsageCreditsRequest) InitDefault() {
}

var EstimateSkillUsageCreditsRequest_AuthContext_DEFAULT *businessagent.AuthContext

func (p *EstimateSkillUsageCreditsRequest) GetAuthContext() (v *businessagent.AuthContext) {
	if !p.IsSetAuthContext() {
		return EstimateSkillUsageCreditsRequest_AuthContext_DEFAULT
	}
	return p.AuthContext
}

var EstimateSkillUsageCreditsRequest_RequestMeta_DEFAULT *businessagent.RequestMeta

func (p *EstimateSkillUsageCreditsRequest) GetRequestMeta() (v *businessagent.RequestMeta) {
	if !p.IsSetRequestMeta() {
		return EstimateSkillUsageCreditsRequest_RequestMeta_DEFAULT
	}
	return p.RequestMeta
}

func (p *EstimateSkillUsageCreditsRequest) GetRunId() (v string) {
	return p.RunId
}

func (p *EstimateSkillUsageCreditsRequest) GetListingId() (v string) {
	return p.ListingId
}

func (p *EstimateSkillUsageCreditsRequest) GetPricingPolicyDigest() (v string) {
	return p.PricingPolicyDigest
}
func (p *EstimateSkillUsageCreditsRequest) SetAuthContext(val *businessagent.AuthContext) {
	p.AuthContext = val
}
func (p *EstimateSkillUsageCreditsRequest) SetRequestMeta(val *businessagent.RequestMeta) {
	p.RequestMeta = val
}
func (p *EstimateSkillUsageCreditsRequest) SetRunId(val string) {
	p.RunId = val
}
func (p *EstimateSkillUsageCreditsRequest) SetListingId(val string) {
	p.ListingId = val
}
func (p *EstimateSkillUsageCreditsRequest) SetPricingPolicyDigest(val string) {
	p.PricingPolicyDigest = val
}

func (p *EstimateSkillUsageCreditsRequest) IsSetAuthContext() bool {
	return p.AuthContext != nil
}

func (p *EstimateSkillUsageCreditsRequest) IsSetRequestMeta() bool {
	return p.RequestMeta != nil
}

func (p *EstimateSkillUsageCreditsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EstimateSkillUsageCreditsRequest(%+v)", *p)
}

var fieldIDToName_EstimateSkillUsageCreditsRequest = map[int16]string{
	1: "auth_context",
	2: "request_meta",
	3: "run_id",
	4: "listing_id",
	5: "pricing_policy_digest",
}

type EstimateSkillUsageCreditsResponse struct {
	EstimatedCredits    int64  `thrift:"estimated_credits,1,required" frugal:"1,required,i64" json:"estimated_credits"`
	PricingPolicyDigest string `thrift:"pricing_policy_digest,2,required" frugal:"2,required,string" json:"pricing_policy_digest"`
	SkillUsageDigest    string `thrift:"skill_usage_digest,3,required" frugal:"3,required,string" json:"skill_usage_digest"`
	ExpiresAt           string `thrift:"expires_at,4,required" frugal:"4,required,string" json:"expires_at"`
}

func NewEstimateSkillUsageCreditsResponse() *EstimateSkillUsageCreditsResponse {
	return &EstimateSkillUsageCreditsResponse{}
}

func (p *EstimateSkillUsageCreditsResponse) InitDefault() {
}

func (p *EstimateSkillUsageCreditsResponse) GetEstimatedCredits() (v int64) {
	return p.EstimatedCredits
}

func (p *EstimateSkillUsageCreditsResponse) GetPricingPolicyDigest() (v string) {
	return p.PricingPolicyDigest
}

func (p *EstimateSkillUsageCreditsResponse) GetSkillUsageDigest() (v string) {
	return p.SkillUsageDigest
}

func (p *EstimateSkillUsageCreditsResponse) GetExpiresAt() (v string) {
	return p.ExpiresAt
}
func (p *EstimateSkillUsageCreditsResponse) SetEstimatedCredits(val int64) {
	p.EstimatedCredits = val
}
func (p *EstimateSkillUsageCreditsResponse) SetPricingPolicyDigest(val string) {
	p.PricingPolicyDigest = val
}
func (p *EstimateSkillUsageCreditsResponse) SetSkillUsageDigest(val string) {
	p.SkillUsageDigest = val
}
func (p *EstimateSkillUsageCreditsResponse) SetExpiresAt(val string) {
	p.ExpiresAt = val
}

func (p *EstimateSkillUsageCreditsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EstimateSkillUsageCreditsResponse(%+v)", *p)
}

var fieldIDToName_EstimateSkillUsageCreditsResponse = map[int16]string{
	1: "estimated_credits",
	2: "pricing_policy_digest",
	3: "skill_usage_digest",
	4: "expires_at",
}

type CreateSkillUsageRecordRequest struct {
	AuthContext         *businessagent.AuthContext `thrift:"auth_context,1,required" frugal:"1,required,businessagent.AuthContext" json:"auth_context"`
	RequestMeta         *businessagent.RequestMeta `thrift:"request_meta,2,required" frugal:"2,required,businessagent.RequestMeta" json:"request_meta"`
	RunId               string                     `thrift:"run_id,3,required" frugal:"3,required,string" json:"run_id"`
	ListingId           string                     `thrift:"listing_id,4,required" frugal:"4,required,string" json:"listing_id"`
	SkillId             string                     `thrift:"skill_id,5,required" frugal:"5,required,string" json:"skill_id"`
	SkillVersion        string                     `thrift:"skill_version,6,required" frugal:"6,required,string" json:"skill_version"`
	PricingPolicyDigest string                     `thrift:"pricing_policy_digest,7,required" frugal:"7,required,string" json:"pricing_policy_digest"`
	SkillUsageDigest    string                     `thrift:"skill_usage_digest,8,required" frugal:"8,required,string" json:"skill_usage_digest"`
	EstimatedCredits    int64                      `thrift:"estimated_credits,9,required" frugal:"9,required,i64" json:"estimated_credits"`
}

func NewCreateSkillUsageRecordRequest() *CreateSkillUsageRecordRequest {
	return &CreateSkillUsageRecordRequest{}
}

func (p *CreateSkillUsageRecordRequest) InitDefault() {
}

var CreateSkillUsageRecordRequest_AuthContext_DEFAULT *businessagent.AuthContext

func (p *CreateSkillUsageRecordRequest) GetAuthContext() (v *businessagent.AuthContext) {
	if !p.IsSetAuthContext() {
		return CreateSkillUsageRecordRequest_AuthContext_DEFAULT
	}
	return p.AuthContext
}

var CreateSkillUsageRecordRequest_RequestMeta_DEFAULT *businessagent.RequestMeta

func (p *CreateSkillUsageRecordRequest) GetRequestMeta() (v *businessagent.RequestMeta) {
	if !p.IsSetRequestMeta() {
		return CreateSkillUsageRecordRequest_RequestMeta_DEFAULT
	}
	return p.RequestMeta
}

func (p *CreateSkillUsageRecordRequest) GetRunId() (v string) {
	return p.RunId
}

func (p *CreateSkillUsageRecordRequest) GetListingId() (v string) {
	return p.ListingId
}

func (p *CreateSkillUsageRecordRequest) GetSkillId() (v string) {
	return p.SkillId
}

func (p *CreateSkillUsageRecordRequest) GetSkillVersion() (v string) {
	return p.SkillVersion
}

func (p *CreateSkillUsageRecordRequest) GetPricingPolicyDigest() (v string) {
	return p.PricingPolicyDigest
}

func (p *CreateSkillUsageRecordRequest) GetSkillUsageDigest() (v string) {
	return p.SkillUsageDigest
}

func (p *CreateSkillUsageRecordRequest) GetEstimatedCredits() (v int64) {
	return p.EstimatedCredits
}
func (p *CreateSkillUsageRecordRequest) SetAuthContext(val *businessagent.AuthContext) {
	p.AuthContext = val
}
func (p *CreateSkillUsageRecordRequest) SetRequestMeta(val *businessagent.RequestMeta) {
	p.RequestMeta = val
}
func (p *CreateSkillUsageRecordRequest) SetRunId(val string) {
	p.RunId = val
}
func (p *CreateSkillUsageRecordRequest) SetListingId(val string) {
	p.ListingId = val
}
func (p *CreateSkillUsageRecordRequest) SetSkillId(val string) {
	p.SkillId = val
}
func (p *CreateSkillUsageRecordRequest) SetSkillVersion(val string) {
	p.SkillVersion = val
}
func (p *CreateSkillUsageRecordRequest) SetPricingPolicyDigest(val string) {
	p.PricingPolicyDigest = val
}
func (p *CreateSkillUsageRecordRequest) SetSkillUsageDigest(val string) {
	p.SkillUsageDigest = val
}
func (p *CreateSkillUsageRecordRequest) SetEstimatedCredits(val int64) {
	p.EstimatedCredits = val
}

func (p *CreateSkillUsageRecordRequest) IsSetAuthContext() bool {
	return p.AuthContext != nil
}

func (p *CreateSkillUsageRecordRequest) IsSetRequestMeta() bool {
	return p.RequestMeta != nil
}

func (p *CreateSkillUsageRecordRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateSkillUsageRecordRequest(%+v)", *p)
}

var fieldIDToName_CreateSkillUsageRecordRequest = map[int16]string{
	1: "auth_context",
	2: "request_meta",
	3: "run_id",
	4: "listing_id",
	5: "skill_id",
	6: "skill_version",
	7: "pricing_policy_digest",
	8: "skill_usage_digest",
	9: "estimated_credits",
}

type CreateSkillUsageRecordResponse struct {
	Usage            *SkillUsageRecordDTO `thrift:"usage,1,required" frugal:"1,required,SkillUsageRecordDTO" json:"usage"`
	IdempotentReplay bool                 `thrift:"idempotent_replay,2,required" frugal:"2,required,bool" json:"idempotent_replay"`
}

func NewCreateSkillUsageRecordResponse() *CreateSkillUsageRecordResponse {
	return &CreateSkillUsageRecordResponse{}
}

func (p *CreateSkillUsageRecordResponse) InitDefault() {
}

var CreateSkillUsageRecordResponse_Usage_DEFAULT *SkillUsageRecordDTO

func (p *CreateSkillUsageRecordResponse) GetUsage() (v *SkillUsageRecordDTO) {
	if !p.IsSetUsage() {
		return CreateSkillUsageRecordResponse_Usage_DEFAULT
	}
	return p.Usage
}

func (p *CreateSkillUsageRecordResponse) GetIdempotentReplay() (v bool) {
	return p.IdempotentReplay
}
func (p *CreateSkillUsageRecordResponse) SetUsage(val *SkillUsageRecordDTO) {
	p.Usage = val
}
func (p *CreateSkillUsageRecordResponse) SetIdempotentReplay(val bool) {
	p.IdempotentReplay = val
}

func (p *CreateSkillUsageRecordResponse) IsSetUsage() bool {
	return p.Usage != nil
}

func (p *CreateSkillUsageRecordResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateSkillUsageRecordResponse(%+v)", *p)
}

var fieldIDToName_CreateSkillUsageRecordResponse = map[int16]string{
	1: "usage",
	2: "idempotent_replay",
}

type FreezeSkillUsageCreditsRequest struct {
	AuthContext      *businessagent.AuthContext `thrift:"auth_context,1,required" frugal:"1,required,businessagent.AuthContext" json:"auth_context"`
	RequestMeta      *businessagent.RequestMeta `thrift:"request_meta,2,required" frugal:"2,required,businessagent.RequestMeta" json:"request_meta"`
	UsageId          string                     `thrift:"usage_id,3,required" frugal:"3,required,string" json:"usage_id"`
	SkillUsageDigest string                     `thrift:"skill_usage_digest,4,required" frugal:"4,required,string" json:"skill_usage_digest"`
}

func NewFreezeSkillUsageCreditsRequest() *FreezeSkillUsageCreditsRequest {
	return &FreezeSkillUsageCreditsRequest{}
}

func (p *FreezeSkillUsageCreditsRequest) InitDefault() {
}

var FreezeSkillUsageCreditsRequest_AuthContext_DEFAULT *businessagent.AuthContext

func (p *FreezeSkillUsageCreditsRequest) GetAuthContext() (v *businessagent.AuthContext) {
	if !p.IsSetAuthContext() {
		return FreezeSkillUsageCreditsRequest_AuthContext_DEFAULT
	}
	return p.AuthContext
}

var FreezeSkillUsageCreditsRequest_RequestMeta_DEFAULT *businessagent.RequestMeta

func (p *FreezeSkillUsageCreditsRequest) GetRequestMeta() (v *businessagent.RequestMeta) {
	if !p.IsSetRequestMeta() {
		return FreezeSkillUsageCreditsRequest_RequestMeta_DEFAULT
	}
	return p.RequestMeta
}

func (p *FreezeSkillUsageCreditsRequest) GetUsageId() (v string) {
	return p.UsageId
}

func (p *FreezeSkillUsageCreditsRequest) GetSkillUsageDigest() (v string) {
	return p.SkillUsageDigest
}
func (p *FreezeSkillUsageCreditsRequest) SetAuthContext(val *businessagent.AuthContext) {
	p.AuthContext = val
}
func (p *FreezeSkillUsageCreditsRequest) SetRequestMeta(val *businessagent.RequestMeta) {
	p.RequestMeta = val
}
func (p *FreezeSkillUsageCreditsRequest) SetUsageId(val string) {
	p.UsageId = val
}
func (p *FreezeSkillUsageCreditsRequest) SetSkillUsageDigest(val string) {
	p.SkillUsageDigest = val
}

func (p *FreezeSkillUsageCreditsRequest) IsSetAuthContext() bool {
	return p.AuthContext != nil
}

func (p *FreezeSkillUsageCreditsRequest) IsSetRequestMeta() bool {
	return p.RequestMeta != nil
}

func (p *FreezeSkillUsageCreditsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FreezeSkillUsageCreditsRequest(%+v)", *p)
}

var fieldIDToName_FreezeSkillUsageCreditsRequest = map[int16]string{
	1: "auth_context",
	2: "request_meta",
	3: "usage_id",
	4: "skill_usage_digest",
}

type FreezeSkillUsageCreditsResponse struct {
	Usage *SkillUsageRecordDTO `thrift:"usage,1,required" frugal:"1,required,SkillUsageRecordDTO" json:"usage"`
}

func NewFreezeSkillUsageCreditsResponse() *FreezeSkillUsageCreditsResponse {
	return &FreezeSkillUsageCreditsResponse{}
}

func (p *FreezeSkillUsageCreditsResponse) InitDefault() {
}

var FreezeSkillUsageCreditsResponse_Usage_DEFAULT *SkillUsageRecordDTO

func (p *FreezeSkillUsageCreditsResponse) GetUsage() (v *SkillUsageRecordDTO) {
	if !p.IsSetUsage() {
		return FreezeSkillUsageCreditsResponse_Usage_DEFAULT
	}
	return p.Usage
}
func (p *FreezeSkillUsageCreditsResponse) SetUsage(val *SkillUsageRecordDTO) {
	p.Usage = val
}

func (p *FreezeSkillUsageCreditsResponse) IsSetUsage() bool {
	return p.Usage != nil
}

func (p *FreezeSkillUsageCreditsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FreezeSkillUsageCreditsResponse(%+v)", *p)
}

var fieldIDToName_FreezeSkillUsageCreditsResponse = map[int16]string{
	1: "usage",
}

type CommitSkillUsageAndSettleRequest struct {
	AuthContext          *businessagent.AuthContext `thrift:"auth_context,1,required" frugal:"1,required,businessagent.AuthContext" json:"auth_context"`
	RequestMeta          *businessagent.RequestMeta `thrift:"request_meta,2,required" frugal:"2,required,businessagent.RequestMeta" json:"request_meta"`
	UsageId              string                     `thrift:"usage_id,3,required" frugal:"3,required,string" json:"usage_id"`
	ValueDeliveredDigest string                     `thrift:"value_delivered_digest,4,required" frugal:"4,required,string" json:"value_delivered_digest"`
}

func NewCommitSkillUsageAndSettleRequest() *CommitSkillUsageAndSettleRequest {
	return &CommitSkillUsageAndSettleRequest{}
}

func (p *CommitSkillUsageAndSettleRequest) InitDefault() {
}

var CommitSkillUsageAndSettleRequest_AuthContext_DEFAULT *businessagent.AuthContext

func (p *CommitSkillUsageAndSettleRequest) GetAuthContext() (v *businessagent.AuthContext) {
	if !p.IsSetAuthContext() {
		return CommitSkillUsageAndSettleRequest_AuthContext_DEFAULT
	}
	return p.AuthContext
}

var CommitSkillUsageAndSettleRequest_RequestMeta_DEFAULT *businessagent.RequestMeta

func (p *CommitSkillUsageAndSettleRequest) GetRequestMeta() (v *businessagent.RequestMeta) {
	if !p.IsSetRequestMeta() {
		return CommitSkillUsageAndSettleRequest_RequestMeta_DEFAULT
	}
	return p.RequestMeta
}

func (p *CommitSkillUsageAndSettleRequest) GetUsageId() (v string) {
	return p.UsageId
}

func (p *CommitSkillUsageAndSettleRequest) GetValueDeliveredDigest() (v string) {
	return p.ValueDeliveredDigest
}
func (p *CommitSkillUsageAndSettleRequest) SetAuthContext(val *businessagent.AuthContext) {
	p.AuthContext = val
}
func (p *CommitSkillUsageAndSettleRequest) SetRequestMeta(val *businessagent.RequestMeta) {
	p.RequestMeta = val
}
func (p *CommitSkillUsageAndSettleRequest) SetUsageId(val string) {
	p.UsageId = val
}
func (p *CommitSkillUsageAndSettleRequest) SetValueDeliveredDigest(val string) {
	p.ValueDeliveredDigest = val
}

func (p *CommitSkillUsageAndSettleRequest) IsSetAuthContext() bool {
	return p.AuthContext != nil
}

func (p *CommitSkillUsageAndSettleRequest) IsSetRequestMeta() bool {
	return p.RequestMeta != nil
}

func (p *CommitSkillUsageAndSettleRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommitSkillUsageAndSettleRequest(%+v)", *p)
}

var fieldIDToName_CommitSkillUsageAndSettleRequest = map[int16]string{
	1: "auth_context",
	2: "request_meta",
	3: "usage_id",
	4: "value_delivered_digest",
}

type CommitSkillUsageAndSettleResponse struct {
	Usage        *SkillUsageRecordDTO `thrift:"usage,1,required" frugal:"1,required,SkillUsageRecordDTO" json:"usage"`
	SettlementId string               `thrift:"settlement_id,2,required" frugal:"2,required,string" json:"settlement_id"`
}

func NewCommitSkillUsageAndSettleResponse() *CommitSkillUsageAndSettleResponse {
	return &CommitSkillUsageAndSettleResponse{}
}

func (p *CommitSkillUsageAndSettleResponse) InitDefault() {
}

var CommitSkillUsageAndSettleResponse_Usage_DEFAULT *SkillUsageRecordDTO

func (p *CommitSkillUsageAndSettleResponse) GetUsage() (v *SkillUsageRecordDTO) {
	if !p.IsSetUsage() {
		return CommitSkillUsageAndSettleResponse_Usage_DEFAULT
	}
	return p.Usage
}

func (p *CommitSkillUsageAndSettleResponse) GetSettlementId() (v string) {
	return p.SettlementId
}
func (p *CommitSkillUsageAndSettleResponse) SetUsage(val *SkillUsageRecordDTO) {
	p.Usage = val
}
func (p *CommitSkillUsageAndSettleResponse) SetSettlementId(val string) {
	p.SettlementId = val
}

func (p *CommitSkillUsageAndSettleResponse) IsSetUsage() bool {
	return p.Usage != nil
}

func (p *CommitSkillUsageAndSettleResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommitSkillUsageAndSettleResponse(%+v)", *p)
}

var fieldIDToName_CommitSkillUsageAndSettleResponse = map[int16]string{
	1: "usage",
	2: "settlement_id",
}

type ReleaseSkillUsageFreezeRequest struct {
	AuthContext   *businessagent.AuthContext `thrift:"auth_context,1,required" frugal:"1,required,businessagent.AuthContext" json:"auth_context"`
	RequestMeta   *businessagent.RequestMeta `thrift:"request_meta,2,required" frugal:"2,required,businessagent.RequestMeta" json:"request_meta"`
	UsageId       string                     `thrift:"usage_id,3,required" frugal:"3,required,string" json:"usage_id"`
	ReleaseReason string                     `thrift:"release_reason,4,required" frugal:"4,required,string" json:"release_reason"`
}

func NewReleaseSkillUsageFreezeRequest() *ReleaseSkillUsageFreezeRequest {
	return &ReleaseSkillUsageFreezeRequest{}
}

func (p *ReleaseSkillUsageFreezeRequest) InitDefault() {
}

var ReleaseSkillUsageFreezeRequest_AuthContext_DEFAULT *businessagent.AuthContext

func (p *ReleaseSkillUsageFreezeRequest) GetAuthContext() (v *businessagent.AuthContext) {
	if !p.IsSetAuthContext() {
		return ReleaseSkillUsageFreezeRequest_AuthContext_DEFAULT
	}
	return p.AuthContext
}

var ReleaseSkillUsageFreezeRequest_RequestMeta_DEFAULT *businessagent.RequestMeta

func (p *ReleaseSkillUsageFreezeRequest) GetRequestMeta() (v *businessagent.RequestMeta) {
	if !p.IsSetRequestMeta() {
		return ReleaseSkillUsageFreezeRequest_RequestMeta_DEFAULT
	}
	return p.RequestMeta
}

func (p *ReleaseSkillUsageFreezeRequest) GetUsageId() (v string) {
	return p.UsageId
}

func (p *ReleaseSkillUsageFreezeRequest) GetReleaseReason() (v string) {
	return p.ReleaseReason
}
func (p *ReleaseSkillUsageFreezeRequest) SetAuthContext(val *businessagent.AuthContext) {
	p.AuthContext = val
}
func (p *ReleaseSkillUsageFreezeRequest) SetRequestMeta(val *businessagent.RequestMeta) {
	p.RequestMeta = val
}
func (p *ReleaseSkillUsageFreezeRequest) SetUsageId(val string) {
	p.UsageId = val
}
func (p *ReleaseSkillUsageFreezeRequest) SetReleaseReason(val string) {
	p.ReleaseReason = val
}

func (p *ReleaseSkillUsageFreezeRequest) IsSetAuthContext() bool {
	return p.AuthContext != nil
}

func (p *ReleaseSkillUsageFreezeRequest) IsSetRequestMeta() bool {
	return p.RequestMeta != nil
}

func (p *ReleaseSkillUsageFreezeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReleaseSkillUsageFreezeRequest(%+v)", *p)
}

var fieldIDToName_ReleaseSkillUsageFreezeRequest = map[int16]string{
	1: "auth_context",
	2: "request_meta",
	3: "usage_id",
	4: "release_reason",
}

type ReleaseSkillUsageFreezeResponse struct {
	Usage *SkillUsageRecordDTO `thrift:"usage,1,required" frugal:"1,required,SkillUsageRecordDTO" json:"usage"`
}

func NewReleaseSkillUsageFreezeResponse() *ReleaseSkillUsageFreezeResponse {
	return &ReleaseSkillUsageFreezeResponse{}
}

func (p *ReleaseSkillUsageFreezeResponse) InitDefault() {
}

var ReleaseSkillUsageFreezeResponse_Usage_DEFAULT *SkillUsageRecordDTO

func (p *ReleaseSkillUsageFreezeResponse) GetUsage() (v *SkillUsageRecordDTO) {
	if !p.IsSetUsage() {
		return ReleaseSkillUsageFreezeResponse_Usage_DEFAULT
	}
	return p.Usage
}
func (p *ReleaseSkillUsageFreezeResponse) SetUsage(val *SkillUsageRecordDTO) {
	p.Usage = val
}

func (p *ReleaseSkillUsageFreezeResponse) IsSetUsage() bool {
	return p.Usage != nil
}

func (p *ReleaseSkillUsageFreezeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReleaseSkillUsageFreezeResponse(%+v)", *p)
}

var fieldIDToName_ReleaseSkillUsageFreezeResponse = map[int16]string{
	1: "usage",
}

type BusinessSkillMarketplaceService interface {
	ListMarketplaceSkills(ctx context.Context, request *ListMarketplaceSkillsRequest) (r *ListMarketplaceSkillsResponse, err error)

	GetMarketplaceSkill(ctx context.Context, request *GetMarketplaceSkillRequest) (r *GetMarketplaceSkillResponse, err error)

	InstallSkill(ctx context.Context, request *InstallSkillRequest) (r *InstallSkillResponse, err error)

	UpgradeSkillInstallation(ctx context.Context, request *UpgradeSkillInstallationRequest) (r *UpgradeSkillInstallationResponse, err error)

	EstimateSkillUsageCredits(ctx context.Context, request *EstimateSkillUsageCreditsRequest) (r *EstimateSkillUsageCreditsResponse, err error)

	CreateSkillUsageRecord(ctx context.Context, request *CreateSkillUsageRecordRequest) (r *CreateSkillUsageRecordResponse, err error)

	FreezeSkillUsageCredits(ctx context.Context, request *FreezeSkillUsageCreditsRequest) (r *FreezeSkillUsageCreditsResponse, err error)

	CommitSkillUsageAndSettle(ctx context.Context, request *CommitSkillUsageAndSettleRequest) (r *CommitSkillUsageAndSettleResponse, err error)

	ReleaseSkillUsageFreeze(ctx context.Context, request *ReleaseSkillUsageFreezeRequest) (r *ReleaseSkillUsageFreezeResponse, err error)
}

type BusinessSkillMarketplaceServiceListMarketplaceSkillsArgs struct {
	Request *ListMarketplaceSkillsRequest `thrift:"request,1" frugal:"1,default,ListMarketplaceSkillsRequest" json:"request"`
}

func NewBusinessSkillMarketplaceServiceListMarketplaceSkillsArgs() *BusinessSkillMarketplaceServiceListMarketplaceSkillsArgs {
	return &BusinessSkillMarketplaceServiceListMarketplaceSkillsArgs{}
}

func (p *BusinessSkillMarketplaceServiceListMarketplaceSkillsArgs) InitDefault() {
}

var BusinessSkillMarketplaceServiceListMarketplaceSkillsArgs_Request_DEFAULT *ListMarketplaceSkillsRequest

func (p *BusinessSkillMarketplaceServiceListMarketplaceSkillsArgs) GetRequest() (v *ListMarketplaceSkillsRequest) {
	if !p.IsSetRequest() {
		return BusinessSkillMarketplaceServiceListMarketplaceSkillsArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *BusinessSkillMarketplaceServiceListMarketplaceSkillsArgs) SetRequest(val *ListMarketplaceSkillsRequest) {
	p.Request = val
}

func (p *BusinessSkillMarketplaceServiceListMarketplaceSkillsArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *BusinessSkillMarketplaceServiceListMarketplaceSkillsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessSkillMarketplaceServiceListMarketplaceSkillsArgs(%+v)", *p)
}

var fieldIDToName_BusinessSkillMarketplaceServiceListMarketplaceSkillsArgs = map[int16]string{
	1: "request",
}

type BusinessSkillMarketplaceServiceListMarketplaceSkillsResult struct {
	Success *ListMarketplaceSkillsResponse `thrift:"success,0,optional" frugal:"0,optional,ListMarketplaceSkillsResponse" json:"success,omitempty"`
}

func NewBusinessSkillMarketplaceServiceListMarketplaceSkillsResult() *BusinessSkillMarketplaceServiceListMarketplaceSkillsResult {
	return &BusinessSkillMarketplaceServiceListMarketplaceSkillsResult{}
}

func (p *BusinessSkillMarketplaceServiceListMarketplaceSkillsResult) InitDefault() {
}

var BusinessSkillMarketplaceServiceListMarketplaceSkillsResult_Success_DEFAULT *ListMarketplaceSkillsResponse

func (p *BusinessSkillMarketplaceServiceListMarketplaceSkillsResult) GetSuccess() (v *ListMarketplaceSkillsResponse) {
	if !p.IsSetSuccess() {
		return BusinessSkillMarketplaceServiceListMarketplaceSkillsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *BusinessSkillMarketplaceServiceListMarketplaceSkillsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListMarketplaceSkillsResponse)
}

func (p *BusinessSkillMarketplaceServiceListMarketplaceSkillsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BusinessSkillMarketplaceServiceListMarketplaceSkillsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessSkillMarketplaceServiceListMarketplaceSkillsResult(%+v)", *p)
}

var fieldIDToName_BusinessSkillMarketplaceServiceListMarketplaceSkillsResult = map[int16]string{
	0: "success",
}

type BusinessSkillMarketplaceServiceGetMarketplaceSkillArgs struct {
	Request *GetMarketplaceSkillRequest `thrift:"request,1" frugal:"1,default,GetMarketplaceSkillRequest" json:"request"`
}

func NewBusinessSkillMarketplaceServiceGetMarketplaceSkillArgs() *BusinessSkillMarketplaceServiceGetMarketplaceSkillArgs {
	return &BusinessSkillMarketplaceServiceGetMarketplaceSkillArgs{}
}

func (p *BusinessSkillMarketplaceServiceGetMarketplaceSkillArgs) InitDefault() {
}

var BusinessSkillMarketplaceServiceGetMarketplaceSkillArgs_Request_DEFAULT *GetMarketplaceSkillRequest

func (p *BusinessSkillMarketplaceServiceGetMarketplaceSkillArgs) GetRequest() (v *GetMarketplaceSkillRequest) {
	if !p.IsSetRequest() {
		return BusinessSkillMarketplaceServiceGetMarketplaceSkillArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *BusinessSkillMarketplaceServiceGetMarketplaceSkillArgs) SetRequest(val *GetMarketplaceSkillRequest) {
	p.Request = val
}

func (p *BusinessSkillMarketplaceServiceGetMarketplaceSkillArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *BusinessSkillMarketplaceServiceGetMarketplaceSkillArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessSkillMarketplaceServiceGetMarketplaceSkillArgs(%+v)", *p)
}

var fieldIDToName_BusinessSkillMarketplaceServiceGetMarketplaceSkillArgs = map[int16]string{
	1: "request",
}

type BusinessSkillMarketplaceServiceGetMarketplaceSkillResult struct {
	Success *GetMarketplaceSkillResponse `thrift:"success,0,optional" frugal:"0,optional,GetMarketplaceSkillResponse" json:"success,omitempty"`
}

func NewBusinessSkillMarketplaceServiceGetMarketplaceSkillResult() *BusinessSkillMarketplaceServiceGetMarketplaceSkillResult {
	return &BusinessSkillMarketplaceServiceGetMarketplaceSkillResult{}
}

func (p *BusinessSkillMarketplaceServiceGetMarketplaceSkillResult) InitDefault() {
}

var BusinessSkillMarketplaceServiceGetMarketplaceSkillResult_Success_DEFAULT *GetMarketplaceSkillResponse

func (p *BusinessSkillMarketplaceServiceGetMarketplaceSkillResult) GetSuccess() (v *GetMarketplaceSkillResponse) {
	if !p.IsSetSuccess() {
		return BusinessSkillMarketplaceServiceGetMarketplaceSkillResult_Success_DEFAULT
	}
	return p.Success
}
func (p *BusinessSkillMarketplaceServiceGetMarketplaceSkillResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetMarketplaceSkillResponse)
}

func (p *BusinessSkillMarketplaceServiceGetMarketplaceSkillResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BusinessSkillMarketplaceServiceGetMarketplaceSkillResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessSkillMarketplaceServiceGetMarketplaceSkillResult(%+v)", *p)
}

var fieldIDToName_BusinessSkillMarketplaceServiceGetMarketplaceSkillResult = map[int16]string{
	0: "success",
}

type BusinessSkillMarketplaceServiceInstallSkillArgs struct {
	Request *InstallSkillRequest `thrift:"request,1" frugal:"1,default,InstallSkillRequest" json:"request"`
}

func NewBusinessSkillMarketplaceServiceInstallSkillArgs() *BusinessSkillMarketplaceServiceInstallSkillArgs {
	return &BusinessSkillMarketplaceServiceInstallSkillArgs{}
}

func (p *BusinessSkillMarketplaceServiceInstallSkillArgs) InitDefault() {
}

var BusinessSkillMarketplaceServiceInstallSkillArgs_Request_DEFAULT *InstallSkillRequest

func (p *BusinessSkillMarketplaceServiceInstallSkillArgs) GetRequest() (v *InstallSkillRequest) {
	if !p.IsSetRequest() {
		return BusinessSkillMarketplaceServiceInstallSkillArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *BusinessSkillMarketplaceServiceInstallSkillArgs) SetRequest(val *InstallSkillRequest) {
	p.Request = val
}

func (p *BusinessSkillMarketplaceServiceInstallSkillArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *BusinessSkillMarketplaceServiceInstallSkillArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessSkillMarketplaceServiceInstallSkillArgs(%+v)", *p)
}

var fieldIDToName_BusinessSkillMarketplaceServiceInstallSkillArgs = map[int16]string{
	1: "request",
}

type BusinessSkillMarketplaceServiceInstallSkillResult struct {
	Success *InstallSkillResponse `thrift:"success,0,optional" frugal:"0,optional,InstallSkillResponse" json:"success,omitempty"`
}

func NewBusinessSkillMarketplaceServiceInstallSkillResult() *BusinessSkillMarketplaceServiceInstallSkillResult {
	return &BusinessSkillMarketplaceServiceInstallSkillResult{}
}

func (p *BusinessSkillMarketplaceServiceInstallSkillResult) InitDefault() {
}

var BusinessSkillMarketplaceServiceInstallSkillResult_Success_DEFAULT *InstallSkillResponse

func (p *BusinessSkillMarketplaceServiceInstallSkillResult) GetSuccess() (v *InstallSkillResponse) {
	if !p.IsSetSuccess() {
		return BusinessSkillMarketplaceServiceInstallSkillResult_Success_DEFAULT
	}
	return p.Success
}
func (p *BusinessSkillMarketplaceServiceInstallSkillResult) SetSuccess(x interface{}) {
	p.Success = x.(*InstallSkillResponse)
}

func (p *BusinessSkillMarketplaceServiceInstallSkillResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BusinessSkillMarketplaceServiceInstallSkillResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessSkillMarketplaceServiceInstallSkillResult(%+v)", *p)
}

var fieldIDToName_BusinessSkillMarketplaceServiceInstallSkillResult = map[int16]string{
	0: "success",
}

type BusinessSkillMarketplaceServiceUpgradeSkillInstallationArgs struct {
	Request *UpgradeSkillInstallationRequest `thrift:"request,1" frugal:"1,default,UpgradeSkillInstallationRequest" json:"request"`
}

func NewBusinessSkillMarketplaceServiceUpgradeSkillInstallationArgs() *BusinessSkillMarketplaceServiceUpgradeSkillInstallationArgs {
	return &BusinessSkillMarketplaceServiceUpgradeSkillInstallationArgs{}
}

func (p *BusinessSkillMarketplaceServiceUpgradeSkillInstallationArgs) InitDefault() {
}

var BusinessSkillMarketplaceServiceUpgradeSkillInstallationArgs_Request_DEFAULT *UpgradeSkillInstallationRequest

func (p *BusinessSkillMarketplaceServiceUpgradeSkillInstallationArgs) GetRequest() (v *UpgradeSkillInstallationRequest) {
	if !p.IsSetRequest() {
		return BusinessSkillMarketplaceServiceUpgradeSkillInstallationArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *BusinessSkillMarketplaceServiceUpgradeSkillInstallationArgs) SetRequest(val *UpgradeSkillInstallationRequest) {
	p.Request = val
}

func (p *BusinessSkillMarketplaceServiceUpgradeSkillInstallationArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *BusinessSkillMarketplaceServiceUpgradeSkillInstallationArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessSkillMarketplaceServiceUpgradeSkillInstallationArgs(%+v)", *p)
}

var fieldIDToName_BusinessSkillMarketplaceServiceUpgradeSkillInstallationArgs = map[int16]string{
	1: "request",
}

type BusinessSkillMarketplaceServiceUpgradeSkillInstallationResult struct {
	Success *UpgradeSkillInstallationResponse `thrift:"success,0,optional" frugal:"0,optional,UpgradeSkillInstallationResponse" json:"success,omitempty"`
}

func NewBusinessSkillMarketplaceServiceUpgradeSkillInstallationResult() *BusinessSkillMarketplaceServiceUpgradeSkillInstallationResult {
	return &BusinessSkillMarketplaceServiceUpgradeSkillInstallationResult{}
}

func (p *BusinessSkillMarketplaceServiceUpgradeSkillInstallationResult) InitDefault() {
}

var BusinessSkillMarketplaceServiceUpgradeSkillInstallationResult_Success_DEFAULT *UpgradeSkillInstallationResponse

func (p *BusinessSkillMarketplaceServiceUpgradeSkillInstallationResult) GetSuccess() (v *UpgradeSkillInstallationResponse) {
	if !p.IsSetSuccess() {
		return BusinessSkillMarketplaceServiceUpgradeSkillInstallationResult_Success_DEFAULT
	}
	return p.Success
}
func (p *BusinessSkillMarketplaceServiceUpgradeSkillInstallationResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpgradeSkillInstallationResponse)
}

func (p *BusinessSkillMarketplaceServiceUpgradeSkillInstallationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BusinessSkillMarketplaceServiceUpgradeSkillInstallationResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessSkillMarketplaceServiceUpgradeSkillInstallationResult(%+v)", *p)
}

var fieldIDToName_BusinessSkillMarketplaceServiceUpgradeSkillInstallationResult = map[int16]string{
	0: "success",
}

type BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsArgs struct {
	Request *EstimateSkillUsageCreditsRequest `thrift:"request,1" frugal:"1,default,EstimateSkillUsageCreditsRequest" json:"request"`
}

func NewBusinessSkillMarketplaceServiceEstimateSkillUsageCreditsArgs() *BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsArgs {
	return &BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsArgs{}
}

func (p *BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsArgs) InitDefault() {
}

var BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsArgs_Request_DEFAULT *EstimateSkillUsageCreditsRequest

func (p *BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsArgs) GetRequest() (v *EstimateSkillUsageCreditsRequest) {
	if !p.IsSetRequest() {
		return BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsArgs) SetRequest(val *EstimateSkillUsageCreditsRequest) {
	p.Request = val
}

func (p *BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsArgs(%+v)", *p)
}

var fieldIDToName_BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsArgs = map[int16]string{
	1: "request",
}

type BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsResult struct {
	Success *EstimateSkillUsageCreditsResponse `thrift:"success,0,optional" frugal:"0,optional,EstimateSkillUsageCreditsResponse" json:"success,omitempty"`
}

func NewBusinessSkillMarketplaceServiceEstimateSkillUsageCreditsResult() *BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsResult {
	return &BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsResult{}
}

func (p *BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsResult) InitDefault() {
}

var BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsResult_Success_DEFAULT *EstimateSkillUsageCreditsResponse

func (p *BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsResult) GetSuccess() (v *EstimateSkillUsageCreditsResponse) {
	if !p.IsSetSuccess() {
		return BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsResult) SetSuccess(x interface{}) {
	p.Success = x.(*EstimateSkillUsageCreditsResponse)
}

func (p *BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsResult(%+v)", *p)
}

var fieldIDToName_BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsResult = map[int16]string{
	0: "success",
}

type BusinessSkillMarketplaceServiceCreateSkillUsageRecordArgs struct {
	Request *CreateSkillUsageRecordRequest `thrift:"request,1" frugal:"1,default,CreateSkillUsageRecordRequest" json:"request"`
}

func NewBusinessSkillMarketplaceServiceCreateSkillUsageRecordArgs() *BusinessSkillMarketplaceServiceCreateSkillUsageRecordArgs {
	return &BusinessSkillMarketplaceServiceCreateSkillUsageRecordArgs{}
}

func (p *BusinessSkillMarketplaceServiceCreateSkillUsageRecordArgs) InitDefault() {
}

var BusinessSkillMarketplaceServiceCreateSkillUsageRecordArgs_Request_DEFAULT *CreateSkillUsageRecordRequest

func (p *BusinessSkillMarketplaceServiceCreateSkillUsageRecordArgs) GetRequest() (v *CreateSkillUsageRecordRequest) {
	if !p.IsSetRequest() {
		return BusinessSkillMarketplaceServiceCreateSkillUsageRecordArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *BusinessSkillMarketplaceServiceCreateSkillUsageRecordArgs) SetRequest(val *CreateSkillUsageRecordRequest) {
	p.Request = val
}

func (p *BusinessSkillMarketplaceServiceCreateSkillUsageRecordArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *BusinessSkillMarketplaceServiceCreateSkillUsageRecordArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessSkillMarketplaceServiceCreateSkillUsageRecordArgs(%+v)", *p)
}

var fieldIDToName_BusinessSkillMarketplaceServiceCreateSkillUsageRecordArgs = map[int16]string{
	1: "request",
}

type BusinessSkillMarketplaceServiceCreateSkillUsageRecordResult struct {
	Success *CreateSkillUsageRecordResponse `thrift:"success,0,optional" frugal:"0,optional,CreateSkillUsageRecordResponse" json:"success,omitempty"`
}

func NewBusinessSkillMarketplaceServiceCreateSkillUsageRecordResult() *BusinessSkillMarketplaceServiceCreateSkillUsageRecordResult {
	return &BusinessSkillMarketplaceServiceCreateSkillUsageRecordResult{}
}

func (p *BusinessSkillMarketplaceServiceCreateSkillUsageRecordResult) InitDefault() {
}

var BusinessSkillMarketplaceServiceCreateSkillUsageRecordResult_Success_DEFAULT *CreateSkillUsageRecordResponse

func (p *BusinessSkillMarketplaceServiceCreateSkillUsageRecordResult) GetSuccess() (v *CreateSkillUsageRecordResponse) {
	if !p.IsSetSuccess() {
		return BusinessSkillMarketplaceServiceCreateSkillUsageRecordResult_Success_DEFAULT
	}
	return p.Success
}
func (p *BusinessSkillMarketplaceServiceCreateSkillUsageRecordResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateSkillUsageRecordResponse)
}

func (p *BusinessSkillMarketplaceServiceCreateSkillUsageRecordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BusinessSkillMarketplaceServiceCreateSkillUsageRecordResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessSkillMarketplaceServiceCreateSkillUsageRecordResult(%+v)", *p)
}

var fieldIDToName_BusinessSkillMarketplaceServiceCreateSkillUsageRecordResult = map[int16]string{
	0: "success",
}

type BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsArgs struct {
	Request *FreezeSkillUsageCreditsRequest `thrift:"request,1" frugal:"1,default,FreezeSkillUsageCreditsRequest" json:"request"`
}

func NewBusinessSkillMarketplaceServiceFreezeSkillUsageCreditsArgs() *BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsArgs {
	return &BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsArgs{}
}

func (p *BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsArgs) InitDefault() {
}

var BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsArgs_Request_DEFAULT *FreezeSkillUsageCreditsRequest

func (p *BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsArgs) GetRequest() (v *FreezeSkillUsageCreditsRequest) {
	if !p.IsSetRequest() {
		return BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsArgs) SetRequest(val *FreezeSkillUsageCreditsRequest) {
	p.Request = val
}

func (p *BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsArgs(%+v)", *p)
}

var fieldIDToName_BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsArgs = map[int16]string{
	1: "request",
}

type BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsResult struct {
	Success *FreezeSkillUsageCreditsResponse `thrift:"success,0,optional" frugal:"0,optional,FreezeSkillUsageCreditsResponse" json:"success,omitempty"`
}

func NewBusinessSkillMarketplaceServiceFreezeSkillUsageCreditsResult() *BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsResult {
	return &BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsResult{}
}

func (p *BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsResult) InitDefault() {
}

var BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsResult_Success_DEFAULT *FreezeSkillUsageCreditsResponse

func (p *BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsResult) GetSuccess() (v *FreezeSkillUsageCreditsResponse) {
	if !p.IsSetSuccess() {
		return BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsResult) SetSuccess(x interface{}) {
	p.Success = x.(*FreezeSkillUsageCreditsResponse)
}

func (p *BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsResult(%+v)", *p)
}

var fieldIDToName_BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsResult = map[int16]string{
	0: "success",
}

type BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleArgs struct {
	Request *CommitSkillUsageAndSettleRequest `thrift:"request,1" frugal:"1,default,CommitSkillUsageAndSettleRequest" json:"request"`
}

func NewBusinessSkillMarketplaceServiceCommitSkillUsageAndSettleArgs() *BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleArgs {
	return &BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleArgs{}
}

func (p *BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleArgs) InitDefault() {
}

var BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleArgs_Request_DEFAULT *CommitSkillUsageAndSettleRequest

func (p *BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleArgs) GetRequest() (v *CommitSkillUsageAndSettleRequest) {
	if !p.IsSetRequest() {
		return BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleArgs) SetRequest(val *CommitSkillUsageAndSettleRequest) {
	p.Request = val
}

func (p *BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleArgs(%+v)", *p)
}

var fieldIDToName_BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleArgs = map[int16]string{
	1: "request",
}

type BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleResult struct {
	Success *CommitSkillUsageAndSettleResponse `thrift:"success,0,optional" frugal:"0,optional,CommitSkillUsageAndSettleResponse" json:"success,omitempty"`
}

func NewBusinessSkillMarketplaceServiceCommitSkillUsageAndSettleResult() *BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleResult {
	return &BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleResult{}
}

func (p *BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleResult) InitDefault() {
}

var BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleResult_Success_DEFAULT *CommitSkillUsageAndSettleResponse

func (p *BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleResult) GetSuccess() (v *CommitSkillUsageAndSettleResponse) {
	if !p.IsSetSuccess() {
		return BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleResult_Success_DEFAULT
	}
	return p.Success
}
func (p *BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommitSkillUsageAndSettleResponse)
}

func (p *BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleResult(%+v)", *p)
}

var fieldIDToName_BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleResult = map[int16]string{
	0: "success",
}

type BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeArgs struct {
	Request *ReleaseSkillUsageFreezeRequest `thrift:"request,1" frugal:"1,default,ReleaseSkillUsageFreezeRequest" json:"request"`
}

func NewBusinessSkillMarketplaceServiceReleaseSkillUsageFreezeArgs() *BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeArgs {
	return &BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeArgs{}
}

func (p *BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeArgs) InitDefault() {
}

var BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeArgs_Request_DEFAULT *ReleaseSkillUsageFreezeRequest

func (p *BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeArgs) GetRequest() (v *ReleaseSkillUsageFreezeRequest) {
	if !p.IsSetRequest() {
		return BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeArgs) SetRequest(val *ReleaseSkillUsageFreezeRequest) {
	p.Request = val
}

func (p *BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeArgs(%+v)", *p)
}

var fieldIDToName_BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeArgs = map[int16]string{
	1: "request",
}

type BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeResult struct {
	Success *ReleaseSkillUsageFreezeResponse `thrift:"success,0,optional" frugal:"0,optional,ReleaseSkillUsageFreezeResponse" json:"success,omitempty"`
}

func NewBusinessSkillMarketplaceServiceReleaseSkillUsageFreezeResult() *BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeResult {
	return &BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeResult{}
}

func (p *BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeResult) InitDefault() {
}

var BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeResult_Success_DEFAULT *ReleaseSkillUsageFreezeResponse

func (p *BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeResult) GetSuccess() (v *ReleaseSkillUsageFreezeResponse) {
	if !p.IsSetSuccess() {
		return BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeResult) SetSuccess(x interface{}) {
	p.Success = x.(*ReleaseSkillUsageFreezeResponse)
}

func (p *BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeResult(%+v)", *p)
}

var fieldIDToName_BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeResult = map[int16]string{
	0: "success",
}
