// Code generated by Kitex v0.16.2. DO NOT EDIT.

package assetservice

import (
	"context"
	"errors"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"BatchCheckAssetAccess": kitex.NewMethodInfo(
		batchCheckAssetAccessHandler,
		newAssetServiceBatchCheckAssetAccessArgs,
		newAssetServiceBatchCheckAssetAccessResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"PrepareGeneratedAssetObjects": kitex.NewMethodInfo(
		prepareGeneratedAssetObjectsHandler,
		newAssetServicePrepareGeneratedAssetObjectsArgs,
		newAssetServicePrepareGeneratedAssetObjectsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	assetServiceServiceInfo                = NewServiceInfo()
	assetServiceServiceInfoForClient       = NewServiceInfoForClient()
	assetServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return assetServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return assetServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return assetServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AssetService"
	handlerType := (*businessagent.AssetService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "businessagent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func batchCheckAssetAccessHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.AssetServiceBatchCheckAssetAccessArgs)
	realResult := result.(*businessagent.AssetServiceBatchCheckAssetAccessResult)
	success, err := handler.(businessagent.AssetService).BatchCheckAssetAccess(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceBatchCheckAssetAccessArgs() interface{} {
	return businessagent.NewAssetServiceBatchCheckAssetAccessArgs()
}

func newAssetServiceBatchCheckAssetAccessResult() interface{} {
	return businessagent.NewAssetServiceBatchCheckAssetAccessResult()
}

func prepareGeneratedAssetObjectsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.AssetServicePrepareGeneratedAssetObjectsArgs)
	realResult := result.(*businessagent.AssetServicePrepareGeneratedAssetObjectsResult)
	success, err := handler.(businessagent.AssetService).PrepareGeneratedAssetObjects(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServicePrepareGeneratedAssetObjectsArgs() interface{} {
	return businessagent.NewAssetServicePrepareGeneratedAssetObjectsArgs()
}

func newAssetServicePrepareGeneratedAssetObjectsResult() interface{} {
	return businessagent.NewAssetServicePrepareGeneratedAssetObjectsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) BatchCheckAssetAccess(ctx context.Context, req *businessagent.BatchCheckAssetAccessRequest) (r *businessagent.BatchCheckAssetAccessResponse, err error) {
	var _args businessagent.AssetServiceBatchCheckAssetAccessArgs
	_args.Req = req
	var _result businessagent.AssetServiceBatchCheckAssetAccessResult
	if err = p.c.Call(ctx, "BatchCheckAssetAccess", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PrepareGeneratedAssetObjects(ctx context.Context, req *businessagent.PrepareGeneratedAssetObjectsRequest) (r *businessagent.PrepareGeneratedAssetObjectsResponse, err error) {
	var _args businessagent.AssetServicePrepareGeneratedAssetObjectsArgs
	_args.Req = req
	var _result businessagent.AssetServicePrepareGeneratedAssetObjectsResult
	if err = p.c.Call(ctx, "PrepareGeneratedAssetObjects", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
