// Code generated by Kitex v0.16.2. DO NOT EDIT.

package assetservice

import (
	"context"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateUploadIntent(ctx context.Context, req *businessagent.CreateUploadIntentRequest, callOptions ...callopt.Option) (r *businessagent.UploadIntentDTO, err error)
	ConfirmUploadedAsset(ctx context.Context, req *businessagent.ConfirmUploadedAssetRequest, callOptions ...callopt.Option) (r *businessagent.AssetDetailDTO, err error)
	BatchCheckAssetAccess(ctx context.Context, req *businessagent.BatchCheckAssetAccessRequest, callOptions ...callopt.Option) (r *businessagent.BatchCheckAssetAccessResponse, err error)
	PrepareGeneratedAssetObjects(ctx context.Context, req *businessagent.PrepareGeneratedAssetObjectsRequest, callOptions ...callopt.Option) (r *businessagent.PrepareGeneratedAssetObjectsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAssetServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAssetServiceClient struct {
	*kClient
}

func (p *kAssetServiceClient) CreateUploadIntent(ctx context.Context, req *businessagent.CreateUploadIntentRequest, callOptions ...callopt.Option) (r *businessagent.UploadIntentDTO, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateUploadIntent(ctx, req)
}

func (p *kAssetServiceClient) ConfirmUploadedAsset(ctx context.Context, req *businessagent.ConfirmUploadedAssetRequest, callOptions ...callopt.Option) (r *businessagent.AssetDetailDTO, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ConfirmUploadedAsset(ctx, req)
}

func (p *kAssetServiceClient) BatchCheckAssetAccess(ctx context.Context, req *businessagent.BatchCheckAssetAccessRequest, callOptions ...callopt.Option) (r *businessagent.BatchCheckAssetAccessResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchCheckAssetAccess(ctx, req)
}

func (p *kAssetServiceClient) PrepareGeneratedAssetObjects(ctx context.Context, req *businessagent.PrepareGeneratedAssetObjectsRequest, callOptions ...callopt.Option) (r *businessagent.PrepareGeneratedAssetObjectsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PrepareGeneratedAssetObjects(ctx, req)
}
