// Code generated by Kitex v0.16.2. DO NOT EDIT.

package useradminservice

import (
	"context"
	"errors"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"PreviewSetUserStatus": kitex.NewMethodInfo(
		previewSetUserStatusHandler,
		newUserAdminServicePreviewSetUserStatusArgs,
		newUserAdminServicePreviewSetUserStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ConfirmSetUserStatus": kitex.NewMethodInfo(
		confirmSetUserStatusHandler,
		newUserAdminServiceConfirmSetUserStatusArgs,
		newUserAdminServiceConfirmSetUserStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userAdminServiceServiceInfo                = NewServiceInfo()
	userAdminServiceServiceInfoForClient       = NewServiceInfoForClient()
	userAdminServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userAdminServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userAdminServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userAdminServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserAdminService"
	handlerType := (*businessagent.UserAdminService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "businessagent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func previewSetUserStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.UserAdminServicePreviewSetUserStatusArgs)
	realResult := result.(*businessagent.UserAdminServicePreviewSetUserStatusResult)
	success, err := handler.(businessagent.UserAdminService).PreviewSetUserStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserAdminServicePreviewSetUserStatusArgs() interface{} {
	return businessagent.NewUserAdminServicePreviewSetUserStatusArgs()
}

func newUserAdminServicePreviewSetUserStatusResult() interface{} {
	return businessagent.NewUserAdminServicePreviewSetUserStatusResult()
}

func confirmSetUserStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.UserAdminServiceConfirmSetUserStatusArgs)
	realResult := result.(*businessagent.UserAdminServiceConfirmSetUserStatusResult)
	success, err := handler.(businessagent.UserAdminService).ConfirmSetUserStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserAdminServiceConfirmSetUserStatusArgs() interface{} {
	return businessagent.NewUserAdminServiceConfirmSetUserStatusArgs()
}

func newUserAdminServiceConfirmSetUserStatusResult() interface{} {
	return businessagent.NewUserAdminServiceConfirmSetUserStatusResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PreviewSetUserStatus(ctx context.Context, req *businessagent.PreviewSetUserStatusRequest) (r *businessagent.UserStatusPreviewDTO, err error) {
	var _args businessagent.UserAdminServicePreviewSetUserStatusArgs
	_args.Req = req
	var _result businessagent.UserAdminServicePreviewSetUserStatusResult
	if err = p.c.Call(ctx, "PreviewSetUserStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfirmSetUserStatus(ctx context.Context, req *businessagent.ConfirmSetUserStatusRequest) (r *businessagent.AdminUserSummaryDTO, err error) {
	var _args businessagent.UserAdminServiceConfirmSetUserStatusArgs
	_args.Req = req
	var _result businessagent.UserAdminServiceConfirmSetUserStatusResult
	if err = p.c.Call(ctx, "ConfirmSetUserStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
