// Code generated by Kitex v0.16.2. DO NOT EDIT.

package publiccontentservice

import (
	"context"
	"errors"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListPublicWorks": kitex.NewMethodInfo(
		listPublicWorksHandler,
		newPublicContentServiceListPublicWorksArgs,
		newPublicContentServiceListPublicWorksResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPublicWork": kitex.NewMethodInfo(
		getPublicWorkHandler,
		newPublicContentServiceGetPublicWorkArgs,
		newPublicContentServiceGetPublicWorkResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	publicContentServiceServiceInfo                = NewServiceInfo()
	publicContentServiceServiceInfoForClient       = NewServiceInfoForClient()
	publicContentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return publicContentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return publicContentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return publicContentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PublicContentService"
	handlerType := (*businessagent.PublicContentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "businessagent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func listPublicWorksHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.PublicContentServiceListPublicWorksArgs)
	realResult := result.(*businessagent.PublicContentServiceListPublicWorksResult)
	success, err := handler.(businessagent.PublicContentService).ListPublicWorks(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPublicContentServiceListPublicWorksArgs() interface{} {
	return businessagent.NewPublicContentServiceListPublicWorksArgs()
}

func newPublicContentServiceListPublicWorksResult() interface{} {
	return businessagent.NewPublicContentServiceListPublicWorksResult()
}

func getPublicWorkHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.PublicContentServiceGetPublicWorkArgs)
	realResult := result.(*businessagent.PublicContentServiceGetPublicWorkResult)
	success, err := handler.(businessagent.PublicContentService).GetPublicWork(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPublicContentServiceGetPublicWorkArgs() interface{} {
	return businessagent.NewPublicContentServiceGetPublicWorkArgs()
}

func newPublicContentServiceGetPublicWorkResult() interface{} {
	return businessagent.NewPublicContentServiceGetPublicWorkResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListPublicWorks(ctx context.Context, req *businessagent.ListPublicWorksRequest) (r *businessagent.ListPublicWorksResponse, err error) {
	var _args businessagent.PublicContentServiceListPublicWorksArgs
	_args.Req = req
	var _result businessagent.PublicContentServiceListPublicWorksResult
	if err = p.c.Call(ctx, "ListPublicWorks", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPublicWork(ctx context.Context, req *businessagent.GetPublicWorkRequest) (r *businessagent.PublicWorkDetailDTO, err error) {
	var _args businessagent.PublicContentServiceGetPublicWorkArgs
	_args.Req = req
	var _result businessagent.PublicContentServiceGetPublicWorkResult
	if err = p.c.Call(ctx, "GetPublicWork", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
