// Code generated by Kitex v0.16.2. DO NOT EDIT.

package projectservice

import (
	"context"
	"errors"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CheckProjectAccess": kitex.NewMethodInfo(
		checkProjectAccessHandler,
		newProjectServiceCheckProjectAccessArgs,
		newProjectServiceCheckProjectAccessResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateProject": kitex.NewMethodInfo(
		createProjectHandler,
		newProjectServiceCreateProjectArgs,
		newProjectServiceCreateProjectResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateProjectTitle": kitex.NewMethodInfo(
		updateProjectTitleHandler,
		newProjectServiceUpdateProjectTitleArgs,
		newProjectServiceUpdateProjectTitleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	projectServiceServiceInfo                = NewServiceInfo()
	projectServiceServiceInfoForClient       = NewServiceInfoForClient()
	projectServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return projectServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return projectServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return projectServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ProjectService"
	handlerType := (*businessagent.ProjectService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "businessagent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func checkProjectAccessHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.ProjectServiceCheckProjectAccessArgs)
	realResult := result.(*businessagent.ProjectServiceCheckProjectAccessResult)
	success, err := handler.(businessagent.ProjectService).CheckProjectAccess(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProjectServiceCheckProjectAccessArgs() interface{} {
	return businessagent.NewProjectServiceCheckProjectAccessArgs()
}

func newProjectServiceCheckProjectAccessResult() interface{} {
	return businessagent.NewProjectServiceCheckProjectAccessResult()
}

func createProjectHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.ProjectServiceCreateProjectArgs)
	realResult := result.(*businessagent.ProjectServiceCreateProjectResult)
	success, err := handler.(businessagent.ProjectService).CreateProject(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProjectServiceCreateProjectArgs() interface{} {
	return businessagent.NewProjectServiceCreateProjectArgs()
}

func newProjectServiceCreateProjectResult() interface{} {
	return businessagent.NewProjectServiceCreateProjectResult()
}

func updateProjectTitleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.ProjectServiceUpdateProjectTitleArgs)
	realResult := result.(*businessagent.ProjectServiceUpdateProjectTitleResult)
	success, err := handler.(businessagent.ProjectService).UpdateProjectTitle(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProjectServiceUpdateProjectTitleArgs() interface{} {
	return businessagent.NewProjectServiceUpdateProjectTitleArgs()
}

func newProjectServiceUpdateProjectTitleResult() interface{} {
	return businessagent.NewProjectServiceUpdateProjectTitleResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CheckProjectAccess(ctx context.Context, req *businessagent.CheckProjectAccessRequest) (r *businessagent.ProjectAccessResponse, err error) {
	var _args businessagent.ProjectServiceCheckProjectAccessArgs
	_args.Req = req
	var _result businessagent.ProjectServiceCheckProjectAccessResult
	if err = p.c.Call(ctx, "CheckProjectAccess", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateProject(ctx context.Context, req *businessagent.CreateProjectRequest) (r *businessagent.ProjectDetailDTO, err error) {
	var _args businessagent.ProjectServiceCreateProjectArgs
	_args.Req = req
	var _result businessagent.ProjectServiceCreateProjectResult
	if err = p.c.Call(ctx, "CreateProject", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateProjectTitle(ctx context.Context, req *businessagent.UpdateProjectTitleRequest) (r *businessagent.ProjectDetailDTO, err error) {
	var _args businessagent.ProjectServiceUpdateProjectTitleArgs
	_args.Req = req
	var _result businessagent.ProjectServiceUpdateProjectTitleResult
	if err = p.c.Call(ctx, "UpdateProjectTitle", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
