// Code generated by Kitex v0.16.2. DO NOT EDIT.

package creditservice

import (
	"context"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	EstimateGenerationCredits(ctx context.Context, req *businessagent.EstimateGenerationCreditsRequest, callOptions ...callopt.Option) (r *businessagent.EstimateGenerationCreditsResponse, err error)
	EstimateToolCredits(ctx context.Context, req *businessagent.EstimateToolCreditsRequest, callOptions ...callopt.Option) (r *businessagent.EstimateToolCreditsResponse, err error)
	FreezeCredits(ctx context.Context, req *businessagent.FreezeCreditsRequest, callOptions ...callopt.Option) (r *businessagent.FreezeCreditsResponse, err error)
	ChargeToolUsageCredits(ctx context.Context, req *businessagent.ChargeToolUsageCreditsRequest, callOptions ...callopt.Option) (r *businessagent.ChargeToolUsageCreditsResponse, err error)
	ReleaseFrozenCredits(ctx context.Context, req *businessagent.ReleaseFrozenCreditsRequest, callOptions ...callopt.Option) (r *businessagent.ReleaseFrozenCreditsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kCreditServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCreditServiceClient struct {
	*kClient
}

func (p *kCreditServiceClient) EstimateGenerationCredits(ctx context.Context, req *businessagent.EstimateGenerationCreditsRequest, callOptions ...callopt.Option) (r *businessagent.EstimateGenerationCreditsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EstimateGenerationCredits(ctx, req)
}

func (p *kCreditServiceClient) EstimateToolCredits(ctx context.Context, req *businessagent.EstimateToolCreditsRequest, callOptions ...callopt.Option) (r *businessagent.EstimateToolCreditsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EstimateToolCredits(ctx, req)
}

func (p *kCreditServiceClient) FreezeCredits(ctx context.Context, req *businessagent.FreezeCreditsRequest, callOptions ...callopt.Option) (r *businessagent.FreezeCreditsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FreezeCredits(ctx, req)
}

func (p *kCreditServiceClient) ChargeToolUsageCredits(ctx context.Context, req *businessagent.ChargeToolUsageCreditsRequest, callOptions ...callopt.Option) (r *businessagent.ChargeToolUsageCreditsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChargeToolUsageCredits(ctx, req)
}

func (p *kCreditServiceClient) ReleaseFrozenCredits(ctx context.Context, req *businessagent.ReleaseFrozenCreditsRequest, callOptions ...callopt.Option) (r *businessagent.ReleaseFrozenCreditsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReleaseFrozenCredits(ctx, req)
}
