// Code generated by Kitex v0.16.2. DO NOT EDIT.

package creditservice

import (
	"context"
	"errors"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"EstimateGenerationCredits": kitex.NewMethodInfo(
		estimateGenerationCreditsHandler,
		newCreditServiceEstimateGenerationCreditsArgs,
		newCreditServiceEstimateGenerationCreditsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"EstimateToolCredits": kitex.NewMethodInfo(
		estimateToolCreditsHandler,
		newCreditServiceEstimateToolCreditsArgs,
		newCreditServiceEstimateToolCreditsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FreezeCredits": kitex.NewMethodInfo(
		freezeCreditsHandler,
		newCreditServiceFreezeCreditsArgs,
		newCreditServiceFreezeCreditsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChargeToolUsageCredits": kitex.NewMethodInfo(
		chargeToolUsageCreditsHandler,
		newCreditServiceChargeToolUsageCreditsArgs,
		newCreditServiceChargeToolUsageCreditsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ReleaseFrozenCredits": kitex.NewMethodInfo(
		releaseFrozenCreditsHandler,
		newCreditServiceReleaseFrozenCreditsArgs,
		newCreditServiceReleaseFrozenCreditsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	creditServiceServiceInfo                = NewServiceInfo()
	creditServiceServiceInfoForClient       = NewServiceInfoForClient()
	creditServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return creditServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return creditServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return creditServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CreditService"
	handlerType := (*businessagent.CreditService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "businessagent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func estimateGenerationCreditsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.CreditServiceEstimateGenerationCreditsArgs)
	realResult := result.(*businessagent.CreditServiceEstimateGenerationCreditsResult)
	success, err := handler.(businessagent.CreditService).EstimateGenerationCredits(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCreditServiceEstimateGenerationCreditsArgs() interface{} {
	return businessagent.NewCreditServiceEstimateGenerationCreditsArgs()
}

func newCreditServiceEstimateGenerationCreditsResult() interface{} {
	return businessagent.NewCreditServiceEstimateGenerationCreditsResult()
}

func estimateToolCreditsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.CreditServiceEstimateToolCreditsArgs)
	realResult := result.(*businessagent.CreditServiceEstimateToolCreditsResult)
	success, err := handler.(businessagent.CreditService).EstimateToolCredits(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCreditServiceEstimateToolCreditsArgs() interface{} {
	return businessagent.NewCreditServiceEstimateToolCreditsArgs()
}

func newCreditServiceEstimateToolCreditsResult() interface{} {
	return businessagent.NewCreditServiceEstimateToolCreditsResult()
}

func freezeCreditsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.CreditServiceFreezeCreditsArgs)
	realResult := result.(*businessagent.CreditServiceFreezeCreditsResult)
	success, err := handler.(businessagent.CreditService).FreezeCredits(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCreditServiceFreezeCreditsArgs() interface{} {
	return businessagent.NewCreditServiceFreezeCreditsArgs()
}

func newCreditServiceFreezeCreditsResult() interface{} {
	return businessagent.NewCreditServiceFreezeCreditsResult()
}

func chargeToolUsageCreditsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.CreditServiceChargeToolUsageCreditsArgs)
	realResult := result.(*businessagent.CreditServiceChargeToolUsageCreditsResult)
	success, err := handler.(businessagent.CreditService).ChargeToolUsageCredits(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCreditServiceChargeToolUsageCreditsArgs() interface{} {
	return businessagent.NewCreditServiceChargeToolUsageCreditsArgs()
}

func newCreditServiceChargeToolUsageCreditsResult() interface{} {
	return businessagent.NewCreditServiceChargeToolUsageCreditsResult()
}

func releaseFrozenCreditsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.CreditServiceReleaseFrozenCreditsArgs)
	realResult := result.(*businessagent.CreditServiceReleaseFrozenCreditsResult)
	success, err := handler.(businessagent.CreditService).ReleaseFrozenCredits(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCreditServiceReleaseFrozenCreditsArgs() interface{} {
	return businessagent.NewCreditServiceReleaseFrozenCreditsArgs()
}

func newCreditServiceReleaseFrozenCreditsResult() interface{} {
	return businessagent.NewCreditServiceReleaseFrozenCreditsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) EstimateGenerationCredits(ctx context.Context, req *businessagent.EstimateGenerationCreditsRequest) (r *businessagent.EstimateGenerationCreditsResponse, err error) {
	var _args businessagent.CreditServiceEstimateGenerationCreditsArgs
	_args.Req = req
	var _result businessagent.CreditServiceEstimateGenerationCreditsResult
	if err = p.c.Call(ctx, "EstimateGenerationCredits", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EstimateToolCredits(ctx context.Context, req *businessagent.EstimateToolCreditsRequest) (r *businessagent.EstimateToolCreditsResponse, err error) {
	var _args businessagent.CreditServiceEstimateToolCreditsArgs
	_args.Req = req
	var _result businessagent.CreditServiceEstimateToolCreditsResult
	if err = p.c.Call(ctx, "EstimateToolCredits", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FreezeCredits(ctx context.Context, req *businessagent.FreezeCreditsRequest) (r *businessagent.FreezeCreditsResponse, err error) {
	var _args businessagent.CreditServiceFreezeCreditsArgs
	_args.Req = req
	var _result businessagent.CreditServiceFreezeCreditsResult
	if err = p.c.Call(ctx, "FreezeCredits", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChargeToolUsageCredits(ctx context.Context, req *businessagent.ChargeToolUsageCreditsRequest) (r *businessagent.ChargeToolUsageCreditsResponse, err error) {
	var _args businessagent.CreditServiceChargeToolUsageCreditsArgs
	_args.Req = req
	var _result businessagent.CreditServiceChargeToolUsageCreditsResult
	if err = p.c.Call(ctx, "ChargeToolUsageCredits", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReleaseFrozenCredits(ctx context.Context, req *businessagent.ReleaseFrozenCreditsRequest) (r *businessagent.ReleaseFrozenCreditsResponse, err error) {
	var _args businessagent.CreditServiceReleaseFrozenCreditsArgs
	_args.Req = req
	var _result businessagent.CreditServiceReleaseFrozenCreditsResult
	if err = p.c.Call(ctx, "ReleaseFrozenCredits", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
