// Code generated by Kitex v0.16.2. DO NOT EDIT.

package skillcatalogservice

import (
	"context"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ListRoutableSkills(ctx context.Context, req *businessagent.ListRoutableSkillsRequest, callOptions ...callopt.Option) (r *businessagent.ListRoutableSkillsResponse, err error)
	GetPublishedSkillSpec(ctx context.Context, req *businessagent.GetPublishedSkillSpecRequest, callOptions ...callopt.Option) (r *businessagent.SkillSpecResponse, err error)
	GetReviewCandidateSkillSpec(ctx context.Context, req *businessagent.GetReviewCandidateSkillSpecRequest, callOptions ...callopt.Option) (r *businessagent.ReviewCandidateSkillSpecResponse, err error)
	SaveSkillTestResult_(ctx context.Context, req *businessagent.SaveSkillTestResultRequest, callOptions ...callopt.Option) (r *businessagent.SaveSkillTestResultResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kSkillCatalogServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSkillCatalogServiceClient struct {
	*kClient
}

func (p *kSkillCatalogServiceClient) ListRoutableSkills(ctx context.Context, req *businessagent.ListRoutableSkillsRequest, callOptions ...callopt.Option) (r *businessagent.ListRoutableSkillsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListRoutableSkills(ctx, req)
}

func (p *kSkillCatalogServiceClient) GetPublishedSkillSpec(ctx context.Context, req *businessagent.GetPublishedSkillSpecRequest, callOptions ...callopt.Option) (r *businessagent.SkillSpecResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPublishedSkillSpec(ctx, req)
}

func (p *kSkillCatalogServiceClient) GetReviewCandidateSkillSpec(ctx context.Context, req *businessagent.GetReviewCandidateSkillSpecRequest, callOptions ...callopt.Option) (r *businessagent.ReviewCandidateSkillSpecResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetReviewCandidateSkillSpec(ctx, req)
}

func (p *kSkillCatalogServiceClient) SaveSkillTestResult_(ctx context.Context, req *businessagent.SaveSkillTestResultRequest, callOptions ...callopt.Option) (r *businessagent.SaveSkillTestResultResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SaveSkillTestResult_(ctx, req)
}
