// Code generated by Kitex v0.16.2. DO NOT EDIT.

package skillcatalogservice

import (
	"context"
	"errors"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListRoutableSkills": kitex.NewMethodInfo(
		listRoutableSkillsHandler,
		newSkillCatalogServiceListRoutableSkillsArgs,
		newSkillCatalogServiceListRoutableSkillsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPublishedSkillSpec": kitex.NewMethodInfo(
		getPublishedSkillSpecHandler,
		newSkillCatalogServiceGetPublishedSkillSpecArgs,
		newSkillCatalogServiceGetPublishedSkillSpecResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetReviewCandidateSkillSpec": kitex.NewMethodInfo(
		getReviewCandidateSkillSpecHandler,
		newSkillCatalogServiceGetReviewCandidateSkillSpecArgs,
		newSkillCatalogServiceGetReviewCandidateSkillSpecResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SaveSkillTestResult": kitex.NewMethodInfo(
		saveSkillTestResult_Handler,
		newSkillCatalogServiceSaveSkillTestResultArgs,
		newSkillCatalogServiceSaveSkillTestResultResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	skillCatalogServiceServiceInfo                = NewServiceInfo()
	skillCatalogServiceServiceInfoForClient       = NewServiceInfoForClient()
	skillCatalogServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return skillCatalogServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return skillCatalogServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return skillCatalogServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "SkillCatalogService"
	handlerType := (*businessagent.SkillCatalogService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "businessagent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func listRoutableSkillsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.SkillCatalogServiceListRoutableSkillsArgs)
	realResult := result.(*businessagent.SkillCatalogServiceListRoutableSkillsResult)
	success, err := handler.(businessagent.SkillCatalogService).ListRoutableSkills(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSkillCatalogServiceListRoutableSkillsArgs() interface{} {
	return businessagent.NewSkillCatalogServiceListRoutableSkillsArgs()
}

func newSkillCatalogServiceListRoutableSkillsResult() interface{} {
	return businessagent.NewSkillCatalogServiceListRoutableSkillsResult()
}

func getPublishedSkillSpecHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.SkillCatalogServiceGetPublishedSkillSpecArgs)
	realResult := result.(*businessagent.SkillCatalogServiceGetPublishedSkillSpecResult)
	success, err := handler.(businessagent.SkillCatalogService).GetPublishedSkillSpec(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSkillCatalogServiceGetPublishedSkillSpecArgs() interface{} {
	return businessagent.NewSkillCatalogServiceGetPublishedSkillSpecArgs()
}

func newSkillCatalogServiceGetPublishedSkillSpecResult() interface{} {
	return businessagent.NewSkillCatalogServiceGetPublishedSkillSpecResult()
}

func getReviewCandidateSkillSpecHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.SkillCatalogServiceGetReviewCandidateSkillSpecArgs)
	realResult := result.(*businessagent.SkillCatalogServiceGetReviewCandidateSkillSpecResult)
	success, err := handler.(businessagent.SkillCatalogService).GetReviewCandidateSkillSpec(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSkillCatalogServiceGetReviewCandidateSkillSpecArgs() interface{} {
	return businessagent.NewSkillCatalogServiceGetReviewCandidateSkillSpecArgs()
}

func newSkillCatalogServiceGetReviewCandidateSkillSpecResult() interface{} {
	return businessagent.NewSkillCatalogServiceGetReviewCandidateSkillSpecResult()
}

func saveSkillTestResult_Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.SkillCatalogServiceSaveSkillTestResultArgs)
	realResult := result.(*businessagent.SkillCatalogServiceSaveSkillTestResultResult)
	success, err := handler.(businessagent.SkillCatalogService).SaveSkillTestResult_(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSkillCatalogServiceSaveSkillTestResultArgs() interface{} {
	return businessagent.NewSkillCatalogServiceSaveSkillTestResultArgs()
}

func newSkillCatalogServiceSaveSkillTestResultResult() interface{} {
	return businessagent.NewSkillCatalogServiceSaveSkillTestResultResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListRoutableSkills(ctx context.Context, req *businessagent.ListRoutableSkillsRequest) (r *businessagent.ListRoutableSkillsResponse, err error) {
	var _args businessagent.SkillCatalogServiceListRoutableSkillsArgs
	_args.Req = req
	var _result businessagent.SkillCatalogServiceListRoutableSkillsResult
	if err = p.c.Call(ctx, "ListRoutableSkills", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPublishedSkillSpec(ctx context.Context, req *businessagent.GetPublishedSkillSpecRequest) (r *businessagent.SkillSpecResponse, err error) {
	var _args businessagent.SkillCatalogServiceGetPublishedSkillSpecArgs
	_args.Req = req
	var _result businessagent.SkillCatalogServiceGetPublishedSkillSpecResult
	if err = p.c.Call(ctx, "GetPublishedSkillSpec", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetReviewCandidateSkillSpec(ctx context.Context, req *businessagent.GetReviewCandidateSkillSpecRequest) (r *businessagent.ReviewCandidateSkillSpecResponse, err error) {
	var _args businessagent.SkillCatalogServiceGetReviewCandidateSkillSpecArgs
	_args.Req = req
	var _result businessagent.SkillCatalogServiceGetReviewCandidateSkillSpecResult
	if err = p.c.Call(ctx, "GetReviewCandidateSkillSpec", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SaveSkillTestResult_(ctx context.Context, req *businessagent.SaveSkillTestResultRequest) (r *businessagent.SaveSkillTestResultResponse, err error) {
	var _args businessagent.SkillCatalogServiceSaveSkillTestResultArgs
	_args.Req = req
	var _result businessagent.SkillCatalogServiceSaveSkillTestResultResult
	if err = p.c.Call(ctx, "SaveSkillTestResult", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
