// Code generated by Kitex v0.16.2. DO NOT EDIT.

package workshareservice

import (
	"context"
	"errors"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"PreviewShareWork": kitex.NewMethodInfo(
		previewShareWorkHandler,
		newWorkShareServicePreviewShareWorkArgs,
		newWorkShareServicePreviewShareWorkResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ConfirmShareWork": kitex.NewMethodInfo(
		confirmShareWorkHandler,
		newWorkShareServiceConfirmShareWorkArgs,
		newWorkShareServiceConfirmShareWorkResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	workShareServiceServiceInfo                = NewServiceInfo()
	workShareServiceServiceInfoForClient       = NewServiceInfoForClient()
	workShareServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return workShareServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return workShareServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return workShareServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "WorkShareService"
	handlerType := (*businessagent.WorkShareService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "businessagent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func previewShareWorkHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.WorkShareServicePreviewShareWorkArgs)
	realResult := result.(*businessagent.WorkShareServicePreviewShareWorkResult)
	success, err := handler.(businessagent.WorkShareService).PreviewShareWork(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newWorkShareServicePreviewShareWorkArgs() interface{} {
	return businessagent.NewWorkShareServicePreviewShareWorkArgs()
}

func newWorkShareServicePreviewShareWorkResult() interface{} {
	return businessagent.NewWorkShareServicePreviewShareWorkResult()
}

func confirmShareWorkHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.WorkShareServiceConfirmShareWorkArgs)
	realResult := result.(*businessagent.WorkShareServiceConfirmShareWorkResult)
	success, err := handler.(businessagent.WorkShareService).ConfirmShareWork(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newWorkShareServiceConfirmShareWorkArgs() interface{} {
	return businessagent.NewWorkShareServiceConfirmShareWorkArgs()
}

func newWorkShareServiceConfirmShareWorkResult() interface{} {
	return businessagent.NewWorkShareServiceConfirmShareWorkResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PreviewShareWork(ctx context.Context, req *businessagent.PreviewShareWorkRequest) (r *businessagent.ShareWorkPreviewDTO, err error) {
	var _args businessagent.WorkShareServicePreviewShareWorkArgs
	_args.Req = req
	var _result businessagent.WorkShareServicePreviewShareWorkResult
	if err = p.c.Call(ctx, "PreviewShareWork", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfirmShareWork(ctx context.Context, req *businessagent.ConfirmShareWorkRequest) (r *businessagent.WorkShareResultDTO, err error) {
	var _args businessagent.WorkShareServiceConfirmShareWorkArgs
	_args.Req = req
	var _result businessagent.WorkShareServiceConfirmShareWorkResult
	if err = p.c.Call(ctx, "ConfirmShareWork", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
