// Code generated by Kitex v0.16.2. DO NOT EDIT.

package featuredworkadminservice

import (
	"context"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PreviewTakeDownWork(ctx context.Context, req *businessagent.PreviewTakeDownPublicWorkRequest, callOptions ...callopt.Option) (r *businessagent.TakeDownPublicWorkPreviewDTO, err error)
	ConfirmTakeDownWork(ctx context.Context, req *businessagent.ConfirmTakeDownPublicWorkRequest, callOptions ...callopt.Option) (r *businessagent.AdminPublicWorkDTO, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kFeaturedWorkAdminServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFeaturedWorkAdminServiceClient struct {
	*kClient
}

func (p *kFeaturedWorkAdminServiceClient) PreviewTakeDownWork(ctx context.Context, req *businessagent.PreviewTakeDownPublicWorkRequest, callOptions ...callopt.Option) (r *businessagent.TakeDownPublicWorkPreviewDTO, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PreviewTakeDownWork(ctx, req)
}

func (p *kFeaturedWorkAdminServiceClient) ConfirmTakeDownWork(ctx context.Context, req *businessagent.ConfirmTakeDownPublicWorkRequest, callOptions ...callopt.Option) (r *businessagent.AdminPublicWorkDTO, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ConfirmTakeDownWork(ctx, req)
}
