// Code generated by Kitex v0.16.2. DO NOT EDIT.

package featuredworkadminservice

import (
	"context"
	"errors"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"PreviewTakeDownWork": kitex.NewMethodInfo(
		previewTakeDownWorkHandler,
		newFeaturedWorkAdminServicePreviewTakeDownWorkArgs,
		newFeaturedWorkAdminServicePreviewTakeDownWorkResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ConfirmTakeDownWork": kitex.NewMethodInfo(
		confirmTakeDownWorkHandler,
		newFeaturedWorkAdminServiceConfirmTakeDownWorkArgs,
		newFeaturedWorkAdminServiceConfirmTakeDownWorkResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	featuredWorkAdminServiceServiceInfo                = NewServiceInfo()
	featuredWorkAdminServiceServiceInfoForClient       = NewServiceInfoForClient()
	featuredWorkAdminServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return featuredWorkAdminServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return featuredWorkAdminServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return featuredWorkAdminServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "FeaturedWorkAdminService"
	handlerType := (*businessagent.FeaturedWorkAdminService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "businessagent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func previewTakeDownWorkHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.FeaturedWorkAdminServicePreviewTakeDownWorkArgs)
	realResult := result.(*businessagent.FeaturedWorkAdminServicePreviewTakeDownWorkResult)
	success, err := handler.(businessagent.FeaturedWorkAdminService).PreviewTakeDownWork(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFeaturedWorkAdminServicePreviewTakeDownWorkArgs() interface{} {
	return businessagent.NewFeaturedWorkAdminServicePreviewTakeDownWorkArgs()
}

func newFeaturedWorkAdminServicePreviewTakeDownWorkResult() interface{} {
	return businessagent.NewFeaturedWorkAdminServicePreviewTakeDownWorkResult()
}

func confirmTakeDownWorkHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.FeaturedWorkAdminServiceConfirmTakeDownWorkArgs)
	realResult := result.(*businessagent.FeaturedWorkAdminServiceConfirmTakeDownWorkResult)
	success, err := handler.(businessagent.FeaturedWorkAdminService).ConfirmTakeDownWork(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFeaturedWorkAdminServiceConfirmTakeDownWorkArgs() interface{} {
	return businessagent.NewFeaturedWorkAdminServiceConfirmTakeDownWorkArgs()
}

func newFeaturedWorkAdminServiceConfirmTakeDownWorkResult() interface{} {
	return businessagent.NewFeaturedWorkAdminServiceConfirmTakeDownWorkResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PreviewTakeDownWork(ctx context.Context, req *businessagent.PreviewTakeDownPublicWorkRequest) (r *businessagent.TakeDownPublicWorkPreviewDTO, err error) {
	var _args businessagent.FeaturedWorkAdminServicePreviewTakeDownWorkArgs
	_args.Req = req
	var _result businessagent.FeaturedWorkAdminServicePreviewTakeDownWorkResult
	if err = p.c.Call(ctx, "PreviewTakeDownWork", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfirmTakeDownWork(ctx context.Context, req *businessagent.ConfirmTakeDownPublicWorkRequest) (r *businessagent.AdminPublicWorkDTO, err error) {
	var _args businessagent.FeaturedWorkAdminServiceConfirmTakeDownWorkArgs
	_args.Req = req
	var _result businessagent.FeaturedWorkAdminServiceConfirmTakeDownWorkResult
	if err = p.c.Call(ctx, "ConfirmTakeDownWork", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
