// Code generated by Kitex v0.16.2. DO NOT EDIT.

package businessfoundationservicev1

import (
	"context"
	"errors"
	foundationv1 "github.com/FigoGoo/Dora-Agent/business/kitex_gen/foundationv1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Probe": kitex.NewMethodInfo(
		probeHandler,
		newBusinessFoundationServiceV1ProbeArgs,
		newBusinessFoundationServiceV1ProbeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	businessFoundationServiceV1ServiceInfo                = NewServiceInfo()
	businessFoundationServiceV1ServiceInfoForClient       = NewServiceInfoForClient()
	businessFoundationServiceV1ServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return businessFoundationServiceV1ServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return businessFoundationServiceV1ServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return businessFoundationServiceV1ServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "BusinessFoundationServiceV1"
	handlerType := (*foundationv1.BusinessFoundationServiceV1)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "foundationv1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func probeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*foundationv1.BusinessFoundationServiceV1ProbeArgs)
	realResult := result.(*foundationv1.BusinessFoundationServiceV1ProbeResult)
	success, err := handler.(foundationv1.BusinessFoundationServiceV1).Probe(ctx, realArg.Request)
	if err != nil {
		switch v := err.(type) {
		case *foundationv1.FoundationServiceExceptionV1:
			realResult.ServiceError = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newBusinessFoundationServiceV1ProbeArgs() interface{} {
	return foundationv1.NewBusinessFoundationServiceV1ProbeArgs()
}

func newBusinessFoundationServiceV1ProbeResult() interface{} {
	return foundationv1.NewBusinessFoundationServiceV1ProbeResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Probe(ctx context.Context, request *foundationv1.FoundationProbeRequestV1) (r *foundationv1.FoundationProbeResponseV1, err error) {
	var _args foundationv1.BusinessFoundationServiceV1ProbeArgs
	_args.Request = request
	var _result foundationv1.BusinessFoundationServiceV1ProbeResult
	if err = p.c.Call(ctx, "Probe", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.ServiceError != nil:
		return r, _result.ServiceError
	}
	return _result.GetSuccess(), nil
}
