// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package foundationv1

import (
	"context"
	"fmt"
)

const (
	FOUNDATION_SCHEMA_VERSION = "foundation.rpc.v1"

	BUSINESS_FOUNDATION_SERVICE_NAME = "dora.business.foundation.v1"
)

type FoundationProbeRequestV1 struct {
	SchemaVersion string `thrift:"schema_version,1,required" frugal:"1,required,string" json:"schema_version"`
	RequestId     string `thrift:"request_id,2,required" frugal:"2,required,string" json:"request_id"`
	CallerService string `thrift:"caller_service,3,required" frugal:"3,required,string" json:"caller_service"`
	CallerVersion string `thrift:"caller_version,4,required" frugal:"4,required,string" json:"caller_version"`
	SentAtUnixMs  int64  `thrift:"sent_at_unix_ms,5,required" frugal:"5,required,i64" json:"sent_at_unix_ms"`
}

func NewFoundationProbeRequestV1() *FoundationProbeRequestV1 {
	return &FoundationProbeRequestV1{}
}

func (p *FoundationProbeRequestV1) InitDefault() {
}

func (p *FoundationProbeRequestV1) GetSchemaVersion() (v string) {
	return p.SchemaVersion
}

func (p *FoundationProbeRequestV1) GetRequestId() (v string) {
	return p.RequestId
}

func (p *FoundationProbeRequestV1) GetCallerService() (v string) {
	return p.CallerService
}

func (p *FoundationProbeRequestV1) GetCallerVersion() (v string) {
	return p.CallerVersion
}

func (p *FoundationProbeRequestV1) GetSentAtUnixMs() (v int64) {
	return p.SentAtUnixMs
}
func (p *FoundationProbeRequestV1) SetSchemaVersion(val string) {
	p.SchemaVersion = val
}
func (p *FoundationProbeRequestV1) SetRequestId(val string) {
	p.RequestId = val
}
func (p *FoundationProbeRequestV1) SetCallerService(val string) {
	p.CallerService = val
}
func (p *FoundationProbeRequestV1) SetCallerVersion(val string) {
	p.CallerVersion = val
}
func (p *FoundationProbeRequestV1) SetSentAtUnixMs(val int64) {
	p.SentAtUnixMs = val
}

func (p *FoundationProbeRequestV1) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FoundationProbeRequestV1(%+v)", *p)
}

var fieldIDToName_FoundationProbeRequestV1 = map[int16]string{
	1: "schema_version",
	2: "request_id",
	3: "caller_service",
	4: "caller_version",
	5: "sent_at_unix_ms",
}

type FoundationProbeResponseV1 struct {
	SchemaVersion    string `thrift:"schema_version,1,required" frugal:"1,required,string" json:"schema_version"`
	RequestId        string `thrift:"request_id,2,required" frugal:"2,required,string" json:"request_id"`
	ServiceName      string `thrift:"service_name,3,required" frugal:"3,required,string" json:"service_name"`
	ServiceVersion   string `thrift:"service_version,4,required" frugal:"4,required,string" json:"service_version"`
	Environment      string `thrift:"environment,5,required" frugal:"5,required,string" json:"environment"`
	InstanceId       string `thrift:"instance_id,6,required" frugal:"6,required,string" json:"instance_id"`
	ReceivedAtUnixMs int64  `thrift:"received_at_unix_ms,7,required" frugal:"7,required,i64" json:"received_at_unix_ms"`
}

func NewFoundationProbeResponseV1() *FoundationProbeResponseV1 {
	return &FoundationProbeResponseV1{}
}

func (p *FoundationProbeResponseV1) InitDefault() {
}

func (p *FoundationProbeResponseV1) GetSchemaVersion() (v string) {
	return p.SchemaVersion
}

func (p *FoundationProbeResponseV1) GetRequestId() (v string) {
	return p.RequestId
}

func (p *FoundationProbeResponseV1) GetServiceName() (v string) {
	return p.ServiceName
}

func (p *FoundationProbeResponseV1) GetServiceVersion() (v string) {
	return p.ServiceVersion
}

func (p *FoundationProbeResponseV1) GetEnvironment() (v string) {
	return p.Environment
}

func (p *FoundationProbeResponseV1) GetInstanceId() (v string) {
	return p.InstanceId
}

func (p *FoundationProbeResponseV1) GetReceivedAtUnixMs() (v int64) {
	return p.ReceivedAtUnixMs
}
func (p *FoundationProbeResponseV1) SetSchemaVersion(val string) {
	p.SchemaVersion = val
}
func (p *FoundationProbeResponseV1) SetRequestId(val string) {
	p.RequestId = val
}
func (p *FoundationProbeResponseV1) SetServiceName(val string) {
	p.ServiceName = val
}
func (p *FoundationProbeResponseV1) SetServiceVersion(val string) {
	p.ServiceVersion = val
}
func (p *FoundationProbeResponseV1) SetEnvironment(val string) {
	p.Environment = val
}
func (p *FoundationProbeResponseV1) SetInstanceId(val string) {
	p.InstanceId = val
}
func (p *FoundationProbeResponseV1) SetReceivedAtUnixMs(val int64) {
	p.ReceivedAtUnixMs = val
}

func (p *FoundationProbeResponseV1) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FoundationProbeResponseV1(%+v)", *p)
}

var fieldIDToName_FoundationProbeResponseV1 = map[int16]string{
	1: "schema_version",
	2: "request_id",
	3: "service_name",
	4: "service_version",
	5: "environment",
	6: "instance_id",
	7: "received_at_unix_ms",
}

type FoundationServiceExceptionV1 struct {
	Code      string `thrift:"code,1,required" frugal:"1,required,string" json:"code"`
	Message   string `thrift:"message,2,required" frugal:"2,required,string" json:"message"`
	Retryable bool   `thrift:"retryable,3,required" frugal:"3,required,bool" json:"retryable"`
}

func NewFoundationServiceExceptionV1() *FoundationServiceExceptionV1 {
	return &FoundationServiceExceptionV1{}
}

func (p *FoundationServiceExceptionV1) InitDefault() {
}

func (p *FoundationServiceExceptionV1) GetCode() (v string) {
	return p.Code
}

func (p *FoundationServiceExceptionV1) GetMessage() (v string) {
	return p.Message
}

func (p *FoundationServiceExceptionV1) GetRetryable() (v bool) {
	return p.Retryable
}
func (p *FoundationServiceExceptionV1) SetCode(val string) {
	p.Code = val
}
func (p *FoundationServiceExceptionV1) SetMessage(val string) {
	p.Message = val
}
func (p *FoundationServiceExceptionV1) SetRetryable(val bool) {
	p.Retryable = val
}

func (p *FoundationServiceExceptionV1) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FoundationServiceExceptionV1(%+v)", *p)
}
func (p *FoundationServiceExceptionV1) Error() string {
	return p.String()
}

var fieldIDToName_FoundationServiceExceptionV1 = map[int16]string{
	1: "code",
	2: "message",
	3: "retryable",
}

type BusinessFoundationServiceV1 interface {
	Probe(ctx context.Context, request *FoundationProbeRequestV1) (r *FoundationProbeResponseV1, err error)
}

type BusinessFoundationServiceV1ProbeArgs struct {
	Request *FoundationProbeRequestV1 `thrift:"request,1" frugal:"1,default,FoundationProbeRequestV1" json:"request"`
}

func NewBusinessFoundationServiceV1ProbeArgs() *BusinessFoundationServiceV1ProbeArgs {
	return &BusinessFoundationServiceV1ProbeArgs{}
}

func (p *BusinessFoundationServiceV1ProbeArgs) InitDefault() {
}

var BusinessFoundationServiceV1ProbeArgs_Request_DEFAULT *FoundationProbeRequestV1

func (p *BusinessFoundationServiceV1ProbeArgs) GetRequest() (v *FoundationProbeRequestV1) {
	if !p.IsSetRequest() {
		return BusinessFoundationServiceV1ProbeArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *BusinessFoundationServiceV1ProbeArgs) SetRequest(val *FoundationProbeRequestV1) {
	p.Request = val
}

func (p *BusinessFoundationServiceV1ProbeArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *BusinessFoundationServiceV1ProbeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessFoundationServiceV1ProbeArgs(%+v)", *p)
}

var fieldIDToName_BusinessFoundationServiceV1ProbeArgs = map[int16]string{
	1: "request",
}

type BusinessFoundationServiceV1ProbeResult struct {
	Success      *FoundationProbeResponseV1    `thrift:"success,0,optional" frugal:"0,optional,FoundationProbeResponseV1" json:"success,omitempty"`
	ServiceError *FoundationServiceExceptionV1 `thrift:"service_error,1,optional" frugal:"1,optional,FoundationServiceExceptionV1" json:"service_error,omitempty"`
}

func NewBusinessFoundationServiceV1ProbeResult() *BusinessFoundationServiceV1ProbeResult {
	return &BusinessFoundationServiceV1ProbeResult{}
}

func (p *BusinessFoundationServiceV1ProbeResult) InitDefault() {
}

var BusinessFoundationServiceV1ProbeResult_Success_DEFAULT *FoundationProbeResponseV1

func (p *BusinessFoundationServiceV1ProbeResult) GetSuccess() (v *FoundationProbeResponseV1) {
	if !p.IsSetSuccess() {
		return BusinessFoundationServiceV1ProbeResult_Success_DEFAULT
	}
	return p.Success
}

var BusinessFoundationServiceV1ProbeResult_ServiceError_DEFAULT *FoundationServiceExceptionV1

func (p *BusinessFoundationServiceV1ProbeResult) GetServiceError() (v *FoundationServiceExceptionV1) {
	if !p.IsSetServiceError() {
		return BusinessFoundationServiceV1ProbeResult_ServiceError_DEFAULT
	}
	return p.ServiceError
}
func (p *BusinessFoundationServiceV1ProbeResult) SetSuccess(x interface{}) {
	p.Success = x.(*FoundationProbeResponseV1)
}
func (p *BusinessFoundationServiceV1ProbeResult) SetServiceError(val *FoundationServiceExceptionV1) {
	p.ServiceError = val
}

func (p *BusinessFoundationServiceV1ProbeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BusinessFoundationServiceV1ProbeResult) IsSetServiceError() bool {
	return p.ServiceError != nil
}

func (p *BusinessFoundationServiceV1ProbeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BusinessFoundationServiceV1ProbeResult(%+v)", *p)
}

var fieldIDToName_BusinessFoundationServiceV1ProbeResult = map[int16]string{
	0: "success",
	1: "service_error",
}

// exceptions of methods in BusinessFoundationServiceV1.
var (
	_ error = (*FoundationServiceExceptionV1)(nil)
)
