// Code generated by Kitex v0.16.2. DO NOT EDIT.

package workservice

import (
	"context"
	"errors"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateWork": kitex.NewMethodInfo(
		createWorkHandler,
		newWorkServiceCreateWorkArgs,
		newWorkServiceCreateWorkResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	workServiceServiceInfo                = NewServiceInfo()
	workServiceServiceInfoForClient       = NewServiceInfoForClient()
	workServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return workServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return workServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return workServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "WorkService"
	handlerType := (*businessagent.WorkService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "businessagent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func createWorkHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.WorkServiceCreateWorkArgs)
	realResult := result.(*businessagent.WorkServiceCreateWorkResult)
	success, err := handler.(businessagent.WorkService).CreateWork(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newWorkServiceCreateWorkArgs() interface{} {
	return businessagent.NewWorkServiceCreateWorkArgs()
}

func newWorkServiceCreateWorkResult() interface{} {
	return businessagent.NewWorkServiceCreateWorkResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateWork(ctx context.Context, req *businessagent.CreateWorkRequest) (r *businessagent.WorkDetailDTO, err error) {
	var _args businessagent.WorkServiceCreateWorkArgs
	_args.Req = req
	var _result businessagent.WorkServiceCreateWorkResult
	if err = p.c.Call(ctx, "CreateWork", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
