// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package sessionv1

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
)

const (
	SESSION_RPC_SCHEMA_VERSION = "session.rpc.v1"

	ENSURE_PROJECT_SESSION_SCHEMA_VERSION = "ensure_project_session.v1"

	QUERY_PROJECT_SESSION_COMMAND_SCHEMA_VERSION = "query_project_session_command.v1"

	AGENT_SESSION_SERVICE_NAME = "dora.agent.session.v1"
)

type CreationSourceV1 int64

const (
	CreationSourceV1_QUICK_CREATE CreationSourceV1 = 1
)

func (p CreationSourceV1) String() string {
	switch p {
	case CreationSourceV1_QUICK_CREATE:
		return "QUICK_CREATE"
	}
	return "<UNSET>"
}

func CreationSourceV1FromString(s string) (CreationSourceV1, error) {
	switch s {
	case "QUICK_CREATE":
		return CreationSourceV1_QUICK_CREATE, nil
	}
	return CreationSourceV1(0), fmt.Errorf("not a valid CreationSourceV1 string")
}

func CreationSourceV1Ptr(v CreationSourceV1) *CreationSourceV1 { return &v }
func (p *CreationSourceV1) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = CreationSourceV1(result.Int64)
	return
}

func (p *CreationSourceV1) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type SkillSnapshotModeV1 int64

const (
	SkillSnapshotModeV1_EMPTY SkillSnapshotModeV1 = 1
)

func (p SkillSnapshotModeV1) String() string {
	switch p {
	case SkillSnapshotModeV1_EMPTY:
		return "EMPTY"
	}
	return "<UNSET>"
}

func SkillSnapshotModeV1FromString(s string) (SkillSnapshotModeV1, error) {
	switch s {
	case "EMPTY":
		return SkillSnapshotModeV1_EMPTY, nil
	}
	return SkillSnapshotModeV1(0), fmt.Errorf("not a valid SkillSnapshotModeV1 string")
}

func SkillSnapshotModeV1Ptr(v SkillSnapshotModeV1) *SkillSnapshotModeV1 { return &v }
func (p *SkillSnapshotModeV1) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = SkillSnapshotModeV1(result.Int64)
	return
}

func (p *SkillSnapshotModeV1) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type EnsureDispositionV1 int64

const (
	EnsureDispositionV1_CREATED  EnsureDispositionV1 = 1
	EnsureDispositionV1_REPLAYED EnsureDispositionV1 = 2
)

func (p EnsureDispositionV1) String() string {
	switch p {
	case EnsureDispositionV1_CREATED:
		return "CREATED"
	case EnsureDispositionV1_REPLAYED:
		return "REPLAYED"
	}
	return "<UNSET>"
}

func EnsureDispositionV1FromString(s string) (EnsureDispositionV1, error) {
	switch s {
	case "CREATED":
		return EnsureDispositionV1_CREATED, nil
	case "REPLAYED":
		return EnsureDispositionV1_REPLAYED, nil
	}
	return EnsureDispositionV1(0), fmt.Errorf("not a valid EnsureDispositionV1 string")
}

func EnsureDispositionV1Ptr(v EnsureDispositionV1) *EnsureDispositionV1 { return &v }
func (p *EnsureDispositionV1) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = EnsureDispositionV1(result.Int64)
	return
}

func (p *EnsureDispositionV1) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type QueryProjectSessionCommandStatusV1 int64

const (
	QueryProjectSessionCommandStatusV1_NOT_FOUND QueryProjectSessionCommandStatusV1 = 1
	QueryProjectSessionCommandStatusV1_COMPLETED QueryProjectSessionCommandStatusV1 = 2
	QueryProjectSessionCommandStatusV1_CONFLICT  QueryProjectSessionCommandStatusV1 = 3
)

func (p QueryProjectSessionCommandStatusV1) String() string {
	switch p {
	case QueryProjectSessionCommandStatusV1_NOT_FOUND:
		return "NOT_FOUND"
	case QueryProjectSessionCommandStatusV1_COMPLETED:
		return "COMPLETED"
	case QueryProjectSessionCommandStatusV1_CONFLICT:
		return "CONFLICT"
	}
	return "<UNSET>"
}

func QueryProjectSessionCommandStatusV1FromString(s string) (QueryProjectSessionCommandStatusV1, error) {
	switch s {
	case "NOT_FOUND":
		return QueryProjectSessionCommandStatusV1_NOT_FOUND, nil
	case "COMPLETED":
		return QueryProjectSessionCommandStatusV1_COMPLETED, nil
	case "CONFLICT":
		return QueryProjectSessionCommandStatusV1_CONFLICT, nil
	}
	return QueryProjectSessionCommandStatusV1(0), fmt.Errorf("not a valid QueryProjectSessionCommandStatusV1 string")
}

func QueryProjectSessionCommandStatusV1Ptr(v QueryProjectSessionCommandStatusV1) *QueryProjectSessionCommandStatusV1 {
	return &v
}
func (p *QueryProjectSessionCommandStatusV1) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = QueryProjectSessionCommandStatusV1(result.Int64)
	return
}

func (p *QueryProjectSessionCommandStatusV1) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type EnsureProjectSessionRequestV1 struct {
	SchemaVersion     string              `thrift:"schema_version,1,required" frugal:"1,required,string" json:"schema_version"`
	RequestId         string              `thrift:"request_id,2,required" frugal:"2,required,string" json:"request_id"`
	CommandId         string              `thrift:"command_id,3,required" frugal:"3,required,string" json:"command_id"`
	RequestDigest     string              `thrift:"request_digest,4,required" frugal:"4,required,string" json:"request_digest"`
	ProjectId         string              `thrift:"project_id,5,required" frugal:"5,required,string" json:"project_id"`
	OwnerUserId       string              `thrift:"owner_user_id,6,required" frugal:"6,required,string" json:"owner_user_id"`
	CreationSource    CreationSourceV1    `thrift:"creation_source,7,required" frugal:"7,required,CreationSourceV1" json:"creation_source"`
	InitialPrompt     *string             `thrift:"initial_prompt,8,optional" frugal:"8,optional,string" json:"initial_prompt,omitempty"`
	PromptDigest      string              `thrift:"prompt_digest,9,required" frugal:"9,required,string" json:"prompt_digest"`
	SkillSnapshotMode SkillSnapshotModeV1 `thrift:"skill_snapshot_mode,10,required" frugal:"10,required,SkillSnapshotModeV1" json:"skill_snapshot_mode"`
	RequestedAtUnixMs int64               `thrift:"requested_at_unix_ms,11,required" frugal:"11,required,i64" json:"requested_at_unix_ms"`
}

func NewEnsureProjectSessionRequestV1() *EnsureProjectSessionRequestV1 {
	return &EnsureProjectSessionRequestV1{}
}

func (p *EnsureProjectSessionRequestV1) InitDefault() {
}

func (p *EnsureProjectSessionRequestV1) GetSchemaVersion() (v string) {
	return p.SchemaVersion
}

func (p *EnsureProjectSessionRequestV1) GetRequestId() (v string) {
	return p.RequestId
}

func (p *EnsureProjectSessionRequestV1) GetCommandId() (v string) {
	return p.CommandId
}

func (p *EnsureProjectSessionRequestV1) GetRequestDigest() (v string) {
	return p.RequestDigest
}

func (p *EnsureProjectSessionRequestV1) GetProjectId() (v string) {
	return p.ProjectId
}

func (p *EnsureProjectSessionRequestV1) GetOwnerUserId() (v string) {
	return p.OwnerUserId
}

func (p *EnsureProjectSessionRequestV1) GetCreationSource() (v CreationSourceV1) {
	return p.CreationSource
}

var EnsureProjectSessionRequestV1_InitialPrompt_DEFAULT string

func (p *EnsureProjectSessionRequestV1) GetInitialPrompt() (v string) {
	if !p.IsSetInitialPrompt() {
		return EnsureProjectSessionRequestV1_InitialPrompt_DEFAULT
	}
	return *p.InitialPrompt
}

func (p *EnsureProjectSessionRequestV1) GetPromptDigest() (v string) {
	return p.PromptDigest
}

func (p *EnsureProjectSessionRequestV1) GetSkillSnapshotMode() (v SkillSnapshotModeV1) {
	return p.SkillSnapshotMode
}

func (p *EnsureProjectSessionRequestV1) GetRequestedAtUnixMs() (v int64) {
	return p.RequestedAtUnixMs
}
func (p *EnsureProjectSessionRequestV1) SetSchemaVersion(val string) {
	p.SchemaVersion = val
}
func (p *EnsureProjectSessionRequestV1) SetRequestId(val string) {
	p.RequestId = val
}
func (p *EnsureProjectSessionRequestV1) SetCommandId(val string) {
	p.CommandId = val
}
func (p *EnsureProjectSessionRequestV1) SetRequestDigest(val string) {
	p.RequestDigest = val
}
func (p *EnsureProjectSessionRequestV1) SetProjectId(val string) {
	p.ProjectId = val
}
func (p *EnsureProjectSessionRequestV1) SetOwnerUserId(val string) {
	p.OwnerUserId = val
}
func (p *EnsureProjectSessionRequestV1) SetCreationSource(val CreationSourceV1) {
	p.CreationSource = val
}
func (p *EnsureProjectSessionRequestV1) SetInitialPrompt(val *string) {
	p.InitialPrompt = val
}
func (p *EnsureProjectSessionRequestV1) SetPromptDigest(val string) {
	p.PromptDigest = val
}
func (p *EnsureProjectSessionRequestV1) SetSkillSnapshotMode(val SkillSnapshotModeV1) {
	p.SkillSnapshotMode = val
}
func (p *EnsureProjectSessionRequestV1) SetRequestedAtUnixMs(val int64) {
	p.RequestedAtUnixMs = val
}

func (p *EnsureProjectSessionRequestV1) IsSetInitialPrompt() bool {
	return p.InitialPrompt != nil
}

func (p *EnsureProjectSessionRequestV1) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EnsureProjectSessionRequestV1(%+v)", *p)
}

var fieldIDToName_EnsureProjectSessionRequestV1 = map[int16]string{
	1:  "schema_version",
	2:  "request_id",
	3:  "command_id",
	4:  "request_digest",
	5:  "project_id",
	6:  "owner_user_id",
	7:  "creation_source",
	8:  "initial_prompt",
	9:  "prompt_digest",
	10: "skill_snapshot_mode",
	11: "requested_at_unix_ms",
}

type ProjectSessionReceiptV1 struct {
	CommandId         string  `thrift:"command_id,1,required" frugal:"1,required,string" json:"command_id"`
	SessionId         string  `thrift:"session_id,2,required" frugal:"2,required,string" json:"session_id"`
	MessageId         *string `thrift:"message_id,3,optional" frugal:"3,optional,string" json:"message_id,omitempty"`
	InputId           *string `thrift:"input_id,4,optional" frugal:"4,optional,string" json:"input_id,omitempty"`
	ResultVersion     int32   `thrift:"result_version,5,required" frugal:"5,required,i32" json:"result_version"`
	CompletedAtUnixMs int64   `thrift:"completed_at_unix_ms,6,required" frugal:"6,required,i64" json:"completed_at_unix_ms"`
}

func NewProjectSessionReceiptV1() *ProjectSessionReceiptV1 {
	return &ProjectSessionReceiptV1{}
}

func (p *ProjectSessionReceiptV1) InitDefault() {
}

func (p *ProjectSessionReceiptV1) GetCommandId() (v string) {
	return p.CommandId
}

func (p *ProjectSessionReceiptV1) GetSessionId() (v string) {
	return p.SessionId
}

var ProjectSessionReceiptV1_MessageId_DEFAULT string

func (p *ProjectSessionReceiptV1) GetMessageId() (v string) {
	if !p.IsSetMessageId() {
		return ProjectSessionReceiptV1_MessageId_DEFAULT
	}
	return *p.MessageId
}

var ProjectSessionReceiptV1_InputId_DEFAULT string

func (p *ProjectSessionReceiptV1) GetInputId() (v string) {
	if !p.IsSetInputId() {
		return ProjectSessionReceiptV1_InputId_DEFAULT
	}
	return *p.InputId
}

func (p *ProjectSessionReceiptV1) GetResultVersion() (v int32) {
	return p.ResultVersion
}

func (p *ProjectSessionReceiptV1) GetCompletedAtUnixMs() (v int64) {
	return p.CompletedAtUnixMs
}
func (p *ProjectSessionReceiptV1) SetCommandId(val string) {
	p.CommandId = val
}
func (p *ProjectSessionReceiptV1) SetSessionId(val string) {
	p.SessionId = val
}
func (p *ProjectSessionReceiptV1) SetMessageId(val *string) {
	p.MessageId = val
}
func (p *ProjectSessionReceiptV1) SetInputId(val *string) {
	p.InputId = val
}
func (p *ProjectSessionReceiptV1) SetResultVersion(val int32) {
	p.ResultVersion = val
}
func (p *ProjectSessionReceiptV1) SetCompletedAtUnixMs(val int64) {
	p.CompletedAtUnixMs = val
}

func (p *ProjectSessionReceiptV1) IsSetMessageId() bool {
	return p.MessageId != nil
}

func (p *ProjectSessionReceiptV1) IsSetInputId() bool {
	return p.InputId != nil
}

func (p *ProjectSessionReceiptV1) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProjectSessionReceiptV1(%+v)", *p)
}

var fieldIDToName_ProjectSessionReceiptV1 = map[int16]string{
	1: "command_id",
	2: "session_id",
	3: "message_id",
	4: "input_id",
	5: "result_version",
	6: "completed_at_unix_ms",
}

type EnsureProjectSessionResponseV1 struct {
	SchemaVersion string                   `thrift:"schema_version,1,required" frugal:"1,required,string" json:"schema_version"`
	RequestId     string                   `thrift:"request_id,2,required" frugal:"2,required,string" json:"request_id"`
	Disposition   EnsureDispositionV1      `thrift:"disposition,3,required" frugal:"3,required,EnsureDispositionV1" json:"disposition"`
	Receipt       *ProjectSessionReceiptV1 `thrift:"receipt,4,required" frugal:"4,required,ProjectSessionReceiptV1" json:"receipt"`
}

func NewEnsureProjectSessionResponseV1() *EnsureProjectSessionResponseV1 {
	return &EnsureProjectSessionResponseV1{}
}

func (p *EnsureProjectSessionResponseV1) InitDefault() {
}

func (p *EnsureProjectSessionResponseV1) GetSchemaVersion() (v string) {
	return p.SchemaVersion
}

func (p *EnsureProjectSessionResponseV1) GetRequestId() (v string) {
	return p.RequestId
}

func (p *EnsureProjectSessionResponseV1) GetDisposition() (v EnsureDispositionV1) {
	return p.Disposition
}

var EnsureProjectSessionResponseV1_Receipt_DEFAULT *ProjectSessionReceiptV1

func (p *EnsureProjectSessionResponseV1) GetReceipt() (v *ProjectSessionReceiptV1) {
	if !p.IsSetReceipt() {
		return EnsureProjectSessionResponseV1_Receipt_DEFAULT
	}
	return p.Receipt
}
func (p *EnsureProjectSessionResponseV1) SetSchemaVersion(val string) {
	p.SchemaVersion = val
}
func (p *EnsureProjectSessionResponseV1) SetRequestId(val string) {
	p.RequestId = val
}
func (p *EnsureProjectSessionResponseV1) SetDisposition(val EnsureDispositionV1) {
	p.Disposition = val
}
func (p *EnsureProjectSessionResponseV1) SetReceipt(val *ProjectSessionReceiptV1) {
	p.Receipt = val
}

func (p *EnsureProjectSessionResponseV1) IsSetReceipt() bool {
	return p.Receipt != nil
}

func (p *EnsureProjectSessionResponseV1) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EnsureProjectSessionResponseV1(%+v)", *p)
}

var fieldIDToName_EnsureProjectSessionResponseV1 = map[int16]string{
	1: "schema_version",
	2: "request_id",
	3: "disposition",
	4: "receipt",
}

type QueryProjectSessionCommandRequestV1 struct {
	SchemaVersion         string `thrift:"schema_version,1,required" frugal:"1,required,string" json:"schema_version"`
	RequestId             string `thrift:"request_id,2,required" frugal:"2,required,string" json:"request_id"`
	CommandId             string `thrift:"command_id,3,required" frugal:"3,required,string" json:"command_id"`
	ExpectedRequestDigest string `thrift:"expected_request_digest,4,required" frugal:"4,required,string" json:"expected_request_digest"`
}

func NewQueryProjectSessionCommandRequestV1() *QueryProjectSessionCommandRequestV1 {
	return &QueryProjectSessionCommandRequestV1{}
}

func (p *QueryProjectSessionCommandRequestV1) InitDefault() {
}

func (p *QueryProjectSessionCommandRequestV1) GetSchemaVersion() (v string) {
	return p.SchemaVersion
}

func (p *QueryProjectSessionCommandRequestV1) GetRequestId() (v string) {
	return p.RequestId
}

func (p *QueryProjectSessionCommandRequestV1) GetCommandId() (v string) {
	return p.CommandId
}

func (p *QueryProjectSessionCommandRequestV1) GetExpectedRequestDigest() (v string) {
	return p.ExpectedRequestDigest
}
func (p *QueryProjectSessionCommandRequestV1) SetSchemaVersion(val string) {
	p.SchemaVersion = val
}
func (p *QueryProjectSessionCommandRequestV1) SetRequestId(val string) {
	p.RequestId = val
}
func (p *QueryProjectSessionCommandRequestV1) SetCommandId(val string) {
	p.CommandId = val
}
func (p *QueryProjectSessionCommandRequestV1) SetExpectedRequestDigest(val string) {
	p.ExpectedRequestDigest = val
}

func (p *QueryProjectSessionCommandRequestV1) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryProjectSessionCommandRequestV1(%+v)", *p)
}

var fieldIDToName_QueryProjectSessionCommandRequestV1 = map[int16]string{
	1: "schema_version",
	2: "request_id",
	3: "command_id",
	4: "expected_request_digest",
}

type QueryProjectSessionCommandResponseV1 struct {
	SchemaVersion string                             `thrift:"schema_version,1,required" frugal:"1,required,string" json:"schema_version"`
	RequestId     string                             `thrift:"request_id,2,required" frugal:"2,required,string" json:"request_id"`
	Status        QueryProjectSessionCommandStatusV1 `thrift:"status,3,required" frugal:"3,required,QueryProjectSessionCommandStatusV1" json:"status"`
	Receipt       *ProjectSessionReceiptV1           `thrift:"receipt,4,optional" frugal:"4,optional,ProjectSessionReceiptV1" json:"receipt,omitempty"`
}

func NewQueryProjectSessionCommandResponseV1() *QueryProjectSessionCommandResponseV1 {
	return &QueryProjectSessionCommandResponseV1{}
}

func (p *QueryProjectSessionCommandResponseV1) InitDefault() {
}

func (p *QueryProjectSessionCommandResponseV1) GetSchemaVersion() (v string) {
	return p.SchemaVersion
}

func (p *QueryProjectSessionCommandResponseV1) GetRequestId() (v string) {
	return p.RequestId
}

func (p *QueryProjectSessionCommandResponseV1) GetStatus() (v QueryProjectSessionCommandStatusV1) {
	return p.Status
}

var QueryProjectSessionCommandResponseV1_Receipt_DEFAULT *ProjectSessionReceiptV1

func (p *QueryProjectSessionCommandResponseV1) GetReceipt() (v *ProjectSessionReceiptV1) {
	if !p.IsSetReceipt() {
		return QueryProjectSessionCommandResponseV1_Receipt_DEFAULT
	}
	return p.Receipt
}
func (p *QueryProjectSessionCommandResponseV1) SetSchemaVersion(val string) {
	p.SchemaVersion = val
}
func (p *QueryProjectSessionCommandResponseV1) SetRequestId(val string) {
	p.RequestId = val
}
func (p *QueryProjectSessionCommandResponseV1) SetStatus(val QueryProjectSessionCommandStatusV1) {
	p.Status = val
}
func (p *QueryProjectSessionCommandResponseV1) SetReceipt(val *ProjectSessionReceiptV1) {
	p.Receipt = val
}

func (p *QueryProjectSessionCommandResponseV1) IsSetReceipt() bool {
	return p.Receipt != nil
}

func (p *QueryProjectSessionCommandResponseV1) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryProjectSessionCommandResponseV1(%+v)", *p)
}

var fieldIDToName_QueryProjectSessionCommandResponseV1 = map[int16]string{
	1: "schema_version",
	2: "request_id",
	3: "status",
	4: "receipt",
}

type SessionServiceExceptionV1 struct {
	Code      string `thrift:"code,1,required" frugal:"1,required,string" json:"code"`
	Message   string `thrift:"message,2,required" frugal:"2,required,string" json:"message"`
	Retryable bool   `thrift:"retryable,3,required" frugal:"3,required,bool" json:"retryable"`
	RequestId string `thrift:"request_id,4,required" frugal:"4,required,string" json:"request_id"`
}

func NewSessionServiceExceptionV1() *SessionServiceExceptionV1 {
	return &SessionServiceExceptionV1{}
}

func (p *SessionServiceExceptionV1) InitDefault() {
}

func (p *SessionServiceExceptionV1) GetCode() (v string) {
	return p.Code
}

func (p *SessionServiceExceptionV1) GetMessage() (v string) {
	return p.Message
}

func (p *SessionServiceExceptionV1) GetRetryable() (v bool) {
	return p.Retryable
}

func (p *SessionServiceExceptionV1) GetRequestId() (v string) {
	return p.RequestId
}
func (p *SessionServiceExceptionV1) SetCode(val string) {
	p.Code = val
}
func (p *SessionServiceExceptionV1) SetMessage(val string) {
	p.Message = val
}
func (p *SessionServiceExceptionV1) SetRetryable(val bool) {
	p.Retryable = val
}
func (p *SessionServiceExceptionV1) SetRequestId(val string) {
	p.RequestId = val
}

func (p *SessionServiceExceptionV1) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SessionServiceExceptionV1(%+v)", *p)
}
func (p *SessionServiceExceptionV1) Error() string {
	return p.String()
}

var fieldIDToName_SessionServiceExceptionV1 = map[int16]string{
	1: "code",
	2: "message",
	3: "retryable",
	4: "request_id",
}

type AgentSessionServiceV1 interface {
	EnsureProjectSessionV1(ctx context.Context, request *EnsureProjectSessionRequestV1) (r *EnsureProjectSessionResponseV1, err error)

	QueryProjectSessionCommandV1(ctx context.Context, request *QueryProjectSessionCommandRequestV1) (r *QueryProjectSessionCommandResponseV1, err error)
}

type AgentSessionServiceV1EnsureProjectSessionV1Args struct {
	Request *EnsureProjectSessionRequestV1 `thrift:"request,1" frugal:"1,default,EnsureProjectSessionRequestV1" json:"request"`
}

func NewAgentSessionServiceV1EnsureProjectSessionV1Args() *AgentSessionServiceV1EnsureProjectSessionV1Args {
	return &AgentSessionServiceV1EnsureProjectSessionV1Args{}
}

func (p *AgentSessionServiceV1EnsureProjectSessionV1Args) InitDefault() {
}

var AgentSessionServiceV1EnsureProjectSessionV1Args_Request_DEFAULT *EnsureProjectSessionRequestV1

func (p *AgentSessionServiceV1EnsureProjectSessionV1Args) GetRequest() (v *EnsureProjectSessionRequestV1) {
	if !p.IsSetRequest() {
		return AgentSessionServiceV1EnsureProjectSessionV1Args_Request_DEFAULT
	}
	return p.Request
}
func (p *AgentSessionServiceV1EnsureProjectSessionV1Args) SetRequest(val *EnsureProjectSessionRequestV1) {
	p.Request = val
}

func (p *AgentSessionServiceV1EnsureProjectSessionV1Args) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AgentSessionServiceV1EnsureProjectSessionV1Args) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AgentSessionServiceV1EnsureProjectSessionV1Args(%+v)", *p)
}

var fieldIDToName_AgentSessionServiceV1EnsureProjectSessionV1Args = map[int16]string{
	1: "request",
}

type AgentSessionServiceV1EnsureProjectSessionV1Result struct {
	Success      *EnsureProjectSessionResponseV1 `thrift:"success,0,optional" frugal:"0,optional,EnsureProjectSessionResponseV1" json:"success,omitempty"`
	ServiceError *SessionServiceExceptionV1      `thrift:"service_error,1,optional" frugal:"1,optional,SessionServiceExceptionV1" json:"service_error,omitempty"`
}

func NewAgentSessionServiceV1EnsureProjectSessionV1Result() *AgentSessionServiceV1EnsureProjectSessionV1Result {
	return &AgentSessionServiceV1EnsureProjectSessionV1Result{}
}

func (p *AgentSessionServiceV1EnsureProjectSessionV1Result) InitDefault() {
}

var AgentSessionServiceV1EnsureProjectSessionV1Result_Success_DEFAULT *EnsureProjectSessionResponseV1

func (p *AgentSessionServiceV1EnsureProjectSessionV1Result) GetSuccess() (v *EnsureProjectSessionResponseV1) {
	if !p.IsSetSuccess() {
		return AgentSessionServiceV1EnsureProjectSessionV1Result_Success_DEFAULT
	}
	return p.Success
}

var AgentSessionServiceV1EnsureProjectSessionV1Result_ServiceError_DEFAULT *SessionServiceExceptionV1

func (p *AgentSessionServiceV1EnsureProjectSessionV1Result) GetServiceError() (v *SessionServiceExceptionV1) {
	if !p.IsSetServiceError() {
		return AgentSessionServiceV1EnsureProjectSessionV1Result_ServiceError_DEFAULT
	}
	return p.ServiceError
}
func (p *AgentSessionServiceV1EnsureProjectSessionV1Result) SetSuccess(x interface{}) {
	p.Success = x.(*EnsureProjectSessionResponseV1)
}
func (p *AgentSessionServiceV1EnsureProjectSessionV1Result) SetServiceError(val *SessionServiceExceptionV1) {
	p.ServiceError = val
}

func (p *AgentSessionServiceV1EnsureProjectSessionV1Result) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AgentSessionServiceV1EnsureProjectSessionV1Result) IsSetServiceError() bool {
	return p.ServiceError != nil
}

func (p *AgentSessionServiceV1EnsureProjectSessionV1Result) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AgentSessionServiceV1EnsureProjectSessionV1Result(%+v)", *p)
}

var fieldIDToName_AgentSessionServiceV1EnsureProjectSessionV1Result = map[int16]string{
	0: "success",
	1: "service_error",
}

type AgentSessionServiceV1QueryProjectSessionCommandV1Args struct {
	Request *QueryProjectSessionCommandRequestV1 `thrift:"request,1" frugal:"1,default,QueryProjectSessionCommandRequestV1" json:"request"`
}

func NewAgentSessionServiceV1QueryProjectSessionCommandV1Args() *AgentSessionServiceV1QueryProjectSessionCommandV1Args {
	return &AgentSessionServiceV1QueryProjectSessionCommandV1Args{}
}

func (p *AgentSessionServiceV1QueryProjectSessionCommandV1Args) InitDefault() {
}

var AgentSessionServiceV1QueryProjectSessionCommandV1Args_Request_DEFAULT *QueryProjectSessionCommandRequestV1

func (p *AgentSessionServiceV1QueryProjectSessionCommandV1Args) GetRequest() (v *QueryProjectSessionCommandRequestV1) {
	if !p.IsSetRequest() {
		return AgentSessionServiceV1QueryProjectSessionCommandV1Args_Request_DEFAULT
	}
	return p.Request
}
func (p *AgentSessionServiceV1QueryProjectSessionCommandV1Args) SetRequest(val *QueryProjectSessionCommandRequestV1) {
	p.Request = val
}

func (p *AgentSessionServiceV1QueryProjectSessionCommandV1Args) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AgentSessionServiceV1QueryProjectSessionCommandV1Args) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AgentSessionServiceV1QueryProjectSessionCommandV1Args(%+v)", *p)
}

var fieldIDToName_AgentSessionServiceV1QueryProjectSessionCommandV1Args = map[int16]string{
	1: "request",
}

type AgentSessionServiceV1QueryProjectSessionCommandV1Result struct {
	Success      *QueryProjectSessionCommandResponseV1 `thrift:"success,0,optional" frugal:"0,optional,QueryProjectSessionCommandResponseV1" json:"success,omitempty"`
	ServiceError *SessionServiceExceptionV1            `thrift:"service_error,1,optional" frugal:"1,optional,SessionServiceExceptionV1" json:"service_error,omitempty"`
}

func NewAgentSessionServiceV1QueryProjectSessionCommandV1Result() *AgentSessionServiceV1QueryProjectSessionCommandV1Result {
	return &AgentSessionServiceV1QueryProjectSessionCommandV1Result{}
}

func (p *AgentSessionServiceV1QueryProjectSessionCommandV1Result) InitDefault() {
}

var AgentSessionServiceV1QueryProjectSessionCommandV1Result_Success_DEFAULT *QueryProjectSessionCommandResponseV1

func (p *AgentSessionServiceV1QueryProjectSessionCommandV1Result) GetSuccess() (v *QueryProjectSessionCommandResponseV1) {
	if !p.IsSetSuccess() {
		return AgentSessionServiceV1QueryProjectSessionCommandV1Result_Success_DEFAULT
	}
	return p.Success
}

var AgentSessionServiceV1QueryProjectSessionCommandV1Result_ServiceError_DEFAULT *SessionServiceExceptionV1

func (p *AgentSessionServiceV1QueryProjectSessionCommandV1Result) GetServiceError() (v *SessionServiceExceptionV1) {
	if !p.IsSetServiceError() {
		return AgentSessionServiceV1QueryProjectSessionCommandV1Result_ServiceError_DEFAULT
	}
	return p.ServiceError
}
func (p *AgentSessionServiceV1QueryProjectSessionCommandV1Result) SetSuccess(x interface{}) {
	p.Success = x.(*QueryProjectSessionCommandResponseV1)
}
func (p *AgentSessionServiceV1QueryProjectSessionCommandV1Result) SetServiceError(val *SessionServiceExceptionV1) {
	p.ServiceError = val
}

func (p *AgentSessionServiceV1QueryProjectSessionCommandV1Result) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AgentSessionServiceV1QueryProjectSessionCommandV1Result) IsSetServiceError() bool {
	return p.ServiceError != nil
}

func (p *AgentSessionServiceV1QueryProjectSessionCommandV1Result) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AgentSessionServiceV1QueryProjectSessionCommandV1Result(%+v)", *p)
}

var fieldIDToName_AgentSessionServiceV1QueryProjectSessionCommandV1Result = map[int16]string{
	0: "success",
	1: "service_error",
}

// exceptions of methods in AgentSessionServiceV1.
var (
	_ error = (*SessionServiceExceptionV1)(nil)
)
