// Code generated by Kitex v0.16.2. DO NOT EDIT.

package agentsessionservicev1

import (
	"context"
	sessionv1 "github.com/FigoGoo/Dora-Agent/business/kitex_gen/sessionv1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	EnsureProjectSessionV1(ctx context.Context, request *sessionv1.EnsureProjectSessionRequestV1, callOptions ...callopt.Option) (r *sessionv1.EnsureProjectSessionResponseV1, err error)
	QueryProjectSessionCommandV1(ctx context.Context, request *sessionv1.QueryProjectSessionCommandRequestV1, callOptions ...callopt.Option) (r *sessionv1.QueryProjectSessionCommandResponseV1, err error)
	EnsureProjectSessionV2(ctx context.Context, request *sessionv1.EnsureProjectSessionRequestV2, callOptions ...callopt.Option) (r *sessionv1.EnsureProjectSessionResponseV2, err error)
	QueryProjectSessionCommandV2(ctx context.Context, request *sessionv1.QueryProjectSessionCommandRequestV2, callOptions ...callopt.Option) (r *sessionv1.QueryProjectSessionCommandResponseV2, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAgentSessionServiceV1Client{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAgentSessionServiceV1Client struct {
	*kClient
}

func (p *kAgentSessionServiceV1Client) EnsureProjectSessionV1(ctx context.Context, request *sessionv1.EnsureProjectSessionRequestV1, callOptions ...callopt.Option) (r *sessionv1.EnsureProjectSessionResponseV1, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EnsureProjectSessionV1(ctx, request)
}

func (p *kAgentSessionServiceV1Client) QueryProjectSessionCommandV1(ctx context.Context, request *sessionv1.QueryProjectSessionCommandRequestV1, callOptions ...callopt.Option) (r *sessionv1.QueryProjectSessionCommandResponseV1, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryProjectSessionCommandV1(ctx, request)
}

func (p *kAgentSessionServiceV1Client) EnsureProjectSessionV2(ctx context.Context, request *sessionv1.EnsureProjectSessionRequestV2, callOptions ...callopt.Option) (r *sessionv1.EnsureProjectSessionResponseV2, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EnsureProjectSessionV2(ctx, request)
}

func (p *kAgentSessionServiceV1Client) QueryProjectSessionCommandV2(ctx context.Context, request *sessionv1.QueryProjectSessionCommandRequestV2, callOptions ...callopt.Option) (r *sessionv1.QueryProjectSessionCommandResponseV2, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryProjectSessionCommandV2(ctx, request)
}
