// Code generated by Kitex v0.16.2. DO NOT EDIT.

package adminservice

import (
	"context"
	"errors"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateAdmin": kitex.NewMethodInfo(
		createAdminHandler,
		newAdminServiceCreateAdminArgs,
		newAdminServiceCreateAdminResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DisableAdmin": kitex.NewMethodInfo(
		disableAdminHandler,
		newAdminServiceDisableAdminArgs,
		newAdminServiceDisableAdminResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	adminServiceServiceInfo                = NewServiceInfo()
	adminServiceServiceInfoForClient       = NewServiceInfoForClient()
	adminServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return adminServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return adminServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return adminServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AdminService"
	handlerType := (*businessagent.AdminService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "businessagent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func createAdminHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.AdminServiceCreateAdminArgs)
	realResult := result.(*businessagent.AdminServiceCreateAdminResult)
	success, err := handler.(businessagent.AdminService).CreateAdmin(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdminServiceCreateAdminArgs() interface{} {
	return businessagent.NewAdminServiceCreateAdminArgs()
}

func newAdminServiceCreateAdminResult() interface{} {
	return businessagent.NewAdminServiceCreateAdminResult()
}

func disableAdminHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.AdminServiceDisableAdminArgs)
	realResult := result.(*businessagent.AdminServiceDisableAdminResult)
	success, err := handler.(businessagent.AdminService).DisableAdmin(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdminServiceDisableAdminArgs() interface{} {
	return businessagent.NewAdminServiceDisableAdminArgs()
}

func newAdminServiceDisableAdminResult() interface{} {
	return businessagent.NewAdminServiceDisableAdminResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateAdmin(ctx context.Context, req *businessagent.CreateAdminRequest) (r *businessagent.PlatformAdminDTO, err error) {
	var _args businessagent.AdminServiceCreateAdminArgs
	_args.Req = req
	var _result businessagent.AdminServiceCreateAdminResult
	if err = p.c.Call(ctx, "CreateAdmin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DisableAdmin(ctx context.Context, req *businessagent.DisableAdminRequest) (r *businessagent.PlatformAdminDTO, err error) {
	var _args businessagent.AdminServiceDisableAdminArgs
	_args.Req = req
	var _result businessagent.AdminServiceDisableAdminResult
	if err = p.c.Call(ctx, "DisableAdmin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
