// Code generated by Kitex v0.16.2. DO NOT EDIT.

package adminservice

import (
	"context"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateAdmin(ctx context.Context, req *businessagent.CreateAdminRequest, callOptions ...callopt.Option) (r *businessagent.PlatformAdminDTO, err error)
	DisableAdmin(ctx context.Context, req *businessagent.DisableAdminRequest, callOptions ...callopt.Option) (r *businessagent.PlatformAdminDTO, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAdminServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAdminServiceClient struct {
	*kClient
}

func (p *kAdminServiceClient) CreateAdmin(ctx context.Context, req *businessagent.CreateAdminRequest, callOptions ...callopt.Option) (r *businessagent.PlatformAdminDTO, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateAdmin(ctx, req)
}

func (p *kAdminServiceClient) DisableAdmin(ctx context.Context, req *businessagent.DisableAdminRequest, callOptions ...callopt.Option) (r *businessagent.PlatformAdminDTO, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DisableAdmin(ctx, req)
}
