// Code generated by Kitex v0.16.2. DO NOT EDIT.

package notificationservice

import (
	"context"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateNotification(ctx context.Context, req *businessagent.CreateNotificationRequest, callOptions ...callopt.Option) (r *businessagent.NotificationDTO, err error)
	ListNotifications(ctx context.Context, req *businessagent.ListNotificationsRequest, callOptions ...callopt.Option) (r *businessagent.ListNotificationsResponse, err error)
	GetUnreadCount(ctx context.Context, req *businessagent.GetUnreadCountRequest, callOptions ...callopt.Option) (r *businessagent.UnreadCountDTO, err error)
	MarkNotificationRead(ctx context.Context, req *businessagent.MarkNotificationReadRequest, callOptions ...callopt.Option) (r *businessagent.NotificationDTO, err error)
	MarkAllNotificationsRead(ctx context.Context, req *businessagent.MarkAllNotificationsReadRequest, callOptions ...callopt.Option) (r *businessagent.UnreadCountDTO, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kNotificationServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kNotificationServiceClient struct {
	*kClient
}

func (p *kNotificationServiceClient) CreateNotification(ctx context.Context, req *businessagent.CreateNotificationRequest, callOptions ...callopt.Option) (r *businessagent.NotificationDTO, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateNotification(ctx, req)
}

func (p *kNotificationServiceClient) ListNotifications(ctx context.Context, req *businessagent.ListNotificationsRequest, callOptions ...callopt.Option) (r *businessagent.ListNotificationsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListNotifications(ctx, req)
}

func (p *kNotificationServiceClient) GetUnreadCount(ctx context.Context, req *businessagent.GetUnreadCountRequest, callOptions ...callopt.Option) (r *businessagent.UnreadCountDTO, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUnreadCount(ctx, req)
}

func (p *kNotificationServiceClient) MarkNotificationRead(ctx context.Context, req *businessagent.MarkNotificationReadRequest, callOptions ...callopt.Option) (r *businessagent.NotificationDTO, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MarkNotificationRead(ctx, req)
}

func (p *kNotificationServiceClient) MarkAllNotificationsRead(ctx context.Context, req *businessagent.MarkAllNotificationsReadRequest, callOptions ...callopt.Option) (r *businessagent.UnreadCountDTO, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MarkAllNotificationsRead(ctx, req)
}
