// Code generated by Kitex v0.16.2. DO NOT EDIT.

package notificationservice

import (
	"context"
	"errors"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateNotification": kitex.NewMethodInfo(
		createNotificationHandler,
		newNotificationServiceCreateNotificationArgs,
		newNotificationServiceCreateNotificationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListNotifications": kitex.NewMethodInfo(
		listNotificationsHandler,
		newNotificationServiceListNotificationsArgs,
		newNotificationServiceListNotificationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUnreadCount": kitex.NewMethodInfo(
		getUnreadCountHandler,
		newNotificationServiceGetUnreadCountArgs,
		newNotificationServiceGetUnreadCountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"MarkNotificationRead": kitex.NewMethodInfo(
		markNotificationReadHandler,
		newNotificationServiceMarkNotificationReadArgs,
		newNotificationServiceMarkNotificationReadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"MarkAllNotificationsRead": kitex.NewMethodInfo(
		markAllNotificationsReadHandler,
		newNotificationServiceMarkAllNotificationsReadArgs,
		newNotificationServiceMarkAllNotificationsReadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	notificationServiceServiceInfo                = NewServiceInfo()
	notificationServiceServiceInfoForClient       = NewServiceInfoForClient()
	notificationServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return notificationServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return notificationServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return notificationServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "NotificationService"
	handlerType := (*businessagent.NotificationService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "businessagent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func createNotificationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.NotificationServiceCreateNotificationArgs)
	realResult := result.(*businessagent.NotificationServiceCreateNotificationResult)
	success, err := handler.(businessagent.NotificationService).CreateNotification(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNotificationServiceCreateNotificationArgs() interface{} {
	return businessagent.NewNotificationServiceCreateNotificationArgs()
}

func newNotificationServiceCreateNotificationResult() interface{} {
	return businessagent.NewNotificationServiceCreateNotificationResult()
}

func listNotificationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.NotificationServiceListNotificationsArgs)
	realResult := result.(*businessagent.NotificationServiceListNotificationsResult)
	success, err := handler.(businessagent.NotificationService).ListNotifications(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNotificationServiceListNotificationsArgs() interface{} {
	return businessagent.NewNotificationServiceListNotificationsArgs()
}

func newNotificationServiceListNotificationsResult() interface{} {
	return businessagent.NewNotificationServiceListNotificationsResult()
}

func getUnreadCountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.NotificationServiceGetUnreadCountArgs)
	realResult := result.(*businessagent.NotificationServiceGetUnreadCountResult)
	success, err := handler.(businessagent.NotificationService).GetUnreadCount(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNotificationServiceGetUnreadCountArgs() interface{} {
	return businessagent.NewNotificationServiceGetUnreadCountArgs()
}

func newNotificationServiceGetUnreadCountResult() interface{} {
	return businessagent.NewNotificationServiceGetUnreadCountResult()
}

func markNotificationReadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.NotificationServiceMarkNotificationReadArgs)
	realResult := result.(*businessagent.NotificationServiceMarkNotificationReadResult)
	success, err := handler.(businessagent.NotificationService).MarkNotificationRead(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNotificationServiceMarkNotificationReadArgs() interface{} {
	return businessagent.NewNotificationServiceMarkNotificationReadArgs()
}

func newNotificationServiceMarkNotificationReadResult() interface{} {
	return businessagent.NewNotificationServiceMarkNotificationReadResult()
}

func markAllNotificationsReadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.NotificationServiceMarkAllNotificationsReadArgs)
	realResult := result.(*businessagent.NotificationServiceMarkAllNotificationsReadResult)
	success, err := handler.(businessagent.NotificationService).MarkAllNotificationsRead(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNotificationServiceMarkAllNotificationsReadArgs() interface{} {
	return businessagent.NewNotificationServiceMarkAllNotificationsReadArgs()
}

func newNotificationServiceMarkAllNotificationsReadResult() interface{} {
	return businessagent.NewNotificationServiceMarkAllNotificationsReadResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateNotification(ctx context.Context, req *businessagent.CreateNotificationRequest) (r *businessagent.NotificationDTO, err error) {
	var _args businessagent.NotificationServiceCreateNotificationArgs
	_args.Req = req
	var _result businessagent.NotificationServiceCreateNotificationResult
	if err = p.c.Call(ctx, "CreateNotification", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListNotifications(ctx context.Context, req *businessagent.ListNotificationsRequest) (r *businessagent.ListNotificationsResponse, err error) {
	var _args businessagent.NotificationServiceListNotificationsArgs
	_args.Req = req
	var _result businessagent.NotificationServiceListNotificationsResult
	if err = p.c.Call(ctx, "ListNotifications", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUnreadCount(ctx context.Context, req *businessagent.GetUnreadCountRequest) (r *businessagent.UnreadCountDTO, err error) {
	var _args businessagent.NotificationServiceGetUnreadCountArgs
	_args.Req = req
	var _result businessagent.NotificationServiceGetUnreadCountResult
	if err = p.c.Call(ctx, "GetUnreadCount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MarkNotificationRead(ctx context.Context, req *businessagent.MarkNotificationReadRequest) (r *businessagent.NotificationDTO, err error) {
	var _args businessagent.NotificationServiceMarkNotificationReadArgs
	_args.Req = req
	var _result businessagent.NotificationServiceMarkNotificationReadResult
	if err = p.c.Call(ctx, "MarkNotificationRead", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MarkAllNotificationsRead(ctx context.Context, req *businessagent.MarkAllNotificationsReadRequest) (r *businessagent.UnreadCountDTO, err error) {
	var _args businessagent.NotificationServiceMarkAllNotificationsReadArgs
	_args.Req = req
	var _result businessagent.NotificationServiceMarkAllNotificationsReadResult
	if err = p.c.Call(ctx, "MarkAllNotificationsRead", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
