// Code generated by Kitex v0.16.2. DO NOT EDIT.

package businessskillmarketplaceservice

import (
	"context"
	"errors"
	businessskillmarketplace "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessskillmarketplace"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListMarketplaceSkills": kitex.NewMethodInfo(
		listMarketplaceSkillsHandler,
		newBusinessSkillMarketplaceServiceListMarketplaceSkillsArgs,
		newBusinessSkillMarketplaceServiceListMarketplaceSkillsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetMarketplaceSkill": kitex.NewMethodInfo(
		getMarketplaceSkillHandler,
		newBusinessSkillMarketplaceServiceGetMarketplaceSkillArgs,
		newBusinessSkillMarketplaceServiceGetMarketplaceSkillResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"InstallSkill": kitex.NewMethodInfo(
		installSkillHandler,
		newBusinessSkillMarketplaceServiceInstallSkillArgs,
		newBusinessSkillMarketplaceServiceInstallSkillResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpgradeSkillInstallation": kitex.NewMethodInfo(
		upgradeSkillInstallationHandler,
		newBusinessSkillMarketplaceServiceUpgradeSkillInstallationArgs,
		newBusinessSkillMarketplaceServiceUpgradeSkillInstallationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"EstimateSkillUsageCredits": kitex.NewMethodInfo(
		estimateSkillUsageCreditsHandler,
		newBusinessSkillMarketplaceServiceEstimateSkillUsageCreditsArgs,
		newBusinessSkillMarketplaceServiceEstimateSkillUsageCreditsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateSkillUsageRecord": kitex.NewMethodInfo(
		createSkillUsageRecordHandler,
		newBusinessSkillMarketplaceServiceCreateSkillUsageRecordArgs,
		newBusinessSkillMarketplaceServiceCreateSkillUsageRecordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FreezeSkillUsageCredits": kitex.NewMethodInfo(
		freezeSkillUsageCreditsHandler,
		newBusinessSkillMarketplaceServiceFreezeSkillUsageCreditsArgs,
		newBusinessSkillMarketplaceServiceFreezeSkillUsageCreditsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CommitSkillUsageAndSettle": kitex.NewMethodInfo(
		commitSkillUsageAndSettleHandler,
		newBusinessSkillMarketplaceServiceCommitSkillUsageAndSettleArgs,
		newBusinessSkillMarketplaceServiceCommitSkillUsageAndSettleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ReleaseSkillUsageFreeze": kitex.NewMethodInfo(
		releaseSkillUsageFreezeHandler,
		newBusinessSkillMarketplaceServiceReleaseSkillUsageFreezeArgs,
		newBusinessSkillMarketplaceServiceReleaseSkillUsageFreezeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	businessSkillMarketplaceServiceServiceInfo                = NewServiceInfo()
	businessSkillMarketplaceServiceServiceInfoForClient       = NewServiceInfoForClient()
	businessSkillMarketplaceServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return businessSkillMarketplaceServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return businessSkillMarketplaceServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return businessSkillMarketplaceServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "BusinessSkillMarketplaceService"
	handlerType := (*businessskillmarketplace.BusinessSkillMarketplaceService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "businessskillmarketplace",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func listMarketplaceSkillsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessskillmarketplace.BusinessSkillMarketplaceServiceListMarketplaceSkillsArgs)
	realResult := result.(*businessskillmarketplace.BusinessSkillMarketplaceServiceListMarketplaceSkillsResult)
	success, err := handler.(businessskillmarketplace.BusinessSkillMarketplaceService).ListMarketplaceSkills(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBusinessSkillMarketplaceServiceListMarketplaceSkillsArgs() interface{} {
	return businessskillmarketplace.NewBusinessSkillMarketplaceServiceListMarketplaceSkillsArgs()
}

func newBusinessSkillMarketplaceServiceListMarketplaceSkillsResult() interface{} {
	return businessskillmarketplace.NewBusinessSkillMarketplaceServiceListMarketplaceSkillsResult()
}

func getMarketplaceSkillHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessskillmarketplace.BusinessSkillMarketplaceServiceGetMarketplaceSkillArgs)
	realResult := result.(*businessskillmarketplace.BusinessSkillMarketplaceServiceGetMarketplaceSkillResult)
	success, err := handler.(businessskillmarketplace.BusinessSkillMarketplaceService).GetMarketplaceSkill(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBusinessSkillMarketplaceServiceGetMarketplaceSkillArgs() interface{} {
	return businessskillmarketplace.NewBusinessSkillMarketplaceServiceGetMarketplaceSkillArgs()
}

func newBusinessSkillMarketplaceServiceGetMarketplaceSkillResult() interface{} {
	return businessskillmarketplace.NewBusinessSkillMarketplaceServiceGetMarketplaceSkillResult()
}

func installSkillHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessskillmarketplace.BusinessSkillMarketplaceServiceInstallSkillArgs)
	realResult := result.(*businessskillmarketplace.BusinessSkillMarketplaceServiceInstallSkillResult)
	success, err := handler.(businessskillmarketplace.BusinessSkillMarketplaceService).InstallSkill(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBusinessSkillMarketplaceServiceInstallSkillArgs() interface{} {
	return businessskillmarketplace.NewBusinessSkillMarketplaceServiceInstallSkillArgs()
}

func newBusinessSkillMarketplaceServiceInstallSkillResult() interface{} {
	return businessskillmarketplace.NewBusinessSkillMarketplaceServiceInstallSkillResult()
}

func upgradeSkillInstallationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessskillmarketplace.BusinessSkillMarketplaceServiceUpgradeSkillInstallationArgs)
	realResult := result.(*businessskillmarketplace.BusinessSkillMarketplaceServiceUpgradeSkillInstallationResult)
	success, err := handler.(businessskillmarketplace.BusinessSkillMarketplaceService).UpgradeSkillInstallation(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBusinessSkillMarketplaceServiceUpgradeSkillInstallationArgs() interface{} {
	return businessskillmarketplace.NewBusinessSkillMarketplaceServiceUpgradeSkillInstallationArgs()
}

func newBusinessSkillMarketplaceServiceUpgradeSkillInstallationResult() interface{} {
	return businessskillmarketplace.NewBusinessSkillMarketplaceServiceUpgradeSkillInstallationResult()
}

func estimateSkillUsageCreditsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessskillmarketplace.BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsArgs)
	realResult := result.(*businessskillmarketplace.BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsResult)
	success, err := handler.(businessskillmarketplace.BusinessSkillMarketplaceService).EstimateSkillUsageCredits(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBusinessSkillMarketplaceServiceEstimateSkillUsageCreditsArgs() interface{} {
	return businessskillmarketplace.NewBusinessSkillMarketplaceServiceEstimateSkillUsageCreditsArgs()
}

func newBusinessSkillMarketplaceServiceEstimateSkillUsageCreditsResult() interface{} {
	return businessskillmarketplace.NewBusinessSkillMarketplaceServiceEstimateSkillUsageCreditsResult()
}

func createSkillUsageRecordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessskillmarketplace.BusinessSkillMarketplaceServiceCreateSkillUsageRecordArgs)
	realResult := result.(*businessskillmarketplace.BusinessSkillMarketplaceServiceCreateSkillUsageRecordResult)
	success, err := handler.(businessskillmarketplace.BusinessSkillMarketplaceService).CreateSkillUsageRecord(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBusinessSkillMarketplaceServiceCreateSkillUsageRecordArgs() interface{} {
	return businessskillmarketplace.NewBusinessSkillMarketplaceServiceCreateSkillUsageRecordArgs()
}

func newBusinessSkillMarketplaceServiceCreateSkillUsageRecordResult() interface{} {
	return businessskillmarketplace.NewBusinessSkillMarketplaceServiceCreateSkillUsageRecordResult()
}

func freezeSkillUsageCreditsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessskillmarketplace.BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsArgs)
	realResult := result.(*businessskillmarketplace.BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsResult)
	success, err := handler.(businessskillmarketplace.BusinessSkillMarketplaceService).FreezeSkillUsageCredits(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBusinessSkillMarketplaceServiceFreezeSkillUsageCreditsArgs() interface{} {
	return businessskillmarketplace.NewBusinessSkillMarketplaceServiceFreezeSkillUsageCreditsArgs()
}

func newBusinessSkillMarketplaceServiceFreezeSkillUsageCreditsResult() interface{} {
	return businessskillmarketplace.NewBusinessSkillMarketplaceServiceFreezeSkillUsageCreditsResult()
}

func commitSkillUsageAndSettleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessskillmarketplace.BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleArgs)
	realResult := result.(*businessskillmarketplace.BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleResult)
	success, err := handler.(businessskillmarketplace.BusinessSkillMarketplaceService).CommitSkillUsageAndSettle(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBusinessSkillMarketplaceServiceCommitSkillUsageAndSettleArgs() interface{} {
	return businessskillmarketplace.NewBusinessSkillMarketplaceServiceCommitSkillUsageAndSettleArgs()
}

func newBusinessSkillMarketplaceServiceCommitSkillUsageAndSettleResult() interface{} {
	return businessskillmarketplace.NewBusinessSkillMarketplaceServiceCommitSkillUsageAndSettleResult()
}

func releaseSkillUsageFreezeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessskillmarketplace.BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeArgs)
	realResult := result.(*businessskillmarketplace.BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeResult)
	success, err := handler.(businessskillmarketplace.BusinessSkillMarketplaceService).ReleaseSkillUsageFreeze(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBusinessSkillMarketplaceServiceReleaseSkillUsageFreezeArgs() interface{} {
	return businessskillmarketplace.NewBusinessSkillMarketplaceServiceReleaseSkillUsageFreezeArgs()
}

func newBusinessSkillMarketplaceServiceReleaseSkillUsageFreezeResult() interface{} {
	return businessskillmarketplace.NewBusinessSkillMarketplaceServiceReleaseSkillUsageFreezeResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListMarketplaceSkills(ctx context.Context, request *businessskillmarketplace.ListMarketplaceSkillsRequest) (r *businessskillmarketplace.ListMarketplaceSkillsResponse, err error) {
	var _args businessskillmarketplace.BusinessSkillMarketplaceServiceListMarketplaceSkillsArgs
	_args.Request = request
	var _result businessskillmarketplace.BusinessSkillMarketplaceServiceListMarketplaceSkillsResult
	if err = p.c.Call(ctx, "ListMarketplaceSkills", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetMarketplaceSkill(ctx context.Context, request *businessskillmarketplace.GetMarketplaceSkillRequest) (r *businessskillmarketplace.GetMarketplaceSkillResponse, err error) {
	var _args businessskillmarketplace.BusinessSkillMarketplaceServiceGetMarketplaceSkillArgs
	_args.Request = request
	var _result businessskillmarketplace.BusinessSkillMarketplaceServiceGetMarketplaceSkillResult
	if err = p.c.Call(ctx, "GetMarketplaceSkill", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) InstallSkill(ctx context.Context, request *businessskillmarketplace.InstallSkillRequest) (r *businessskillmarketplace.InstallSkillResponse, err error) {
	var _args businessskillmarketplace.BusinessSkillMarketplaceServiceInstallSkillArgs
	_args.Request = request
	var _result businessskillmarketplace.BusinessSkillMarketplaceServiceInstallSkillResult
	if err = p.c.Call(ctx, "InstallSkill", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpgradeSkillInstallation(ctx context.Context, request *businessskillmarketplace.UpgradeSkillInstallationRequest) (r *businessskillmarketplace.UpgradeSkillInstallationResponse, err error) {
	var _args businessskillmarketplace.BusinessSkillMarketplaceServiceUpgradeSkillInstallationArgs
	_args.Request = request
	var _result businessskillmarketplace.BusinessSkillMarketplaceServiceUpgradeSkillInstallationResult
	if err = p.c.Call(ctx, "UpgradeSkillInstallation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EstimateSkillUsageCredits(ctx context.Context, request *businessskillmarketplace.EstimateSkillUsageCreditsRequest) (r *businessskillmarketplace.EstimateSkillUsageCreditsResponse, err error) {
	var _args businessskillmarketplace.BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsArgs
	_args.Request = request
	var _result businessskillmarketplace.BusinessSkillMarketplaceServiceEstimateSkillUsageCreditsResult
	if err = p.c.Call(ctx, "EstimateSkillUsageCredits", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateSkillUsageRecord(ctx context.Context, request *businessskillmarketplace.CreateSkillUsageRecordRequest) (r *businessskillmarketplace.CreateSkillUsageRecordResponse, err error) {
	var _args businessskillmarketplace.BusinessSkillMarketplaceServiceCreateSkillUsageRecordArgs
	_args.Request = request
	var _result businessskillmarketplace.BusinessSkillMarketplaceServiceCreateSkillUsageRecordResult
	if err = p.c.Call(ctx, "CreateSkillUsageRecord", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FreezeSkillUsageCredits(ctx context.Context, request *businessskillmarketplace.FreezeSkillUsageCreditsRequest) (r *businessskillmarketplace.FreezeSkillUsageCreditsResponse, err error) {
	var _args businessskillmarketplace.BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsArgs
	_args.Request = request
	var _result businessskillmarketplace.BusinessSkillMarketplaceServiceFreezeSkillUsageCreditsResult
	if err = p.c.Call(ctx, "FreezeSkillUsageCredits", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommitSkillUsageAndSettle(ctx context.Context, request *businessskillmarketplace.CommitSkillUsageAndSettleRequest) (r *businessskillmarketplace.CommitSkillUsageAndSettleResponse, err error) {
	var _args businessskillmarketplace.BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleArgs
	_args.Request = request
	var _result businessskillmarketplace.BusinessSkillMarketplaceServiceCommitSkillUsageAndSettleResult
	if err = p.c.Call(ctx, "CommitSkillUsageAndSettle", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReleaseSkillUsageFreeze(ctx context.Context, request *businessskillmarketplace.ReleaseSkillUsageFreezeRequest) (r *businessskillmarketplace.ReleaseSkillUsageFreezeResponse, err error) {
	var _args businessskillmarketplace.BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeArgs
	_args.Request = request
	var _result businessskillmarketplace.BusinessSkillMarketplaceServiceReleaseSkillUsageFreezeResult
	if err = p.c.Call(ctx, "ReleaseSkillUsageFreeze", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
