// Code generated by Kitex v0.16.2. DO NOT EDIT.

package businessskillmarketplaceservice

import (
	"context"
	businessskillmarketplace "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessskillmarketplace"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ListMarketplaceSkills(ctx context.Context, request *businessskillmarketplace.ListMarketplaceSkillsRequest, callOptions ...callopt.Option) (r *businessskillmarketplace.ListMarketplaceSkillsResponse, err error)
	GetMarketplaceSkill(ctx context.Context, request *businessskillmarketplace.GetMarketplaceSkillRequest, callOptions ...callopt.Option) (r *businessskillmarketplace.GetMarketplaceSkillResponse, err error)
	InstallSkill(ctx context.Context, request *businessskillmarketplace.InstallSkillRequest, callOptions ...callopt.Option) (r *businessskillmarketplace.InstallSkillResponse, err error)
	UpgradeSkillInstallation(ctx context.Context, request *businessskillmarketplace.UpgradeSkillInstallationRequest, callOptions ...callopt.Option) (r *businessskillmarketplace.UpgradeSkillInstallationResponse, err error)
	EstimateSkillUsageCredits(ctx context.Context, request *businessskillmarketplace.EstimateSkillUsageCreditsRequest, callOptions ...callopt.Option) (r *businessskillmarketplace.EstimateSkillUsageCreditsResponse, err error)
	CreateSkillUsageRecord(ctx context.Context, request *businessskillmarketplace.CreateSkillUsageRecordRequest, callOptions ...callopt.Option) (r *businessskillmarketplace.CreateSkillUsageRecordResponse, err error)
	FreezeSkillUsageCredits(ctx context.Context, request *businessskillmarketplace.FreezeSkillUsageCreditsRequest, callOptions ...callopt.Option) (r *businessskillmarketplace.FreezeSkillUsageCreditsResponse, err error)
	CommitSkillUsageAndSettle(ctx context.Context, request *businessskillmarketplace.CommitSkillUsageAndSettleRequest, callOptions ...callopt.Option) (r *businessskillmarketplace.CommitSkillUsageAndSettleResponse, err error)
	ReleaseSkillUsageFreeze(ctx context.Context, request *businessskillmarketplace.ReleaseSkillUsageFreezeRequest, callOptions ...callopt.Option) (r *businessskillmarketplace.ReleaseSkillUsageFreezeResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kBusinessSkillMarketplaceServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kBusinessSkillMarketplaceServiceClient struct {
	*kClient
}

func (p *kBusinessSkillMarketplaceServiceClient) ListMarketplaceSkills(ctx context.Context, request *businessskillmarketplace.ListMarketplaceSkillsRequest, callOptions ...callopt.Option) (r *businessskillmarketplace.ListMarketplaceSkillsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListMarketplaceSkills(ctx, request)
}

func (p *kBusinessSkillMarketplaceServiceClient) GetMarketplaceSkill(ctx context.Context, request *businessskillmarketplace.GetMarketplaceSkillRequest, callOptions ...callopt.Option) (r *businessskillmarketplace.GetMarketplaceSkillResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMarketplaceSkill(ctx, request)
}

func (p *kBusinessSkillMarketplaceServiceClient) InstallSkill(ctx context.Context, request *businessskillmarketplace.InstallSkillRequest, callOptions ...callopt.Option) (r *businessskillmarketplace.InstallSkillResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.InstallSkill(ctx, request)
}

func (p *kBusinessSkillMarketplaceServiceClient) UpgradeSkillInstallation(ctx context.Context, request *businessskillmarketplace.UpgradeSkillInstallationRequest, callOptions ...callopt.Option) (r *businessskillmarketplace.UpgradeSkillInstallationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpgradeSkillInstallation(ctx, request)
}

func (p *kBusinessSkillMarketplaceServiceClient) EstimateSkillUsageCredits(ctx context.Context, request *businessskillmarketplace.EstimateSkillUsageCreditsRequest, callOptions ...callopt.Option) (r *businessskillmarketplace.EstimateSkillUsageCreditsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EstimateSkillUsageCredits(ctx, request)
}

func (p *kBusinessSkillMarketplaceServiceClient) CreateSkillUsageRecord(ctx context.Context, request *businessskillmarketplace.CreateSkillUsageRecordRequest, callOptions ...callopt.Option) (r *businessskillmarketplace.CreateSkillUsageRecordResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateSkillUsageRecord(ctx, request)
}

func (p *kBusinessSkillMarketplaceServiceClient) FreezeSkillUsageCredits(ctx context.Context, request *businessskillmarketplace.FreezeSkillUsageCreditsRequest, callOptions ...callopt.Option) (r *businessskillmarketplace.FreezeSkillUsageCreditsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FreezeSkillUsageCredits(ctx, request)
}

func (p *kBusinessSkillMarketplaceServiceClient) CommitSkillUsageAndSettle(ctx context.Context, request *businessskillmarketplace.CommitSkillUsageAndSettleRequest, callOptions ...callopt.Option) (r *businessskillmarketplace.CommitSkillUsageAndSettleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommitSkillUsageAndSettle(ctx, request)
}

func (p *kBusinessSkillMarketplaceServiceClient) ReleaseSkillUsageFreeze(ctx context.Context, request *businessskillmarketplace.ReleaseSkillUsageFreezeRequest, callOptions ...callopt.Option) (r *businessskillmarketplace.ReleaseSkillUsageFreezeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReleaseSkillUsageFreeze(ctx, request)
}
