// Code generated by Kitex v0.16.2. DO NOT EDIT.

package projectassetservice

import (
	"context"
	"errors"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"AttachAssetToProject": kitex.NewMethodInfo(
		attachAssetToProjectHandler,
		newProjectAssetServiceAttachAssetToProjectArgs,
		newProjectAssetServiceAttachAssetToProjectResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	projectAssetServiceServiceInfo                = NewServiceInfo()
	projectAssetServiceServiceInfoForClient       = NewServiceInfoForClient()
	projectAssetServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return projectAssetServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return projectAssetServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return projectAssetServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ProjectAssetService"
	handlerType := (*businessagent.ProjectAssetService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "businessagent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func attachAssetToProjectHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.ProjectAssetServiceAttachAssetToProjectArgs)
	realResult := result.(*businessagent.ProjectAssetServiceAttachAssetToProjectResult)
	success, err := handler.(businessagent.ProjectAssetService).AttachAssetToProject(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProjectAssetServiceAttachAssetToProjectArgs() interface{} {
	return businessagent.NewProjectAssetServiceAttachAssetToProjectArgs()
}

func newProjectAssetServiceAttachAssetToProjectResult() interface{} {
	return businessagent.NewProjectAssetServiceAttachAssetToProjectResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) AttachAssetToProject(ctx context.Context, req *businessagent.AttachAssetToProjectRequest) (r *businessagent.ProjectAssetDTO, err error) {
	var _args businessagent.ProjectAssetServiceAttachAssetToProjectArgs
	_args.Req = req
	var _result businessagent.ProjectAssetServiceAttachAssetToProjectResult
	if err = p.c.Call(ctx, "AttachAssetToProject", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
