// Code generated by Kitex v0.16.2. DO NOT EDIT.

package enterpriseservice

import (
	"context"
	"errors"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"PreviewTransferOwner": kitex.NewMethodInfo(
		previewTransferOwnerHandler,
		newEnterpriseServicePreviewTransferOwnerArgs,
		newEnterpriseServicePreviewTransferOwnerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ConfirmTransferOwner": kitex.NewMethodInfo(
		confirmTransferOwnerHandler,
		newEnterpriseServiceConfirmTransferOwnerArgs,
		newEnterpriseServiceConfirmTransferOwnerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	enterpriseServiceServiceInfo                = NewServiceInfo()
	enterpriseServiceServiceInfoForClient       = NewServiceInfoForClient()
	enterpriseServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return enterpriseServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return enterpriseServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return enterpriseServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "EnterpriseService"
	handlerType := (*businessagent.EnterpriseService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "businessagent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func previewTransferOwnerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.EnterpriseServicePreviewTransferOwnerArgs)
	realResult := result.(*businessagent.EnterpriseServicePreviewTransferOwnerResult)
	success, err := handler.(businessagent.EnterpriseService).PreviewTransferOwner(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newEnterpriseServicePreviewTransferOwnerArgs() interface{} {
	return businessagent.NewEnterpriseServicePreviewTransferOwnerArgs()
}

func newEnterpriseServicePreviewTransferOwnerResult() interface{} {
	return businessagent.NewEnterpriseServicePreviewTransferOwnerResult()
}

func confirmTransferOwnerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.EnterpriseServiceConfirmTransferOwnerArgs)
	realResult := result.(*businessagent.EnterpriseServiceConfirmTransferOwnerResult)
	success, err := handler.(businessagent.EnterpriseService).ConfirmTransferOwner(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newEnterpriseServiceConfirmTransferOwnerArgs() interface{} {
	return businessagent.NewEnterpriseServiceConfirmTransferOwnerArgs()
}

func newEnterpriseServiceConfirmTransferOwnerResult() interface{} {
	return businessagent.NewEnterpriseServiceConfirmTransferOwnerResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PreviewTransferOwner(ctx context.Context, req *businessagent.PreviewTransferOwnerRequest) (r *businessagent.TransferOwnerPreviewDTO, err error) {
	var _args businessagent.EnterpriseServicePreviewTransferOwnerArgs
	_args.Req = req
	var _result businessagent.EnterpriseServicePreviewTransferOwnerResult
	if err = p.c.Call(ctx, "PreviewTransferOwner", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfirmTransferOwner(ctx context.Context, req *businessagent.ConfirmTransferOwnerRequest) (r *businessagent.EnterpriseSummaryDTO, err error) {
	var _args businessagent.EnterpriseServiceConfirmTransferOwnerArgs
	_args.Req = req
	var _result businessagent.EnterpriseServiceConfirmTransferOwnerResult
	if err = p.c.Call(ctx, "ConfirmTransferOwner", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
