// Code generated by Kitex v0.16.2. DO NOT EDIT.

package agentsessionservicev1

import (
	"context"
	"errors"
	sessionv1 "github.com/FigoGoo/Dora-Agent/agent/kitex_gen/sessionv1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"EnsureProjectSessionV1": kitex.NewMethodInfo(
		ensureProjectSessionV1Handler,
		newAgentSessionServiceV1EnsureProjectSessionV1Args,
		newAgentSessionServiceV1EnsureProjectSessionV1Result,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryProjectSessionCommandV1": kitex.NewMethodInfo(
		queryProjectSessionCommandV1Handler,
		newAgentSessionServiceV1QueryProjectSessionCommandV1Args,
		newAgentSessionServiceV1QueryProjectSessionCommandV1Result,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"EnsureProjectSessionV2": kitex.NewMethodInfo(
		ensureProjectSessionV2Handler,
		newAgentSessionServiceV1EnsureProjectSessionV2Args,
		newAgentSessionServiceV1EnsureProjectSessionV2Result,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryProjectSessionCommandV2": kitex.NewMethodInfo(
		queryProjectSessionCommandV2Handler,
		newAgentSessionServiceV1QueryProjectSessionCommandV2Args,
		newAgentSessionServiceV1QueryProjectSessionCommandV2Result,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	agentSessionServiceV1ServiceInfo                = NewServiceInfo()
	agentSessionServiceV1ServiceInfoForClient       = NewServiceInfoForClient()
	agentSessionServiceV1ServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return agentSessionServiceV1ServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return agentSessionServiceV1ServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return agentSessionServiceV1ServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AgentSessionServiceV1"
	handlerType := (*sessionv1.AgentSessionServiceV1)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "sessionv1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func ensureProjectSessionV1Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sessionv1.AgentSessionServiceV1EnsureProjectSessionV1Args)
	realResult := result.(*sessionv1.AgentSessionServiceV1EnsureProjectSessionV1Result)
	success, err := handler.(sessionv1.AgentSessionServiceV1).EnsureProjectSessionV1(ctx, realArg.Request)
	if err != nil {
		switch v := err.(type) {
		case *sessionv1.SessionServiceExceptionV1:
			realResult.ServiceError = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newAgentSessionServiceV1EnsureProjectSessionV1Args() interface{} {
	return sessionv1.NewAgentSessionServiceV1EnsureProjectSessionV1Args()
}

func newAgentSessionServiceV1EnsureProjectSessionV1Result() interface{} {
	return sessionv1.NewAgentSessionServiceV1EnsureProjectSessionV1Result()
}

func queryProjectSessionCommandV1Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sessionv1.AgentSessionServiceV1QueryProjectSessionCommandV1Args)
	realResult := result.(*sessionv1.AgentSessionServiceV1QueryProjectSessionCommandV1Result)
	success, err := handler.(sessionv1.AgentSessionServiceV1).QueryProjectSessionCommandV1(ctx, realArg.Request)
	if err != nil {
		switch v := err.(type) {
		case *sessionv1.SessionServiceExceptionV1:
			realResult.ServiceError = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newAgentSessionServiceV1QueryProjectSessionCommandV1Args() interface{} {
	return sessionv1.NewAgentSessionServiceV1QueryProjectSessionCommandV1Args()
}

func newAgentSessionServiceV1QueryProjectSessionCommandV1Result() interface{} {
	return sessionv1.NewAgentSessionServiceV1QueryProjectSessionCommandV1Result()
}

func ensureProjectSessionV2Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sessionv1.AgentSessionServiceV1EnsureProjectSessionV2Args)
	realResult := result.(*sessionv1.AgentSessionServiceV1EnsureProjectSessionV2Result)
	success, err := handler.(sessionv1.AgentSessionServiceV1).EnsureProjectSessionV2(ctx, realArg.Request)
	if err != nil {
		switch v := err.(type) {
		case *sessionv1.SessionServiceExceptionV1:
			realResult.ServiceError = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newAgentSessionServiceV1EnsureProjectSessionV2Args() interface{} {
	return sessionv1.NewAgentSessionServiceV1EnsureProjectSessionV2Args()
}

func newAgentSessionServiceV1EnsureProjectSessionV2Result() interface{} {
	return sessionv1.NewAgentSessionServiceV1EnsureProjectSessionV2Result()
}

func queryProjectSessionCommandV2Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sessionv1.AgentSessionServiceV1QueryProjectSessionCommandV2Args)
	realResult := result.(*sessionv1.AgentSessionServiceV1QueryProjectSessionCommandV2Result)
	success, err := handler.(sessionv1.AgentSessionServiceV1).QueryProjectSessionCommandV2(ctx, realArg.Request)
	if err != nil {
		switch v := err.(type) {
		case *sessionv1.SessionServiceExceptionV1:
			realResult.ServiceError = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newAgentSessionServiceV1QueryProjectSessionCommandV2Args() interface{} {
	return sessionv1.NewAgentSessionServiceV1QueryProjectSessionCommandV2Args()
}

func newAgentSessionServiceV1QueryProjectSessionCommandV2Result() interface{} {
	return sessionv1.NewAgentSessionServiceV1QueryProjectSessionCommandV2Result()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) EnsureProjectSessionV1(ctx context.Context, request *sessionv1.EnsureProjectSessionRequestV1) (r *sessionv1.EnsureProjectSessionResponseV1, err error) {
	var _args sessionv1.AgentSessionServiceV1EnsureProjectSessionV1Args
	_args.Request = request
	var _result sessionv1.AgentSessionServiceV1EnsureProjectSessionV1Result
	if err = p.c.Call(ctx, "EnsureProjectSessionV1", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.ServiceError != nil:
		return r, _result.ServiceError
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryProjectSessionCommandV1(ctx context.Context, request *sessionv1.QueryProjectSessionCommandRequestV1) (r *sessionv1.QueryProjectSessionCommandResponseV1, err error) {
	var _args sessionv1.AgentSessionServiceV1QueryProjectSessionCommandV1Args
	_args.Request = request
	var _result sessionv1.AgentSessionServiceV1QueryProjectSessionCommandV1Result
	if err = p.c.Call(ctx, "QueryProjectSessionCommandV1", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.ServiceError != nil:
		return r, _result.ServiceError
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EnsureProjectSessionV2(ctx context.Context, request *sessionv1.EnsureProjectSessionRequestV2) (r *sessionv1.EnsureProjectSessionResponseV2, err error) {
	var _args sessionv1.AgentSessionServiceV1EnsureProjectSessionV2Args
	_args.Request = request
	var _result sessionv1.AgentSessionServiceV1EnsureProjectSessionV2Result
	if err = p.c.Call(ctx, "EnsureProjectSessionV2", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.ServiceError != nil:
		return r, _result.ServiceError
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryProjectSessionCommandV2(ctx context.Context, request *sessionv1.QueryProjectSessionCommandRequestV2) (r *sessionv1.QueryProjectSessionCommandResponseV2, err error) {
	var _args sessionv1.AgentSessionServiceV1QueryProjectSessionCommandV2Args
	_args.Request = request
	var _result sessionv1.AgentSessionServiceV1QueryProjectSessionCommandV2Result
	if err = p.c.Call(ctx, "QueryProjectSessionCommandV2", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.ServiceError != nil:
		return r, _result.ServiceError
	}
	return _result.GetSuccess(), nil
}
