// Code generated by Kitex v0.16.2. DO NOT EDIT.

package modelconfigservice

import (
	"context"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ListAvailableGenerationModels(ctx context.Context, req *businessagent.ListAvailableGenerationModelsRequest, callOptions ...callopt.Option) (r *businessagent.ListAvailableGenerationModelsResponse, err error)
	ResolveDefaultModel(ctx context.Context, req *businessagent.ResolveDefaultModelRequest, callOptions ...callopt.Option) (r *businessagent.ModelSummaryDTO, err error)
	ResolveGenerationModelSnapshot(ctx context.Context, req *businessagent.ResolveGenerationModelSnapshotRequest, callOptions ...callopt.Option) (r *businessagent.ModelRuntimeSnapshotDTO, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kModelConfigServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kModelConfigServiceClient struct {
	*kClient
}

func (p *kModelConfigServiceClient) ListAvailableGenerationModels(ctx context.Context, req *businessagent.ListAvailableGenerationModelsRequest, callOptions ...callopt.Option) (r *businessagent.ListAvailableGenerationModelsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAvailableGenerationModels(ctx, req)
}

func (p *kModelConfigServiceClient) ResolveDefaultModel(ctx context.Context, req *businessagent.ResolveDefaultModelRequest, callOptions ...callopt.Option) (r *businessagent.ModelSummaryDTO, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ResolveDefaultModel(ctx, req)
}

func (p *kModelConfigServiceClient) ResolveGenerationModelSnapshot(ctx context.Context, req *businessagent.ResolveGenerationModelSnapshotRequest, callOptions ...callopt.Option) (r *businessagent.ModelRuntimeSnapshotDTO, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ResolveGenerationModelSnapshot(ctx, req)
}
