// Code generated by Kitex v0.16.2. DO NOT EDIT.

package modelconfigservice

import (
	"context"
	"errors"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListAvailableGenerationModels": kitex.NewMethodInfo(
		listAvailableGenerationModelsHandler,
		newModelConfigServiceListAvailableGenerationModelsArgs,
		newModelConfigServiceListAvailableGenerationModelsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ResolveDefaultModel": kitex.NewMethodInfo(
		resolveDefaultModelHandler,
		newModelConfigServiceResolveDefaultModelArgs,
		newModelConfigServiceResolveDefaultModelResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ResolveGenerationModelSnapshot": kitex.NewMethodInfo(
		resolveGenerationModelSnapshotHandler,
		newModelConfigServiceResolveGenerationModelSnapshotArgs,
		newModelConfigServiceResolveGenerationModelSnapshotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	modelConfigServiceServiceInfo                = NewServiceInfo()
	modelConfigServiceServiceInfoForClient       = NewServiceInfoForClient()
	modelConfigServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return modelConfigServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return modelConfigServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return modelConfigServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ModelConfigService"
	handlerType := (*businessagent.ModelConfigService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "businessagent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func listAvailableGenerationModelsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.ModelConfigServiceListAvailableGenerationModelsArgs)
	realResult := result.(*businessagent.ModelConfigServiceListAvailableGenerationModelsResult)
	success, err := handler.(businessagent.ModelConfigService).ListAvailableGenerationModels(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newModelConfigServiceListAvailableGenerationModelsArgs() interface{} {
	return businessagent.NewModelConfigServiceListAvailableGenerationModelsArgs()
}

func newModelConfigServiceListAvailableGenerationModelsResult() interface{} {
	return businessagent.NewModelConfigServiceListAvailableGenerationModelsResult()
}

func resolveDefaultModelHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.ModelConfigServiceResolveDefaultModelArgs)
	realResult := result.(*businessagent.ModelConfigServiceResolveDefaultModelResult)
	success, err := handler.(businessagent.ModelConfigService).ResolveDefaultModel(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newModelConfigServiceResolveDefaultModelArgs() interface{} {
	return businessagent.NewModelConfigServiceResolveDefaultModelArgs()
}

func newModelConfigServiceResolveDefaultModelResult() interface{} {
	return businessagent.NewModelConfigServiceResolveDefaultModelResult()
}

func resolveGenerationModelSnapshotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.ModelConfigServiceResolveGenerationModelSnapshotArgs)
	realResult := result.(*businessagent.ModelConfigServiceResolveGenerationModelSnapshotResult)
	success, err := handler.(businessagent.ModelConfigService).ResolveGenerationModelSnapshot(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newModelConfigServiceResolveGenerationModelSnapshotArgs() interface{} {
	return businessagent.NewModelConfigServiceResolveGenerationModelSnapshotArgs()
}

func newModelConfigServiceResolveGenerationModelSnapshotResult() interface{} {
	return businessagent.NewModelConfigServiceResolveGenerationModelSnapshotResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListAvailableGenerationModels(ctx context.Context, req *businessagent.ListAvailableGenerationModelsRequest) (r *businessagent.ListAvailableGenerationModelsResponse, err error) {
	var _args businessagent.ModelConfigServiceListAvailableGenerationModelsArgs
	_args.Req = req
	var _result businessagent.ModelConfigServiceListAvailableGenerationModelsResult
	if err = p.c.Call(ctx, "ListAvailableGenerationModels", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ResolveDefaultModel(ctx context.Context, req *businessagent.ResolveDefaultModelRequest) (r *businessagent.ModelSummaryDTO, err error) {
	var _args businessagent.ModelConfigServiceResolveDefaultModelArgs
	_args.Req = req
	var _result businessagent.ModelConfigServiceResolveDefaultModelResult
	if err = p.c.Call(ctx, "ResolveDefaultModel", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ResolveGenerationModelSnapshot(ctx context.Context, req *businessagent.ResolveGenerationModelSnapshotRequest) (r *businessagent.ModelRuntimeSnapshotDTO, err error) {
	var _args businessagent.ModelConfigServiceResolveGenerationModelSnapshotArgs
	_args.Req = req
	var _result businessagent.ModelConfigServiceResolveGenerationModelSnapshotResult
	if err = p.c.Call(ctx, "ResolveGenerationModelSnapshot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
