// Code generated by Kitex v0.16.2. DO NOT EDIT.

package platformdictionaryservice

import (
	"context"
	"errors"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListAssetElementTypes": kitex.NewMethodInfo(
		listAssetElementTypesHandler,
		newPlatformDictionaryServiceListAssetElementTypesArgs,
		newPlatformDictionaryServiceListAssetElementTypesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	platformDictionaryServiceServiceInfo                = NewServiceInfo()
	platformDictionaryServiceServiceInfoForClient       = NewServiceInfoForClient()
	platformDictionaryServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return platformDictionaryServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return platformDictionaryServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return platformDictionaryServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PlatformDictionaryService"
	handlerType := (*businessagent.PlatformDictionaryService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "businessagent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func listAssetElementTypesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.PlatformDictionaryServiceListAssetElementTypesArgs)
	realResult := result.(*businessagent.PlatformDictionaryServiceListAssetElementTypesResult)
	success, err := handler.(businessagent.PlatformDictionaryService).ListAssetElementTypes(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPlatformDictionaryServiceListAssetElementTypesArgs() interface{} {
	return businessagent.NewPlatformDictionaryServiceListAssetElementTypesArgs()
}

func newPlatformDictionaryServiceListAssetElementTypesResult() interface{} {
	return businessagent.NewPlatformDictionaryServiceListAssetElementTypesResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListAssetElementTypes(ctx context.Context, req *businessagent.ListAssetElementTypesRequest) (r *businessagent.ListAssetElementTypesResponse, err error) {
	var _args businessagent.PlatformDictionaryServiceListAssetElementTypesArgs
	_args.Req = req
	var _result businessagent.PlatformDictionaryServiceListAssetElementTypesResult
	if err = p.c.Call(ctx, "ListAssetElementTypes", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
