// Code generated by Kitex v0.16.2. DO NOT EDIT.

package accountspaceservice

import (
	"context"
	"errors"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ResolveCurrentSpaceContext": kitex.NewMethodInfo(
		resolveCurrentSpaceContextHandler,
		newAccountSpaceServiceResolveCurrentSpaceContextArgs,
		newAccountSpaceServiceResolveCurrentSpaceContextResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	accountSpaceServiceServiceInfo                = NewServiceInfo()
	accountSpaceServiceServiceInfoForClient       = NewServiceInfoForClient()
	accountSpaceServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return accountSpaceServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return accountSpaceServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return accountSpaceServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AccountSpaceService"
	handlerType := (*businessagent.AccountSpaceService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "businessagent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func resolveCurrentSpaceContextHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.AccountSpaceServiceResolveCurrentSpaceContextArgs)
	realResult := result.(*businessagent.AccountSpaceServiceResolveCurrentSpaceContextResult)
	success, err := handler.(businessagent.AccountSpaceService).ResolveCurrentSpaceContext(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAccountSpaceServiceResolveCurrentSpaceContextArgs() interface{} {
	return businessagent.NewAccountSpaceServiceResolveCurrentSpaceContextArgs()
}

func newAccountSpaceServiceResolveCurrentSpaceContextResult() interface{} {
	return businessagent.NewAccountSpaceServiceResolveCurrentSpaceContextResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ResolveCurrentSpaceContext(ctx context.Context, req *businessagent.ResolveCurrentSpaceContextRequest) (r *businessagent.ResolveCurrentSpaceContextResponse, err error) {
	var _args businessagent.AccountSpaceServiceResolveCurrentSpaceContextArgs
	_args.Req = req
	var _result businessagent.AccountSpaceServiceResolveCurrentSpaceContextResult
	if err = p.c.Call(ctx, "ResolveCurrentSpaceContext", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
