// Code generated by Kitex v0.16.2. DO NOT EDIT.

package toolcapabilityservice

import (
	"context"
	"errors"
	businessagent "github.com/FigoGoo/Dora-Agent/kitex_gen/dora/api/businessagent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CheckToolExecutionPolicy": kitex.NewMethodInfo(
		checkToolExecutionPolicyHandler,
		newToolCapabilityServiceCheckToolExecutionPolicyArgs,
		newToolCapabilityServiceCheckToolExecutionPolicyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	toolCapabilityServiceServiceInfo                = NewServiceInfo()
	toolCapabilityServiceServiceInfoForClient       = NewServiceInfoForClient()
	toolCapabilityServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return toolCapabilityServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return toolCapabilityServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return toolCapabilityServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ToolCapabilityService"
	handlerType := (*businessagent.ToolCapabilityService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "businessagent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func checkToolExecutionPolicyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*businessagent.ToolCapabilityServiceCheckToolExecutionPolicyArgs)
	realResult := result.(*businessagent.ToolCapabilityServiceCheckToolExecutionPolicyResult)
	success, err := handler.(businessagent.ToolCapabilityService).CheckToolExecutionPolicy(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newToolCapabilityServiceCheckToolExecutionPolicyArgs() interface{} {
	return businessagent.NewToolCapabilityServiceCheckToolExecutionPolicyArgs()
}

func newToolCapabilityServiceCheckToolExecutionPolicyResult() interface{} {
	return businessagent.NewToolCapabilityServiceCheckToolExecutionPolicyResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CheckToolExecutionPolicy(ctx context.Context, req *businessagent.CheckToolExecutionPolicyRequest) (r *businessagent.ToolExecutionPolicyResponse, err error) {
	var _args businessagent.ToolCapabilityServiceCheckToolExecutionPolicyArgs
	_args.Req = req
	var _result businessagent.ToolCapabilityServiceCheckToolExecutionPolicyResult
	if err = p.c.Call(ctx, "CheckToolExecutionPolicy", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
